using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
namespace SplifyWin {
  public sealed class UpdateAsset {public string name{get;set;}public string browser_download_url{get;set;}public long size{get;set;}public string digest{get;set;}}
  public sealed class UpdateRelease {public string tag_name{get;set;}public string html_url{get;set;}public bool draft{get;set;}public bool prerelease{get;set;}public DateTime published_at{get;set;}public List<UpdateAsset> assets{get;set;}}
  public sealed class UpdateInstallation {public string Version{get;set;}public string Directory{get;set;}public string File{get;set;}public string Sha256{get;set;}}
  public sealed class UpdatePreferences {public bool CheckOnStart{get;set;}public Dictionary<string,string> Skipped{get;set;}public Dictionary<string,UpdateInstallation> Installed{get;set;}public UpdatePreferences(){CheckOnStart=true;Skipped=new Dictionary<string,string>();Installed=new Dictionary<string,UpdateInstallation>();}}
  public sealed class UpdateItem {
    public string Id,Name,Group,Current,Version,Status,Url,Kind,Text,Snapshot,AppliedVersion;
    public UpdateAsset Asset;public EnginePackage Package;public bool Available,Ignored;
    public bool IsCurrent{get{return !Available&&!String.IsNullOrEmpty(Status)&&Status.IndexOf("актуал",StringComparison.OrdinalIgnoreCase)>=0&&!Status.StartsWith("Не удалось");}}
    public string DisplayStatus{get{return IsCurrent?"Актуально":Status;}}
    public string Fingerprint{get{return Version+"|"+(Asset==null?Package==null?"":Package.Sha256:Asset.digest??"");}}
  }
  public sealed class AppUpdates : IDisposable {
    readonly NetworkCore core;readonly string root;readonly Func<string,Task<string>> fetch;readonly JavaScriptSerializer json=new JavaScriptSerializer{MaxJsonLength=10485760};readonly CancellationTokenSource lifetime=new CancellationTokenSource();readonly Dictionary<string,Task<UpdateRelease[]>> releaseCache=new Dictionary<string,Task<UpdateRelease[]>>();
    public UpdatePreferences Preferences{get;private set;}public List<UpdateItem> Items{get;private set;}public DateTime CheckedAt{get;private set;}public bool Checking{get;private set;}public bool Installing{get;private set;}public int Progress{get;private set;}public string Activity{get;private set;}
    public AppUpdates(NetworkCore network,Func<string,Task<string>> download=null){core=network;root=Path.Combine(core.DataRoot,"updates");var source=download??core.DownloadRemoteTextAsync;fetch=url=>RetryDownload(url,source,lifetime.Token);Preferences=ReadPreferences(core.DataRoot);Items=new List<UpdateItem>();}
    public static async Task<string> RetryDownload(string url,Func<string,Task<string>> download,CancellationToken token,Func<int,Task> pause=null){for(int attempt=0;attempt<3;attempt++){token.ThrowIfCancellationRequested();try{return await download(url);}catch(OperationCanceledException){throw;}catch(Exception ex){if(attempt==2||!Regex.IsMatch(ex.Message??"",@"curl:\s*\((6|28)\)|Resolving timed out|Could not resolve host",RegexOptions.IgnoreCase))throw;}if(pause!=null)await pause((attempt+1)*1000);else await Task.Delay((attempt+1)*1000,token);}throw new InvalidOperationException("Источник не ответил.");}
    public static UpdatePreferences ReadPreferences(string dataRoot){try{var p=new JavaScriptSerializer().Deserialize<UpdatePreferences>(File.ReadAllText(Path.Combine(dataRoot,"updates","preferences.json")));if(p!=null&&p.Skipped!=null&&p.Installed!=null)return p;}catch(IOException){}catch(UnauthorizedAccessException){}catch(ArgumentException){}return new UpdatePreferences();}
    public static void AtomicText(string path,string text){Directory.CreateDirectory(Path.GetDirectoryName(path));string temp=path+".new-"+Guid.NewGuid().ToString("N");try{File.WriteAllText(temp,text,new UTF8Encoding(false));if(File.Exists(path))File.Replace(temp,path,path+".previous");else File.Move(temp,path);}finally{if(File.Exists(temp))File.Delete(temp);}}
    public void Save(){AtomicText(Path.Combine(root,"preferences.json"),json.Serialize(Preferences));}
    public void Skip(IEnumerable<UpdateItem> items){foreach(var row in items.Where(x=>x.Available))Preferences.Skipped[row.Id]=row.Fingerprint;Save();MarkIgnored();}
    public void MarkIgnored(){foreach(var row in Items){string version;row.Ignored=Preferences.Skipped.TryGetValue(row.Id,out version)&&version==row.Fingerprint;}}
    public static string Hash(byte[] bytes){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-","").ToLowerInvariant();}
    public static string HashFile(string file){using(var s=File.OpenRead(file))using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(s)).Replace("-","").ToLowerInvariant();}
    public static string TextVersion(string text){return Hash(Encoding.UTF8.GetBytes((text??"").Replace("\r\n","\n").Trim().TrimStart('\uFEFF')));}
    public static string ListVersion(string text){var parsed=RouteCompiler.Parse(text??"");return TextVersion(String.Join("\n",parsed.OrderBy(p=>p.Key,StringComparer.Ordinal).SelectMany(p=>p.Value.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(v=>v,StringComparer.OrdinalIgnoreCase).Select(v=>p.Key+":"+v.ToLowerInvariant()))));}
    public static int CompareVersion(string a,string b){var x=Regex.Matches(a??"",@"\d+").Cast<Match>().Select(m=>Int64.Parse(m.Value)).ToArray();var y=Regex.Matches(b??"",@"\d+").Cast<Match>().Select(m=>Int64.Parse(m.Value)).ToArray();for(int i=0;i<Math.Max(x.Length,y.Length);i++){int c=(i<x.Length?x[i]:0).CompareTo(i<y.Length?y[i]:0);if(c!=0)return c;}return 0;}
    public static UpdateRelease Latest(IEnumerable<UpdateRelease> releases,Func<UpdateRelease,bool> filter){return releases.Where(r=>!r.draft&&!r.prerelease&&filter(r)).OrderByDescending(r=>r.tag_name,Comparer<string>.Create(CompareVersion)).ThenByDescending(r=>r.published_at).FirstOrDefault();}
    public static bool SafeAsset(UpdateAsset asset,string repository){Uri u;return asset!=null&&asset.size>0&&asset.size<=160000000&&Regex.IsMatch(asset.digest??"",@"^sha256:[a-fA-F0-9]{64}$")&&Uri.TryCreate(asset.browser_download_url,UriKind.Absolute,out u)&&u.Scheme=="https"&&u.Host=="github.com"&&u.AbsolutePath.StartsWith("/"+repository+"/releases/download/",StringComparison.Ordinal)&&u.UserInfo.Length==0;}
    public static string ActiveFile(string dataRoot,string id,string fallback){var p=ReadPreferences(dataRoot);UpdateInstallation item;if(!p.Installed.TryGetValue(id,out item))return fallback;try{string folder=Path.GetFullPath(Path.Combine(dataRoot,"updates","installed"))+Path.DirectorySeparatorChar;string path=Path.GetFullPath(Path.Combine(item.Directory,item.File));if(!path.StartsWith(folder,StringComparison.OrdinalIgnoreCase)&&String.Equals(Path.GetFileName(Path.GetFullPath(dataRoot).TrimEnd(Path.DirectorySeparatorChar)),"mcrf",StringComparison.OrdinalIgnoreCase)){string legacy=Path.GetFullPath(Path.Combine(dataRoot,"..","splify-win","updates","installed"))+Path.DirectorySeparatorChar;if(path.StartsWith(legacy,StringComparison.OrdinalIgnoreCase))path=Path.GetFullPath(Path.Combine(folder,path.Substring(legacy.Length)));}return path.StartsWith(folder,StringComparison.OrdinalIgnoreCase)&&File.Exists(path)&&HashFile(path)==item.Sha256?path:fallback;}catch(IOException){return fallback;}catch(ArgumentException){return fallback;}catch(UnauthorizedAccessException){return fallback;}}
    string Current(string id,string fallback){UpdateInstallation p;return Preferences.Installed.TryGetValue(id,out p)&&ActiveFile(core.DataRoot,id,"")!=""?p.Version:fallback;}
    Task<UpdateRelease[]> Releases(string repo){lock(releaseCache){Task<UpdateRelease[]> data;if(!releaseCache.TryGetValue(repo,out data)){data=ReadReleases(repo);releaseCache[repo]=data;}return data;}}
    async Task<UpdateRelease[]> ReadReleases(string repo){string data=await fetch("https://api.github.com/repos/"+repo+"/releases?per_page=100");lifetime.Token.ThrowIfCancellationRequested();return json.Deserialize<UpdateRelease[]>(data);}
    string EmbeddedText(string suffix){using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("SplifyWin.Zapret."+suffix))using(var reader=new StreamReader(s))return reader.ReadToEnd();}
    public async Task Check(ClientState state){if(Checking||Installing)return;Checking=true;lock(releaseCache)releaseCache.Clear();Activity="Проверяем источники…";var result=new List<UpdateItem>();var gate=new SemaphoreSlim(3);var operations=new List<Task>();
      Func<UpdateItem,Func<UpdateItem,Task>,Task> check=async(row,job)=>{await gate.WaitAsync(lifetime.Token);try{await job(row);}catch(OperationCanceledException){throw;}catch(Exception ex){row.Available=false;row.Status="Не удалось проверить: "+ex.Message;}finally{gate.Release();lock(result)result.Add(row);}};
      operations.Add(check(new UpdateItem{Id="app",Name="MCRF",Group="Программа",Current=Assembly.GetExecutingAssembly().GetName().Version.ToString(3),Kind="app"},async row=>{var release=Latest(await Releases("vnenapravo7-source/mcrf"),r=>(r.assets??new List<UpdateAsset>()).Any(a=>a.name.Equals("mcrf.exe",StringComparison.OrdinalIgnoreCase)));if(release==null){row.Status="Релиза программы ещё нет · пакеты движков не считаются обновлением MCRF";return;}Release(row,release,"mcrf.exe","vnenapravo7-source/mcrf");}));
      operations.Add(check(new UpdateItem{Id="singbox",Name="sing-box-lx / AmneziaWG",Group="Движки",Current=Current("singbox","1.14.2-lx.11"),Kind="link"},async row=>{var r=Latest(await Releases("Leadaxe/sing-box-lx"),v=>true);if(r==null){row.Status="Нет стабильного релиза";return;}row.Version=r.tag_name;row.Url=r.html_url;row.Available=CompareVersion(row.Version,row.Current)>0;row.Status=row.Available?"Есть upstream-версия · нужна сборка с AmneziaWG, автоматически не подменяем":"Установленная версия актуальна или новее стабильного релиза";}));
      foreach(var spec in new[]{new[]{"telegram","Telegram WS","y0sy4/telegram-proxy","v2.0.7","TgWsProxy_lite_windows_amd64.exe","exe"},new[]{"warp","WARP · WarpScout","vernette/warpscout","v0.16.0","windows_amd64.zip","warp"},new[]{"zapret","Zapret · движок и Flowseal","Flowseal/zapret-discord-youtube","1.10.3",".zip","zapret"}}){var s=spec;operations.Add(check(new UpdateItem{Id=s[0],Name=s[1],Group="Движки",Current=Current(s[0],s[3]),Kind=s[5]},async row=>{var release=Latest(await Releases(s[2]),r=>true);if(release==null){row.Status="Нет стабильного релиза";return;}Release(row,release,s[4],s[2]);}));}
      operations.Add(check(new UpdateItem{Id="optional",Name="Каталог дополнительных движков",Group="Движки",Kind="catalog"},async row=>{var releases=await Releases("vnenapravo7-source/mcrf");var release=releases.Where(r=>!r.draft&&!r.prerelease&&(r.assets??new List<UpdateAsset>()).Any(a=>a.name=="engine-catalog.json")).OrderByDescending(r=>r.published_at).FirstOrDefault();if(release==null){row.Status="Каталог движков не опубликован";return;}var asset=release.assets.Single(a=>a.name=="engine-catalog.json");if(!SafeAsset(asset,"vnenapravo7-source/mcrf"))throw new InvalidDataException("Нет SHA-256 каталога");var data=await fetch(asset.browser_download_url);if(Hash(Encoding.UTF8.GetBytes(data))!=asset.digest.Substring(7))throw new InvalidDataException("SHA-256 каталога не совпал");var catalog=json.Deserialize<EngineCatalog>(data);OptionalEngines.ValidateCatalog(catalog);foreach(var p in catalog.Engines){var current=core.Engines.Package(p.Id);bool installed=core.Engines.Installed(p.Id);var entry=new UpdateItem{Id="engine:"+p.Id,Name=p.Name,Group="Дополнительные движки",Current=installed?current.Version:"Не установлен",Version=p.Version,Package=p,Kind="optional",Url=release.html_url,Available=installed&&p.Sha256!=current.Sha256&&CompareVersion(p.Version,current.Version)>=0,Status=installed?p.Sha256==current.Sha256?"Актуальный пакет MCRF":CompareVersion(p.Version,current.Version)<0?"Установленная версия новее каталога":"Новый совместимый пакет MCRF":"Не установлен · можно скачать выбранный движок"};lock(result)result.Add(entry);}row.Status="Проверено 3 совместимых пакета";row.Version=release.tag_name;row.Url=release.html_url;}));
      foreach(var spec in new[]{new[]{"v-config","Стратегии V","v.md","Strategies.md"},new[]{"youtube-config","Стратегии YouTube","youtube.md","Strategies_For_Youtube.md"}}){var s=spec;operations.Add(check(new UpdateItem{Id=s[0],Name=s[1],Group="Конфиги Zapret",Kind="text",Url="https://raw.githubusercontent.com/StressOzz/Zapret-Manager/main/"+s[3]},async row=>{string local=ActiveFile(core.DataRoot,row.Id,null);row.Snapshot=local==null?EmbeddedText(s[2]):File.ReadAllText(local);row.Text=await fetch(row.Url);ValidateStrategies(s[0],row.Text);row.Current=TextVersion(row.Snapshot);row.Version=TextVersion(row.Text);row.Available=row.Version!=row.Current;row.Status=row.Available?"Стратегии изменились · после обновления повторите проверки":"Стратегии актуальны";}));}
      operations.Add(check(new UpdateItem{Id="flowseal-config",Name="Стратегии Flowseal",Group="Конфиги Zapret",Current=CompareVersion(Current("flowseal-config","1.10.3"),Current("zapret","1.10.3"))>=0?Current("flowseal-config","1.10.3"):Current("zapret","1.10.3"),Kind="flowseal"},async row=>{var release=Latest(await Releases("Flowseal/zapret-discord-youtube"),r=>true);if(release!=null)Release(row,release,".zip","Flowseal/zapret-discord-youtube");else row.Status="Нет стабильного релиза";}));
      foreach(var list in state.Lists.Where(l=>RouteSources.Urls(l).Length>0)){var l=list;operations.Add(check(new UpdateItem{Id="list:"+l.Id,Name=ZapretStrategy.CleanLabel(l.Name),Group=ZapretRoutes.IsZapret(l)||state.ZapretProfiles.Any(p=>(p.Settings.ScopeSources??new List<string>()).Contains("list:"+l.Id))?"Списки Zapret":"Списки маршрутизации",Current=ListVersion(l.Text),Snapshot=l.Text,Url=RouteSources.Identity(l),Kind="list"},async row=>{row.Text=RouteSources.UpdatedText(l,String.Join("\n",await Task.WhenAll(RouteSources.Urls(l).Select(url=>fetch(url)))));ValidateList(row.Text,l);row.Version=ListVersion(row.Text);row.Available=row.Version!=row.Current;row.Status=row.Available?"Список изменился · текущие подключения не перезапускаются":"Список актуален";}));}
      try{await Task.WhenAll(operations);lifetime.Token.ThrowIfCancellationRequested();Items=result.OrderBy(i=>i.Group).ThenBy(i=>i.Name).ToList();CheckedAt=DateTime.Now;MarkIgnored();Activity="Проверено · "+Items.Count(i=>i.Available)+" обновлений";}finally{Checking=false;gate.Dispose();}
    }
    void Release(UpdateItem row,UpdateRelease release,string assetSuffix,string repo){row.Version=release.tag_name;row.Url=release.html_url;row.Asset=(release.assets??new List<UpdateAsset>()).FirstOrDefault(a=>a.name.EndsWith(assetSuffix,StringComparison.OrdinalIgnoreCase));row.Available=CompareVersion(row.Version,row.Current)>0;row.Status=!row.Available?"Актуально":SafeAsset(row.Asset,repo)?"Доступна новая версия · "+(row.Asset.size/1000000d).ToString("0.0")+" МБ":"Версия есть, но нет проверяемого Windows-пакета · откройте релиз";if(row.Available&&!SafeAsset(row.Asset,repo))row.Kind="link";if(row.Id=="app"&&row.Available&&row.Kind=="app"){UpdateInstallation staged;if(Preferences.Installed.TryGetValue("app-stage",out staged)&&staged.Version==row.Version&&staged.Sha256==row.Asset.digest.Substring(7))row.AppliedVersion=ActiveFile(core.DataRoot,"app-stage",null);} }
    public static void ValidateStrategies(string id,string text){if(String.IsNullOrWhiteSpace(text)||text.Length>2000000||!text.Contains("--dpi-desync=")||!(id=="v-config"?Regex.IsMatch(text,@"(?m)^# v\d+"):Regex.IsMatch(text,@"(?m)^#Yv\d+")))throw new InvalidDataException("Источник не содержит ожидаемых стратегий");}
    public static void ValidateList(string text,RouteList original){if(String.IsNullOrWhiteSpace(text)||text.Length>64*1024*1024||text.TrimStart().StartsWith("<"))throw new InvalidDataException("Пустой список или HTML вместо списка");var copy=new RouteList{Text=text,MatchMode=original.MatchMode};var parsed=RouteCompiler.Parse(text);if(parsed.Values.Sum(x=>x.Count)==0)throw new InvalidDataException("Список не содержит адресов / приложений");RouteCompiler.Compile(copy,"direct");if(ZapretRoutes.IsZapret(original))ZapretScope.Validate(copy);}
    public async Task Apply(UpdateItem row,ClientState state,StateStore store){if(Installing||Checking)throw new InvalidOperationException("Дождитесь текущей операции");if(!Items.Contains(row)||(!row.Available&&!(row.Kind=="optional"&&!core.Engines.Installed(row.Package.Id)))||row.Kind=="link"||row.Kind=="catalog")throw new InvalidOperationException("Нет устанавливаемого обновления");Installing=true;Progress=0;Activity="Подготовка: "+row.Name;string staging=null;try{
        if(row.Kind=="list"){var list=state.Lists.FirstOrDefault(l=>"list:"+l.Id==row.Id);if(list==null||RouteSources.Identity(list)!=row.Url||TextVersion(list.Text)!=TextVersion(row.Snapshot))throw new InvalidOperationException("Список изменён после проверки. Проверьте обновления заново");ValidateList(row.Text,list);AtomicText(Path.Combine(root,"backups",list.Id+"-"+DateTime.UtcNow.ToString("yyyyMMdd-HHmmssfff")+".txt"),list.Text);string old=list.Text;list.Text=row.Text;try{store.Save(state);}catch{list.Text=old;throw;}}
        else if(row.Kind=="optional"){await core.Engines.InstallUpdate(row.Package);}
        else if(row.Kind=="text"){ValidateStrategies(row.Id,row.Text);string dir=Path.Combine(root,"installed",row.Id+"-"+row.Version.Substring(0,12));string file=row.Id=="v-config"?"v.md":"youtube.md";AtomicText(Path.Combine(dir,file),row.Text);Activate(row,dir,file);}
        else{string repository=row.Id=="app"?"vnenapravo7-source/mcrf":row.Id=="telegram"?"y0sy4/telegram-proxy":row.Id=="warp"?"vernette/warpscout":row.Id=="zapret"||row.Id=="flowseal-config"?"Flowseal/zapret-discord-youtube":"";if(repository.Length==0||!SafeAsset(row.Asset,repository))throw new InvalidDataException("Непроверяемый источник обновления");string dir=Path.Combine(root,"installed",row.Id+"-"+Guid.NewGuid().ToString("N"));staging=dir;Directory.CreateDirectory(dir);string archive=Path.Combine(dir,"download.bin");await Download(row.Asset,archive,lifetime.Token);string file=row.Kind=="app"?"mcrf.exe":row.Kind=="exe"?"tgws.exe":row.Kind=="warp"?"warpscout.exe":"flowseal.zip";
          if(row.Kind=="exe"||row.Kind=="app"){ValidatePe(archive,row.Kind=="app");File.Move(archive,Path.Combine(dir,file));}
          else if(row.Kind=="warp"){ExtractSelected(archive,dir,new[]{"warpscout.exe","LICENSE"});ValidatePe(Path.Combine(dir,file));File.Delete(archive);}
          else{File.Move(archive,Path.Combine(dir,file));ValidateFlowseal(Path.Combine(dir,file));if(row.Kind=="zapret")ExtractZapret(Path.Combine(dir,file),dir);}
          if(row.Kind=="app"){var staged=new UpdateItem{Id="app-stage",Version=row.Version};Activate(staged,dir,file);row.AppliedVersion=Path.Combine(dir,file);row.Status="Скачано и проверено · нажмите «Установить и перезапустить»";}
          else Activate(row,dir,file);staging=null;
        }
        if(row.Kind!="app"){row.Current=row.Version;row.Available=false;row.Status="Обновлено · для активного подключения включите модуль заново";}Progress=100;Activity="Готово: "+row.Name;
      }catch(Exception){Activity="Обновление не применено: "+row.Name;throw;}finally{Installing=false;if(staging!=null){string prefix=Path.GetFullPath(Path.Combine(root,"installed"))+Path.DirectorySeparatorChar;if(!Path.GetFullPath(staging).StartsWith(prefix,StringComparison.OrdinalIgnoreCase)||!Regex.IsMatch(Path.GetFileName(staging),@"-[a-f0-9]{32}$"))throw new IOException("Небезопасный путь временного обновления");try{if(Directory.Exists(staging))Directory.Delete(staging,true);}catch(IOException){}catch(UnauthorizedAccessException){}}}
    }
    void Activate(UpdateItem row,string dir,string file){UpdateInstallation previous;Preferences.Installed.TryGetValue(row.Id,out previous);Preferences.Installed[row.Id]=new UpdateInstallation{Version=row.Version,Directory=dir,File=file,Sha256=HashFile(Path.Combine(dir,file))};try{Save();}catch{if(previous==null)Preferences.Installed.Remove(row.Id);else Preferences.Installed[row.Id]=previous;throw;}}
    async Task Download(UpdateAsset asset,string file,CancellationToken token){if(asset==null||!Regex.IsMatch(asset.digest??"",@"^sha256:[a-fA-F0-9]{64}$"))throw new InvalidDataException("Отсутствует SHA-256 пакета");var psi=new ProcessStartInfo(core.CurlExecutable,"--silent --show-error --fail --location --noproxy \"*\" --connect-timeout 10 --max-time 180 --max-filesize "+asset.size+" --proto =https --proto-redir =https --cacert "+ZapretRuntime.Quote(Path.Combine(core.DataRoot,"core","curl-ca-bundle.crt"))+" --output "+ZapretRuntime.Quote(file)+" "+ZapretRuntime.Quote(asset.browser_download_url)){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};using(var p=OwnedJob.Start(psi)){var output=p.StandardOutput.ReadToEndAsync();var errors=p.StandardError.ReadToEndAsync();try{while(!p.HasExited){token.ThrowIfCancellationRequested();long received=File.Exists(file)?new FileInfo(file).Length:0;if(received>asset.size)throw new InvalidDataException("Превышен размер пакета");Progress=(int)(received*90/asset.size);Activity="Загрузка: "+(received/1000000d).ToString("0.0")+" / "+(asset.size/1000000d).ToString("0.0")+" МБ";await Task.Delay(120,token);}await output;await errors;token.ThrowIfCancellationRequested();if(p.ExitCode!=0||!File.Exists(file)||new FileInfo(file).Length!=asset.size)throw new IOException("Пакет не скачан полностью · код "+p.ExitCode);Progress=95;if(HashFile(file)!=asset.digest.Substring(7).ToLowerInvariant())throw new InvalidDataException("SHA-256 не совпал. Обновление не применено");}finally{if(!p.HasExited)try{p.Kill();}catch{}}}}
    public static void ValidatePe(string path,bool managedAllowed=false){using(var s=File.OpenRead(path))using(var r=new BinaryReader(s)){if(s.Length<128||r.ReadUInt16()!=0x5A4D)throw new InvalidDataException("Файл не является Windows-программой");s.Position=60;int offset=r.ReadInt32();if(offset<64||offset>s.Length-6)throw new InvalidDataException("Повреждён PE-файл");s.Position=offset;if(r.ReadUInt32()!=0x4550)throw new InvalidDataException("Повреждён PE-файл");ushort machine=r.ReadUInt16();if(machine==0x8664)return;if(managedAllowed&&machine==0x14c){s.Position=offset+24;if(r.ReadUInt16()==0x10b&&s.Length>offset+24+96+14*8+8){s.Position=offset+24+96+14*8;if(r.ReadUInt32()!=0&&r.ReadUInt32()>=72)return;}}throw new InvalidDataException("Нужна сборка Windows x64 или .NET AnyCPU для MCRF");}}
    public static void ValidateFlowseal(string path){using(var zip=ZipFile.OpenRead(path)){if(zip.Entries.Count>1500||zip.Entries.Sum(e=>e.Length)>50000000||!zip.Entries.Any(e=>e.FullName.EndsWith("/bin/winws.exe"))||!zip.Entries.Any(e=>Path.GetFileName(e.FullName).StartsWith("general")&&e.FullName.EndsWith(".bat")))throw new InvalidDataException("Неожиданный состав Flowseal");foreach(var e in zip.Entries)SafeEntry(e);}}
    static void SafeEntry(ZipArchiveEntry e){if(e.FullName.StartsWith("/")||e.FullName.Contains("\\")||e.FullName.Contains(":")||e.FullName.Split('/').Any(p=>p=="..")||((e.ExternalAttributes>>16)&0xF000)==0xA000||e.Length>100000000)throw new InvalidDataException("Небезопасный путь в архиве");}
    public static void ExtractSelected(string archive,string destination,string[] names){using(var zip=ZipFile.OpenRead(archive)){if(zip.Entries.Count>1500||zip.Entries.Sum(e=>e.Length)>200000000)throw new InvalidDataException("Слишком большой архив");foreach(var name in names){var matches=zip.Entries.Where(e=>Path.GetFileName(e.FullName)==name).ToArray();if(matches.Length==0&&name=="LICENSE")continue;if(matches.Length!=1)throw new InvalidDataException("Нет однозначного файла "+name);SafeEntry(matches[0]);matches[0].ExtractToFile(Path.Combine(destination,name));}}}
    static void ExtractZapret(string archive,string directory){using(var zip=ZipFile.OpenRead(archive)){var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var e in zip.Entries.Where(e=>e.FullName.Contains("/bin/")&&!String.IsNullOrEmpty(e.Name))){SafeEntry(e);if(!Regex.IsMatch(e.Name,@"^[a-zA-Z0-9_.-]+$")||!seen.Add(e.Name))throw new InvalidDataException("Неоднозначный файл Zapret");e.ExtractToFile(Path.Combine(directory,e.Name));}}ValidatePe(Path.Combine(directory,"winws.exe"));}
    public void Dispose(){lifetime.Cancel();}
  }
}
