using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.WinForms;

namespace SplifyWin {
  internal static class VideoBrowserLibraries {
    static readonly object installLock=new object();internal static string libraryRoot;static bool installed;
    [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern IntPtr LoadLibrary(string path);
    internal static void Install(string root){lock(installLock){if(installed)return;libraryRoot=Path.Combine(root,"video-browser");Directory.CreateDirectory(libraryRoot);
      foreach(string name in new[]{"Microsoft.Web.WebView2.Core.dll","Microsoft.Web.WebView2.WinForms.dll","WebView2Loader.dll","LICENSE.txt","NOTICE.txt"})BundledResources.Install("SplifyWin.Video."+name,Path.Combine(libraryRoot,name));
      AppDomain.CurrentDomain.AssemblyResolve+=(s,e)=>{string name=new AssemblyName(e.Name).Name;if(name!="Microsoft.Web.WebView2.Core"&&name!="Microsoft.Web.WebView2.WinForms")return null;return Assembly.LoadFrom(Path.Combine(libraryRoot,name+".dll"));};
      if(LoadLibrary(Path.Combine(libraryRoot,"WebView2Loader.dll"))==IntPtr.Zero)throw new InvalidOperationException("Не удалось загрузить компонент видеопроверки");installed=true;
    }}
  }

  // One private browser per attempt; never import the user's cookies or credentials.
  internal sealed class BrowserVideoProbe : IDisposable {
readonly string proxy,target;readonly bool pornhub,instagram;internal Action<int,double> FrameProgress;
    Dictionary<string,object> latestSample;
    const string PornSample="(()=>{let visible=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).display!=='none';let gate=[...document.querySelectorAll('#ageVerificationModal,#age-verification-wrapper,.ageDisclaimer,.age-verification,.ageVerification')].find(visible);let text=document.body?document.body.innerText:'';let ageText=/18\\s*(лет|years)|over\\s*18|older than 18|мне.*18|исполнилось.*18/i.test(gate?gate.innerText:text);let confirmation=ageText?[...(gate||document).querySelectorAll('button,a,[role=button],input[type=button],input[type=submit]')].find(b=>visible(b)&&/^(да|yes|i am 18 or older(?:[ \\u2013\\u2014-]+enter)?|i am over 18|i.m 18 or older|мне (уже )?(есть )?18( лет)?|мне исполнилось 18( лет)?|enter|enter pornhub|войти)([.! ]*)$/i.test((b.innerText||b.value||'').trim())):null;if(confirmation)confirmation.click();let v=[...document.querySelectorAll('video')].find(v=>visible(v)&&!v.closest('.videoAdUi,.ad-showing,.video-ad'))||[...document.querySelectorAll('video')].find(v=>!v.closest('.videoAdUi,.ad-showing,.video-ad')),a=[...document.querySelectorAll('a[href]')].find(a=>a.href.includes('/view_video.php?viewkey=')&&/pornhub\\.(org|com)$/.test(new URL(a.href).hostname));if(v){v.muted=true;v.play().catch(()=>{});}return {id:location.pathname.includes('view_video.php')?'pornhub':'',ad:[...document.querySelectorAll('.videoAdUi,.ad-showing')].some(visible),time:v?v.currentTime:0,width:v?v.videoWidth:0,frames:v&&v.getVideoPlaybackQuality?v.getVideoPlaybackQuality().totalVideoFrames:0,error:v&&v.error?v.error.code:0,blocked:/captcha|verify you are human|verify your identity|upload.*(id|passport)/i.test(text),ready:document.readyState,links:document.querySelectorAll('a[href]').length,identityGate:!!gate&&/VK ID|ВКонтакте|upload.*(id|passport)|verify your identity/i.test(gate.innerText),ageGate:!!gate&&!confirmation,ageConfirmed:!!confirmation,ageButtons:gate?[...gate.querySelectorAll('button,a,[role=button],input[type=button],input[type=submit]')].filter(visible).map(b=>(b.innerText||b.value||'').trim().slice(0,100)).join(' / '):'',page:location.hostname+location.pathname,next:a?a.href:''};})()";
    const string YoutubeSample="(()=>{let reject=[...document.querySelectorAll('button')].find(b=>/^(Reject all|Отклонить все)$/.test(b.innerText.trim()));if(reject)reject.click();let v=[...document.querySelectorAll('video')].find(v=>{let r=v.getBoundingClientRect();return r.width>0&&r.height>0&&r.bottom>0&&r.right>0&&r.top<innerHeight&&r.left<innerWidth;})||document.querySelector('video'),p=(v&&v.closest('.html5-video-player'))||document.getElementById('movie_player'),d=p&&p.getVideoData?p.getVideoData():{};if(v){v.muted=true;v.play().catch(()=>{});}let text=document.body?document.body.innerText:'';return {shorts:[...new Set([...document.querySelectorAll('a[href]')].map(a=>a.getAttribute('href')).filter(h=>h&&h.startsWith('/shorts/')&&/^[A-Za-z0-9_-]{11}(?:[?]|$)/.test(h.slice(8))))],ready:document.readyState,links:document.querySelectorAll('a[href]').length,playerError:document.querySelector('.ytp-error-content-wrap-reason')?document.querySelector('.ytp-error-content-wrap-reason').innerText.slice(0,220):'',id:location.pathname.startsWith('/shorts/')?location.pathname.split('/')[2]:(d.video_id||''),ad:!!p&&p.classList.contains('ad-showing'),time:v?v.currentTime:0,width:v?v.videoWidth:0,frames:v&&v.getVideoPlaybackQuality?v.getVideoPlaybackQuality().totalVideoFrames:0,error:v&&v.error?v.error.code:0,blocked:/Sign in to confirm|подтвердить.*не бот|подтвердите.*не бот/i.test(text)};})()";
    internal static bool PornHost(string host){return host=="rt.pornhub.com"||host=="rt.pornhub.org"||host=="www.pornhub.org"||host=="pornhub.org"||host=="www.pornhub.com"||host=="pornhub.com";}
    readonly SemaphoreSlim gate=new SemaphoreSlim(1);
    readonly TaskCompletionSource<bool> ready=new TaskCompletionSource<bool>();
    Form host;WebView2 view;Thread thread;string profile;bool disposed;
    bool mediaResponse;int browserProcessId;int navigationError;bool navigationLoaded;string browserFailure;string initializationFailure;
    const string InstagramSample="(()=>{let v=[...document.querySelectorAll('video')].find(v=>{let r=v.getBoundingClientRect();return r.width>0&&r.height>0;});if(v){v.muted=true;v.play().catch(()=>{});}return {id:location.pathname==='/p/Da-ePNVMV_M/'?'Da-ePNVMV_M':'',ad:false,time:v?v.currentTime:0,width:v?v.videoWidth:0,frames:v&&v.getVideoPlaybackQuality?v.getVideoPlaybackQuality().totalVideoFrames:0,error:v&&v.error?v.error.code:0,blocked:false,ready:document.readyState,links:document.querySelectorAll('a[href]').length};})()";
    internal BrowserVideoProbe(string proxy,string target){this.proxy=proxy;this.target=target;pornhub=target==VideoProbe.PornhubTarget;instagram=target==ManualServiceChecks.InstagramReel;}
    [MethodImpl(MethodImplOptions.NoInlining)]void Start(){
      if(thread!=null)return;profile=Path.Combine(VideoBrowserLibraries.libraryRoot,"sessions",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(profile);
      thread=new Thread(()=>{try{host=new Form{ShowInTaskbar=false,StartPosition=FormStartPosition.Manual,Location=new Point(-20000,-20000),Size=new Size(640,480)};view=new WebView2{Dock=DockStyle.Fill};host.Controls.Add(view);
        host.Shown+=async(s,e)=>{try{
          var options=new CoreWebView2EnvironmentOptions("--disable-quic --autoplay-policy=no-user-gesture-required --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows --disable-features=CalculateNativeWinOcclusion "+(String.IsNullOrEmpty(proxy)?"--no-proxy-server":"--proxy-server="+proxy)){AllowSingleSignOnUsingOSPrimaryAccount=false};
          var environment=await CoreWebView2Environment.CreateAsync(null,profile,options);environment.BrowserProcessExited+=(a,b)=>CleanProfile();await view.EnsureCoreWebView2Async(environment);
          var browser=view.CoreWebView2;browserProcessId=(int)browser.BrowserProcessId;browser.IsMuted=true;browser.Settings.AreDefaultContextMenusEnabled=false;browser.Settings.AreDevToolsEnabled=false;browser.Settings.AreHostObjectsAllowed=false;browser.Settings.IsPasswordAutosaveEnabled=false;browser.Settings.IsGeneralAutofillEnabled=false;
          browser.PermissionRequested+=(a,b)=>b.State=CoreWebView2PermissionState.Deny;browser.NewWindowRequested+=(a,b)=>b.Handled=true;browser.DownloadStarting+=(a,b)=>b.Cancel=true;browser.ServerCertificateErrorDetected+=(a,b)=>b.Action=CoreWebView2ServerCertificateErrorAction.Cancel;
browser.NavigationStarting+=(a,b)=>{Uri uri;if(!Uri.TryCreate(b.Uri,UriKind.Absolute,out uri)||b.Uri!="about:blank"&&(uri.Scheme!="https"||uri.Port!=443||uri.UserInfo.Length>0||!(instagram?HostsCandidates.AllowedDomain("instagram",uri.Host):pornhub?PornHost(uri.Host):(uri.Host=="www.youtube.com"||uri.Host=="consent.youtube.com"))))b.Cancel=true;};
          browser.NavigationCompleted+=(a,b)=>{navigationLoaded=b.IsSuccess;if(!b.IsSuccess&&b.WebErrorStatus!=CoreWebView2WebErrorStatus.ConnectionAborted&&b.WebErrorStatus!=CoreWebView2WebErrorStatus.OperationCanceled)navigationError=(int)b.WebErrorStatus;};
          browser.WebResourceResponseReceived+=(a,b)=>{Uri media;bool allowed=pornhub?Uri.TryCreate(b.Request.Uri,UriKind.Absolute,out media)&&media.Scheme=="https"&&media.Port==443&&media.UserInfo.Length==0&&(media.Host=="phncdn.com"||media.Host.EndsWith(".phncdn.com",StringComparison.OrdinalIgnoreCase)):VideoProbe.Allowed(b.Request.Uri);if(allowed&&(b.Response.StatusCode==200||b.Response.StatusCode==206)&&b.Response.Headers.Contains("Content-Type")&&b.Response.Headers.GetHeader("Content-Type").StartsWith("video/",StringComparison.OrdinalIgnoreCase))mediaResponse=true;};
          browser.ProcessFailed+=(a,b)=>browserFailure="Процесс видеопроигрывателя завершился";
await browser.CallDevToolsProtocolMethodAsync("Network.enable","{}");await browser.CallDevToolsProtocolMethodAsync("Network.setCacheDisabled","{\"cacheDisabled\":true}");browser.WebMessageReceived+=(a,b)=>{try{Uri source;if(!Uri.TryCreate(b.Source,UriKind.Absolute,out source)||source.Scheme!="https"||source.Port!=443||!(instagram?HostsCandidates.AllowedDomain("instagram",source.Host):pornhub?PornHost(source.Host):source.Host=="www.youtube.com"||source.Host=="consent.youtube.com"))return;var envelope=new JavaScriptSerializer().DeserializeObject(b.WebMessageAsJson) as Dictionary<string,object>;object value;if(envelope!=null&&envelope.TryGetValue("mcrfVideoSample",out value))latestSample=value as Dictionary<string,object>;}catch{}};await browser.AddScriptToExecuteOnDocumentCreatedAsync("if(window.top===window){setInterval(()=>{try{window.chrome.webview.postMessage({mcrfVideoSample:"+(instagram?InstagramSample:pornhub?PornSample:YoutubeSample)+"});}catch(e){}},250);}");ready.TrySetResult(true);
        }catch(Exception ex){initializationFailure=ex.GetType().Name+": "+ex.Message;ready.TrySetResult(false);host.Close();}};Application.Run(host);
      }catch(Exception ex){initializationFailure=ex.GetType().Name+": "+ex.Message;ready.TrySetResult(false);}finally{if(view!=null)view.Dispose();if(host!=null)host.Dispose();ready.TrySetResult(false);ThreadPool.QueueUserWorkItem(o=>{try{using(var owned=Process.GetProcessById(browserProcessId)){if(!owned.WaitForExit(10000))return;}}catch{}CleanProfile();});}}){IsBackground=true,Name="MCRF video check"};thread.SetApartmentState(ApartmentState.STA);thread.Start();
    }
    internal static bool Played(Dictionary<string,object> sample,double previousTime,int previousFrames){
      return PlayedFor(sample,previousTime,previousFrames,"jNQXAC9IVRw");
    }
    internal static bool PlayedFor(Dictionary<string,object> sample,double previousTime,int previousFrames,string expected){return !String.IsNullOrEmpty(expected)&&sample!=null&&sample.ContainsKey("id")&&Convert.ToString(sample["id"])==expected&&!Convert.ToBoolean(sample["ad"])&&Convert.ToInt32(sample["width"])>0&&Convert.ToInt32(sample["error"])==0&&Convert.ToDouble(sample["time"])>=previousTime+3&&Convert.ToInt32(sample["frames"])>=previousFrames+20;}
    internal static bool PornPlayed(Dictionary<string,object> sample,double previousTime,int previousFrames){return sample!=null&&sample.ContainsKey("id")&&Convert.ToString(sample["id"])=="pornhub"&&!Convert.ToBoolean(sample["ad"])&&Convert.ToInt32(sample["width"])>0&&Convert.ToInt32(sample["error"])==0&&Convert.ToDouble(sample["time"])>=previousTime+3&&Convert.ToInt32(sample["frames"])>=previousFrames+20;}
    static async Task<T> Within<T>(Task<T> pending,int milliseconds,CancellationToken token){if(await Task.WhenAny(pending,Task.Delay(Math.Max(1,milliseconds),token))!=pending){token.ThrowIfCancellationRequested();var observation=pending.ContinueWith(t=>{var ignored=t.Exception;},TaskContinuationOptions.OnlyOnFaulted);throw new TimeoutException();}return await pending;}
    async Task<ZapretEndpointResult> Check(CancellationToken token){
      var result=new ZapretEndpointResult{Url=target,Access=ServiceAccess.Unknown};var watch=Stopwatch.StartNew();Dictionary<string,object> last=null;latestSample=null;mediaResponse=false;navigationError=0;navigationLoaded=false;browserFailure=null;
      try{
        token.ThrowIfCancellationRequested();
        view.CoreWebView2.Navigate(target+(pornhub?"":target.Contains("?")?"&autoplay=1":"?autoplay=1"));double previousTime=-1;int previousFrames=0;
bool shortLink=target.StartsWith("https://www.youtube.com/shorts/",StringComparison.Ordinal);bool randomShort=target==VideoProbe.ShortsTarget||shortLink;string expectedVideo=shortLink?new Uri(target).AbsolutePath.Substring(8,11):randomShort?null:instagram?"Da-ePNVMV_M":"jNQXAC9IVRw";var triedShorts=new HashSet<string>();if(shortLink)triedShorts.Add(new Uri(target).PathAndQuery);bool selectedPornVideo=false;int budget=pornhub||randomShort?12000:8000;


        while(watch.ElapsedMilliseconds<budget){await Task.Delay(250,token);if(browserFailure!=null){result.Detail=browserFailure;return result;}if(navigationError!=0){result.Access=ServiceAccess.Unavailable;result.Detail="Страница проигрывателя не загрузилась (код "+navigationError+")";return result;}
var data=latestSample;if(data==null)continue;last=data;if(instagram&&FrameProgress!=null)FrameProgress(Convert.ToInt32(data["frames"]),Convert.ToDouble(data["time"]));
          if(randomShort&&expectedVideo==null&&data.ContainsKey("shorts")){var links=data["shorts"] as object[];var choices=(links??new object[0]).Select(Convert.ToString).Where(h=>!triedShorts.Contains(h)).ToArray();if(choices.Length>0){string chosen=choices[new Random(Guid.NewGuid().GetHashCode()).Next(choices.Length)];triedShorts.Add(chosen);expectedVideo=chosen.Substring(8,11);result.Url="https://www.youtube.com"+chosen;latestSample=null;previousTime=-1;previousFrames=0;view.CoreWebView2.Navigate("https://www.youtube.com"+chosen);continue;}}
          if(pornhub&&!selectedPornVideo&&data.ContainsKey("next")&&!String.IsNullOrEmpty(Convert.ToString(data["next"]))&&!Convert.ToBoolean(data["ageGate"])&&!Convert.ToBoolean(data["ageConfirmed"])){Uri next;if(Uri.TryCreate(Convert.ToString(data["next"]),UriKind.Absolute,out next)&&next.Scheme=="https"&&PornHost(next.Host)&&next.UserInfo.Length==0&&next.Port==443&&next.AbsolutePath=="/view_video.php"){latestSample=null;selectedPornVideo=true;previousTime=-1;previousFrames=0;view.CoreWebView2.Navigate(next.AbsoluteUri);continue;}}
          if(pornhub&&Convert.ToBoolean(data["identityGate"])){result.Detail="Для воспроизведения сайт требует вход или подтверждение личности (например, VK ID). Это не подтверждает блокировку сети; автоматический тест не выполняет вход в аккаунт.";return result;}if(Convert.ToBoolean(data["blocked"])){result.Detail="Сайт требует ручного подтверждения. Автоматический видеотест не подтверждён";return result;}
          if(previousTime>=0&&(pornhub?PornPlayed(data,previousTime,previousFrames):PlayedFor(data,previousTime,previousFrames,expectedVideo))){result.Access=ServiceAccess.Available;result.Detail="Видео действительно воспроизводится: время и декодированные кадры растут. "+(mediaResponse?"Получен ответ видеосервера. ":"Воспроизведение подтверждено кадрами, даже без сетевого уведомления браузера. ")+"Новая браузерная сессия, TCP, без кэша. Проверка одного ролика, не всех качеств.";return result;}
          if(Convert.ToDouble(data["time"])>0&&!Convert.ToBoolean(data["ad"])&&previousTime<0){previousTime=Convert.ToDouble(data["time"]);previousFrames=Convert.ToInt32(data["frames"]);if(Convert.ToInt32(data["width"])>0&&previousFrames>0&&Convert.ToString(data["id"])==(pornhub?"pornhub":expectedVideo))budget=Math.Min(pornhub?15500:11500,Math.Max(budget,(int)watch.ElapsedMilliseconds+3500));}
          if(!pornhub&&data.ContainsKey("playerError")&&!String.IsNullOrWhiteSpace(Convert.ToString(data["playerError"]))){if(randomShort&&triedShorts.Count<3){expectedVideo=null;latestSample=null;previousTime=-1;previousFrames=0;view.CoreWebView2.Navigate(VideoProbe.ShortsTarget);continue;}result.Access=randomShort?ServiceAccess.Unknown:ServiceAccess.Unavailable;result.Detail="Проигрыватель сообщает: "+data["playerError"];return result;}if(Convert.ToInt32(data["error"])!=0){result.Access=ServiceAccess.Unavailable;result.Detail="Проигрыватель не загрузил видео (код "+data["error"]+")";return result;}
        }if(!navigationLoaded&&(last==null||last.ContainsKey("ready")&&Convert.ToString(last["ready"])=="loading"&&Convert.ToInt32(last["links"])==0)){result.Access=ServiceAccess.Unavailable;result.Detail="Страница проигрывателя не загрузилась за "+(budget/1000)+" с; воспроизведение не началось. Это ошибка загрузки в этом тесте, а не доказательство, что сервис не работает в вашем браузере.";return result;}result.Detail="Воспроизведение не подтверждено за "+(budget/1000)+" с · поток: "+(mediaResponse?"получен":"не получен")+(last==null?" · проигрыватель не ответил":" · кадры: "+last["frames"]+" · время видео: "+last["time"]+" · ширина: "+last["width"])+(pornhub&&last!=null?" · страница: "+last["page"]+" · ролик выбран: "+selectedPornVideo+" · документ: "+last["ready"]+" · ссылки: "+last["links"]+" · возрастное окно: "+(Convert.ToBoolean(last["ageGate"])?"нужно ручное подтверждение ("+last["ageButtons"]+")":"не мешает"):"")+(randomShort&&last!=null?" · id: "+last["id"]+" · ожидаемый: "+expectedVideo:"")+". Страница сама по себе не считается успехом";return result;
      }catch(TimeoutException){result.Detail="Истекло время видеотеста · поток: "+(mediaResponse?"получен":"не получен")+(last==null?" · проигрыватель не ответил":" · кадры: "+last["frames"]+" · время: "+last["time"]+" · ширина: "+last["width"])+". Воспроизведение не подтверждено";return result;}finally{result.Milliseconds=(int)watch.ElapsedMilliseconds;try{awaitStop();}catch{}}
    }
    void awaitStop(){if(view!=null&&view.CoreWebView2!=null)view.CoreWebView2.Navigate("about:blank");}
    [MethodImpl(MethodImplOptions.NoInlining)]internal async Task<ZapretEndpointResult> Run(CancellationToken token){
      await gate.WaitAsync(token);try{if(disposed)throw new ObjectDisposedException("BrowserVideoProbe");Start();var deadline=Task.Delay(10000,token);if(await Task.WhenAny(ready.Task,deadline)!=ready.Task){token.ThrowIfCancellationRequested();return new ZapretEndpointResult{Url=target,Access=ServiceAccess.Unknown,Detail="Браузерная среда видеотеста не запустилась за 10 секунд"};}if(!await ready.Task)return new ZapretEndpointResult{Url=VideoProbe.Target,Access=ServiceAccess.Unknown,Detail="Среда видеотеста не запустилась: "+(initializationFailure??"нужна Microsoft Edge WebView2")};
        var completion=new TaskCompletionSource<ZapretEndpointResult>();host.BeginInvoke(new Action(async()=>{try{completion.TrySetResult(await Check(token));}catch(OperationCanceledException){completion.TrySetCanceled();}catch(Exception ex){completion.TrySetResult(new ZapretEndpointResult{Url=VideoProbe.Target,Access=ServiceAccess.Unknown,Detail="Не удалось завершить браузерный видеотест: "+ex.GetType().Name});}}));return await Within(completion.Task,pornhub?17000:13000,token);
      }catch(TimeoutException){return new ZapretEndpointResult{Url=target,Access=ServiceAccess.Unknown,Detail="Видеотест превысил лимит времени. Остальные сервисы продолжают проверяться"};}finally{gate.Release();}
    }
    void CleanProfile(){try{string sessions=Path.GetFullPath(Path.Combine(VideoBrowserLibraries.libraryRoot,"sessions"))+Path.DirectorySeparatorChar;string owned=Path.GetFullPath(profile);Guid id;if(owned.StartsWith(sessions,StringComparison.OrdinalIgnoreCase)&&Guid.TryParseExact(Path.GetFileName(owned),"N",out id)&&Directory.Exists(owned))Directory.Delete(owned,true);}catch{}}
    public void Dispose(){disposed=true;try{if(host!=null&&!host.IsDisposed)host.BeginInvoke(new Action(()=>host.Close()));}catch{} // Own session only; no user's browser processes are killed.
    }
  }
}
