using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using System.Threading.Tasks;
namespace SplifyWin {
 public sealed partial class MainForm {
  Task<ZapretCheckRow> ShowDiscordVoiceResults(ZapretCheckReport report,List<Dictionary<string,object>> results,bool draft=false){
   var done=new TaskCompletionSource<ZapretCheckRow>();
   var veil=new GlassBackdrop(blueDashboard){Dock=DockStyle.Fill};var popup=new GlassPopupPanel{Size=new Size(Math.Min(1040,ClientSize.Width-40),Math.Min(590,ClientSize.Height-40))};veil.Controls.Add(popup);Action layout=()=>popup.Location=new Point((veil.Width-popup.Width)/2,(veil.Height-popup.Height)/2);veil.Resize+=(s,e)=>layout();
   Add(popup,L("Discord · результаты голоса",18,true),24,20);
   var hint=L("Голос — ваша отметка. Двусторонний UDP — наблюдение за новыми портами Discord, не доказательство слышимости.",10,false,Muted);hint.AutoSize=false;hint.SetBounds(24,70,popup.Width-48,48);popup.Controls.Add(hint);
   var grid=Grid();grid.Name="discordVoiceResults";grid.SetBounds(24,126,popup.Width-48,popup.Height-216);foreach(string name in new[]{"Стратегия","Голос","UDP","Отправлено / получено"})grid.Columns.Add(name,name);grid.Columns[0].FillWeight=170;popup.Controls.Add(grid);
   var ordered=results.OrderByDescending(r=>Convert.ToString(r["Result"])=="user-confirmed").ThenBy(r=>r.ContainsKey("PingQuality")&&Convert.ToString(r["PingQuality"])=="low"?0:1).ThenByDescending(r=>r.ContainsKey("UdpIncoming")&&Convert.ToInt64(r["UdpIncoming"])>0&&Convert.ToInt64(r["UdpOutgoing"])>0).ThenBy(r=>{var row=report.Rows.FirstOrDefault(v=>v.StrategyId==Convert.ToString(r["StrategyId"]));var service=row==null?null:row.Services.FirstOrDefault(v=>v.Id=="discord");return service==null||service.Milliseconds<=0?Int32.MaxValue:service.Milliseconds;}).ToArray();
   foreach(var r in ordered){bool incoming=r.ContainsKey("UdpIncoming")&&Convert.ToInt64(r["UdpIncoming"])>0,outgoing=r.ContainsKey("UdpOutgoing")&&Convert.ToInt64(r["UdpOutgoing"])>0;string result=Convert.ToString(r["Result"]);int i=grid.Rows.Add(r.ContainsKey("Name")?r["Name"]:r["StrategyId"],result=="user-confirmed"?(r.ContainsKey("PingQuality")&&Convert.ToString(r["PingQuality"])=="low"?"Подключился · низкий пинг":r.ContainsKey("PingQuality")&&Convert.ToString(r["PingQuality"])=="high"?"Подключился · высокий пинг":"Подключился · пинг не отмечен"):result=="user-unavailable"?"Не удалось":"Не проверено",incoming&&outgoing?"В обе стороны":"Не подтверждён",r.ContainsKey("UdpIncoming")?r["UdpOutgoing"]+" / "+r["UdpIncoming"]:"—");grid.Rows[i].Tag=r;grid.Rows[i].Cells[1].ToolTipText=r.ContainsKey("Detail")?Convert.ToString(r["Detail"]):"Отметка пользователя";grid.Rows[i].Cells[1].Style.ForeColor=result=="user-confirmed"?(r.ContainsKey("PingQuality")&&Convert.ToString(r["PingQuality"])=="high"?Color.FromArgb(255,220,110):GlassInk.Mint):result=="user-unavailable"?Red:Muted;grid.Rows[i].Cells[1].Style.SelectionForeColor=grid.Rows[i].Cells[1].Style.ForeColor;grid.Rows[i].Cells[2].ToolTipText=r.ContainsKey("UdpDetail")?Convert.ToString(r["UdpDetail"]):"Наблюдение недоступно";}
   var apply=B("Создать выход Discord",async(s,e)=>{if(grid.CurrentRow==null)return;var r=grid.CurrentRow.Tag as Dictionary<string,object>;if(r==null||Convert.ToString(r["Result"])!="user-confirmed"){Toast("Выберите стратегию с отметкой «Удалось»");return;}var row=report.Rows.FirstOrDefault(v=>v.StrategyId==Convert.ToString(r["StrategyId"]));if(draft){done.TrySetResult(row);veil.Dispose();return;}var button=(Button)s;button.Enabled=false;try{if(await AssignCheckedProfile(report,row,"Discord"))Toast(zapretResultsNotice);}catch(Exception ex){GlassNotice.Show(this,ex.Message,"Профиль Discord");}finally{if(!button.IsDisposed)button.Enabled=true;}},true);apply.Text=draft?"Использовать для Discord":"Создать выход Discord";apply.Name="discordVoiceApply";apply.SetBounds(24,popup.Height-62,280,40);popup.Controls.Add(apply);var close=B("Закрыть",(s,e)=>veil.Dispose());close.SetBounds(popup.Width-180,popup.Height-62,156,40);popup.Controls.Add(close);Controls.Add(veil);veil.BringToFront();layout();veil.Disposed+=(s,e)=>done.TrySetResult(null);return done.Task;
  }
 }
}
