using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows.Forms;
namespace SplifyWin {
 public sealed class MalwHostsService {public string Name;public List<string> Entries=new List<string>();}
 public static class MalwHosts {
  const string Begin="# MCRF MALW BEGIN",End="# MCRF MALW END";
  static bool Dedicated(string domain){return HostsCandidates.AllowedDomain("instagram",domain)||HostsCandidates.AllowedDomain("chatgpt",domain);}
  public static List<MalwHostsService> Catalog(string text){
   if(text==null||text.Length>10*1024*1024)throw new FormatException("Некорректный размер списка ImMALWARE.");var result=new List<MalwHostsService>();string section=null;
   foreach(string raw in text.Split('\n')){var line=raw.Trim();if(line.StartsWith("#")){string title=line.TrimStart('#').Trim();if(title.IndexOf("Блокировка",StringComparison.OrdinalIgnoreCase)>=0)break;if(!String.IsNullOrEmpty(title)&&!title.Contains("hosts file")&&!title.StartsWith("Последнее обновление"))section=title;continue;}var fields=line.Split('#')[0].Split(new[]{' ','\t','\r'},StringSplitOptions.RemoveEmptyEntries);if(fields.Length<2)continue;if(!HostsCandidates.PublicV4(fields[0]))continue;foreach(var value in fields.Skip(1)){string domain=value.ToLowerInvariant();if(Dedicated(domain))continue;Validate(fields[0],domain);string name=section??domain;var group=result.FirstOrDefault(g=>g.Name==name);if(group==null){group=new MalwHostsService{Name=name};result.Add(group);}string entry=fields[0]+" "+domain;if(!group.Entries.Contains(entry))group.Entries.Add(entry);}}
   if(result.Count==0)throw new FormatException("В источнике нет доступных сервисов.");return result;
  }
  static void Validate(string ip,string domain){if(!HostsCandidates.PublicV4(ip)||!Regex.IsMatch(domain,@"^(?=.{1,253}$)[a-z0-9]+(?:[a-z0-9.-]*[a-z0-9])?$")||domain.Contains("..")||!domain.Contains(".")||Dedicated(domain))throw new FormatException("Некорректная запись или домен из отдельных блоков Instagram/ChatGPT: "+domain);}
  public static string ValidateEntries(string text){var entries=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(string raw in (text??"").Split('\n')){var fields=raw.Split('#')[0].Trim().Split(new[]{' ','\t','\r'},StringSplitOptions.RemoveEmptyEntries);if(fields.Length==0)continue;if(fields.Length<2)throw new FormatException("Формат hosts: IP домен.");foreach(string domain in fields.Skip(1)){string name=domain.ToLowerInvariant();Validate(fields[0],name);if(entries.ContainsKey(name)&&entries[name]!=fields[0])throw new FormatException("Разные IP для "+name);entries[name]=fields[0];}}if(entries.Count>1000)throw new FormatException("Слишком много записей.");return String.Join("\r\n",entries.Select(p=>p.Value+" "+p.Key));}
  static Match Block(string managed){var match=Regex.Match(managed,@"(?ms)^# MCRF MALW BEGIN\r*\n(.*?)^# MCRF MALW END\r*$" );if((managed.Contains(Begin)||managed.Contains(End))&&!match.Success||Regex.Matches(managed,Regex.Escape(Begin)).Count>1||Regex.Matches(managed,Regex.Escape(End)).Count>1)throw new IOException("Повреждён блок дополнительных сервисов hosts.");return match;}
  public static string Entries(byte[] original){var match=Block(HostsEditor.Managed(original));return match.Success?match.Groups[1].Value.Trim():"";}
  public static byte[] Compose(byte[] original,string text){string entries=ValidateEntries(text);string managed=HostsEditor.Managed(original);var match=Block(managed);if(match.Success)managed=managed.Remove(match.Index,match.Length);var domains=new HashSet<string>(entries.Split('\n').Where(l=>l.Contains(" ")).Select(l=>l.Trim().Split(' ')[1]),StringComparer.OrdinalIgnoreCase);string remaining=Encoding.UTF8.GetString(HostsRepair.Compose(original,managed));foreach(string raw in remaining.Split('\n')){var fields=raw.Split('#')[0].Trim().Split(new[]{' ','\t','\r'},StringSplitOptions.RemoveEmptyEntries);if(fields.Skip(1).Any(domains.Contains))throw new IOException("Домен уже внесён другим блоком hosts. Сначала уберите конфликтующую запись.");}return HostsRepair.Compose(original,managed.Trim()+ (entries.Length==0?"":"\r\n"+Begin+"\r\n"+entries+"\r\n"+End));}
 }
 public sealed class HostsTrial : IDisposable {
  readonly string root;readonly byte[] before,after;bool applied;
  public HostsTrial(string root,string service,List<HostsCandidate> hosts){this.root=root;before=HostsRepair.ReadHostsFile(HostsEditor.PathName);after=HostsEditor.Compose(before,HostsCandidates.Entries(hosts),service);HostsRepair.Apply(root,HostsEditor.Managed(after),before);applied=true;}
  public void Dispose(){if(!applied)return;HostsRepair.Apply(root,HostsEditor.Managed(before),after,false);applied=false;}
 }
 public static class HostsEditor {
  public static string PathName{get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"drivers","etc","hosts");}}
  public static string Managed(byte[] original){HostsRepair.Compose(original,null);var text=Encoding.UTF8.GetString(original);var match=Regex.Match(text,@"(?ms)^# MCRF META BEGIN\r?\n(.*?)^# MCRF META END");return match.Success?match.Groups[1].Value:"";}
  public static List<HostsCandidate> Parse(string text,string service){if(String.IsNullOrWhiteSpace(text))return new List<HostsCandidate>();return HostsCandidates.ParseLines(text,service,"Ручной редактор",true);}
  public static void UpdateProfileEntries(IEnumerable<ZapretProfile> profiles,string service,string text,bool replacedOwner){var entries=Parse(text,service);foreach(var profile in profiles){bool had=(profile.Settings.Hosts??new List<HostsCandidate>()).Any(h=>h.Service==service);if(!had&&!replacedOwner)continue;profile.Settings.Hosts=(profile.Settings.Hosts??new List<HostsCandidate>()).Where(h=>h.Service!=service).ToList();if(had&&!replacedOwner)profile.Settings.Hosts.AddRange(entries);}}
  public static string ServiceEntries(byte[] original,string service){string managed=Managed(original);var lines=managed.Split('\n').Select(l=>{var fields=l.Split('#')[0].Trim().Split(new[]{' ','\t','\r'},StringSplitOptions.RemoveEmptyEntries);return fields.Length<2?"":fields[0]+" "+String.Join(" ",fields.Skip(1).Where(d=>HostsCandidates.AllowedDomain(service,d.ToLowerInvariant())));}).Where(l=>l.Trim().Contains(" ")).ToArray();return lines.Length==0?"":HostsCandidates.Entries(Parse(String.Join("\n",lines),service));}
  static string RetainOtherService(string line,string service){
   int commentAt=line.IndexOf('#');string comment=commentAt<0?"":line.Substring(commentAt);string record=commentAt<0?line:line.Substring(0,commentAt);
   var words=record.Trim().Split(new[]{' ','\t','\r'},StringSplitOptions.RemoveEmptyEntries);
   if(words.Length<2||!words.Skip(1).Any(d=>HostsCandidates.AllowedDomain(service,d.ToLowerInvariant())))return line;
   var remaining=words.Skip(1).Where(d=>!HostsCandidates.AllowedDomain(service,d.ToLowerInvariant())).ToArray();
   return remaining.Length==0?comment:words[0]+" "+String.Join(" ",remaining)+(comment.Length==0?"":" "+comment);
  }
  public static byte[] Compose(byte[] original,string text,string service){
   var selected=Parse(text,service);string entries=HostsCandidates.Entries(selected);
   var other=Managed(original).Split('\n').Select(l=>RetainOtherService(l,service));
   string outside=Encoding.UTF8.GetString(HostsRepair.Compose(original,null));
   foreach(var item in selected)if(Regex.IsMatch(outside,@"(?im)^\s*[^#\r\n]+\s"+Regex.Escape(item.Domain)+@"(?:\s|$)"))throw new InvalidOperationException("Вне блока MCRF уже есть запись "+item.Domain+". Она не будет перезаписана.");
   return HostsRepair.Compose(original,String.Join("\r\n",other.Where(l=>!String.IsNullOrWhiteSpace(l)))+"\r\n"+entries);
  }
 }
 public sealed partial class MainForm {
  void HostsBlue(){
   var box=Box();box.Dock=DockStyle.Fill;content.Controls.Add(box);
   var intro=L("Подберите hosts вместе с Zapret и подтвердите работу сервиса. Внизу применяются оба блока; записи других программ сохраняются. ChatGPT может использовать стороннее SNI-реле. TLS не отключается.",10,false,Muted);intro.AutoSize=false;intro.SetBounds(22,14,box.Width-44,65);box.Controls.Add(intro);
   var ids=new[]{"instagram","chatgpt"};var cards=new Control[3];var editors=new TextBoxBase[3];var statuses=new Label[3];var sources=new GlassPicker[3];var plans=new SetupAssignment[2];var reports=new ZapretCheckReport[2];var confirmedText=new string[2];bool busy=false;CancellationTokenSource cancellation=null;
   var sourceUrls=new[]{HostsRepair.Source,HostsCandidates.MalwSource,HostsCandidates.GeoHideSource};
   Action<bool> setBusy=value=>{busy=value;foreach(var source in sources)if(source!=null)source.Enabled=!value;foreach(var editor in editors)if(editor!=null)editor.ReadOnly=value;};
   for(int index=0;index<2;index++){
    int n=index;string id=ids[n];int half=(box.Width-58)/2;var card=new GlassFieldPanel{Name="hostsBlock_"+id,Location=new Point(22+n*(half+14),90),Size=new Size(half,Math.Max(240,box.Height-166)),Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left};box.Controls.Add(card);cards[n]=card;
    Add(card,L(n==0?"Instagram":"ChatGPT",16,true),16,12);
    var source=new GlassPicker{Name="hostsPreset_"+id,FlatSurface=true,Location=new Point(16,52),Width=card.Width-32};source.SetItems(HostsCandidates.SourceNames(id));source.SelectedIndex=0;card.Controls.Add(source);sources[n]=source;
    var editor=new GlassLogBox{PlainTextOnly=true,DetectUrls=false,Name="hostsEntries_"+id,Multiline=true,ScrollBars=RichTextBoxScrollBars.None,WordWrap=false,BorderStyle=BorderStyle.None,BackColor=GlassFieldPanel.InputColor,ForeColor=Ink,Font=new Font("Consolas",10),Location=new Point(16,154),Size=new Size(card.Width-32,Math.Max(40,card.Height-233)),Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right};editors[n]=editor;var entryHost=new GlassFieldPanel{Name="hostsTextSurface_"+id};card.Controls.Add(entryHost);entryHost.Controls.Add(editor);editor.InstallRails(entryHost);
    var status=L("Ещё не проверено",10,false,Color.FromArgb(255,220,110));status.Name="hostsStatus_"+id;status.AutoSize=false;status.SetBounds(16,card.Height-70,card.Width-32,62);status.Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;card.Controls.Add(status);statuses[n]=status;
    try{editor.Text=HostsEditor.ServiceEntries(File.ReadAllBytes(HostsEditor.PathName),id);}catch(Exception ex){status.Text=ex.Message;}
    editor.TextChanged+=(s,e)=>{if(confirmedText[n]!=editor.Text){plans[n]=null;status.ForeColor=Color.FromArgb(255,220,110);status.Text="Записи изменены / не проверены";}};
    source.SelectedIndexChanged+=(s,e)=>{plans[n]=null;confirmedText[n]=null;status.ForeColor=Color.FromArgb(255,220,110);status.Text="Источник изменён. Подберите и проверьте комбинацию заново.";};
    var choose=B("Проверить",async(s,e)=>{
     if(busy||setupCancellation!=null||zapretCancellation!=null||discordVoiceChecking||connecting||warpCancellation!=null){Toast("Дождитесь завершения текущей операции");return;}setBusy(true);cancellation=new CancellationTokenSource();((Control)s).Enabled=false;
     try{
      zapret.Prepare();var original=StrategyReport();var json=new System.Web.Script.Serialization.JavaScriptSerializer{MaxJsonLength=Int32.MaxValue};var report=original==null?new ZapretCheckReport{Settings=new ZapretSettings(),Complete=true}:json.Deserialize<ZapretCheckReport>(json.Serialize(original));
      if(report.Rows.All(r=>String.IsNullOrEmpty(r.StrategyId)))foreach(var strategy in ZapretCatalog.Load(zapret.DirectoryPath).Where(x=>x.Available).OrderByDescending(x=>x.Id=="flowseal:general (ALT4).bat").Take(3))report.Rows.Add(new ZapretCheckRow{StrategyId=strategy.Id,Family=strategy.Family,Name=strategy.Name});
      var service=ZapretChecks.Services.First(x=>x.Id==id);var existing=ServicePresetRoutes.Existing(state,id);var profile=existing==null?null:state.ZapretProfiles.FirstOrDefault(p=>p.Id==existing.ZapretProfileId);var assignment=new SetupAssignment{ServiceId=id,Output="warp",Strategy=profile==null?null:report.Rows.FirstOrDefault(r=>r.StrategyId==profile.Settings.Strategy)};
      string url=sourceUrls[source.SelectedIndex==1?2:n];bool worked=await CheckSetupHosts(report,service,assignment,cancellation.Token,message=>{if(!status.IsDisposed)status.Text=message;},url,false,false);
      cancellation.Token.ThrowIfCancellationRequested();if(box.IsDisposed)return;if(worked){reports[n]=report;confirmedText[n]=HostsCandidates.Entries(assignment.Hosts);editor.Text=confirmedText[n];plans[n]=assignment;status.ForeColor=GlassInk.Mint;status.Text="Работа подтверждена · "+assignment.Strategy.Name+". Нажмите «Применить».";}else{plans[n]=null;status.ForeColor=Color.FromArgb(255,130,150);status.Text="Не подтверждено. Текущие записи не изменены.";}
     }catch(OperationCanceledException){if(!status.IsDisposed)status.Text="Подбор отменён.";}catch(Exception ex){WriteLog("Подбор hosts "+id+": "+ex.ToString());if(!status.IsDisposed){status.ForeColor=Color.FromArgb(255,220,110);status.Text="Подбор не завершён: "+ex.Message;}}
     finally{cancellation.Dispose();cancellation=null;setBusy(false);if(!((Control)s).IsDisposed)((Control)s).Enabled=true;}
    },true);choose.Name="hostsPick_"+id;choose.SetBounds(16,106,150,36);card.Controls.Add(choose);
   }
   var extra=new GlassFieldPanel{Name="hostsBlock_malw"};cards[2]=extra;box.Controls.Add(extra);Add(extra,L("Другие сервисы",15,true),16,12);var malwPicker=new GlassPicker{Name="hostsMalwServices",FlatSurface=true,MultiSelect=true,EmptySelectionText="Выберите сервисы",Location=new Point(16,52)};sources[2]=malwPicker;extra.Controls.Add(malwPicker);var malwEditor=new GlassLogBox{PlainTextOnly=true,DetectUrls=false,Name="hostsEntries_malw",Multiline=true,ScrollBars=RichTextBoxScrollBars.None,WordWrap=false,BorderStyle=BorderStyle.None,BackColor=GlassFieldPanel.InputColor,ForeColor=Ink,Font=new Font("Consolas",10)};editors[2]=malwEditor;var extraTextHost=new GlassFieldPanel{Name="hostsTextSurface_malw"};extra.Controls.Add(extraTextHost);extraTextHost.Controls.Add(malwEditor);malwEditor.InstallRails(extraTextHost);var malwStatus=L("ImMALWARE · ещё не проверено",10,false,Color.FromArgb(255,220,110));malwStatus.AutoSize=false;statuses[2]=malwStatus;extra.Controls.Add(malwStatus);try{malwEditor.Text=MalwHosts.Entries(File.ReadAllBytes(HostsEditor.PathName));}catch(Exception ex){malwStatus.Text=ex.Message;}var malwGroups=new List<MalwHostsService>();bool loadingMalw=false,malwSelectionValid=true;malwEditor.TextChanged+=(s,e)=>malwSelectionValid=true;
   malwPicker.CheckedItemsChanged+=(s,e)=>{if(loadingMalw)return;try{malwEditor.Text=MalwHosts.ValidateEntries(String.Join("\n",malwPicker.SelectedIndices.SelectMany(i=>malwGroups[i].Entries)));malwStatus.Text="Источник ImMALWARE. Работу сервисов проверьте после применения.";malwSelectionValid=true;}catch(Exception ex){malwSelectionValid=false;malwStatus.Text=ex.Message;}};
   Func<System.Threading.Tasks.Task> loadMalw=async()=>{try{string text=await core.DownloadTextAsync(HostsCandidates.MalwSource);if(box.IsDisposed)return;var groups=MalwHosts.Catalog(text);loadingMalw=true;malwGroups=groups;malwPicker.SetItems(groups.Select(g=>g.Name));var saved=new HashSet<string>(malwEditor.Text.Split('\n').Select(l=>l.Trim()),StringComparer.OrdinalIgnoreCase);for(int i=0;i<groups.Count;i++)malwPicker.SetChecked(i,groups[i].Entries.Any(saved.Contains));loadingMalw=false;malwStatus.Text="Выберите сервисы. Instagram и ChatGPT остаются в отдельных блоках. Реле стороннее; TLS не отключаем.";}catch(Exception ex){if(!malwStatus.IsDisposed)malwStatus.Text="Не загружено: "+ex.Message;}finally{loadingMalw=false;}};var fetchMalw=B("Обновить с GitHub",async(s,e)=>{if(busy)return;setBusy(true);((Control)s).Enabled=false;try{await PresetStorage.Update(core.DataRoot,new[]{HostsCandidates.MalwSource},core.DownloadRemoteTextAsync);await loadMalw();}catch(Exception ex){if(!malwStatus.IsDisposed)malwStatus.Text="Не обновлено; локальный список сохранён: "+ex.Message;}finally{setBusy(false);if(!((Control)s).IsDisposed)((Control)s).Enabled=true;}});fetchMalw.Name="hostsMalwLoad";fetchMalw.SetBounds(16,106,180,36);extra.Controls.Add(fetchMalw);bool loadedMalw=false;Action beginMalw=async()=>{if(loadedMalw||box.IsDisposed)return;loadedMalw=true;await loadMalw();};box.HandleCreated+=(s,e)=>beginMalw();if(box.IsHandleCreated)beginMalw();
   intro.Text="Подберите Instagram и ChatGPT вместе с Zapret. Другие сервисы — из ImMALWARE. Применяются три блока; чужие записи сохраняются. Сторонние реле не гарантируют работу. TLS не отключается.";
   Action layoutBlocks=()=>{intro.Width=box.Width-44;int half=(box.Width-72)/3;for(int n=0;n<3;n++){cards[n].SetBounds(22+n*(half+14),90,half,Math.Max(240,box.Height-166));sources[n].Width=half-32;editors[n].Parent.SetBounds(8,140,half-16,Math.Max(40,cards[n].Height-219));statuses[n].SetBounds(16,cards[n].Height-70,half-32,62);}};box.Resize+=(s,e)=>layoutBlocks();layoutBlocks();
   var apply=B("Применить",async(s,e)=>{
    if(busy||setupCancellation!=null||zapretCancellation!=null||discordVoiceChecking)return;
    byte[] before=null,after=null;bool written=false,touched=false,running=zapret.Running;var json=new System.Web.Script.Serialization.JavaScriptSerializer{MaxJsonLength=Int32.MaxValue};string backup=json.Serialize(state);System.Threading.Tasks.Task rollback=null;Exception applyFailure=null;
    try{
     if(!IsAdministrator())throw new InvalidOperationException("Для изменения hosts запустите программу от администратора.");if(!malwSelectionValid)throw new FormatException("Исправьте конфликтующие записи дополнительных сервисов.");setBusy(true);before=await System.Threading.Tasks.Task.Run(()=>HostsRepair.ReadHostsFile(HostsEditor.PathName));after=before;for(int n=0;n<2;n++)after=HostsEditor.Compose(after,editors[n].Text,ids[n]);after=MalwHosts.Compose(after,editors[2].Text);
     if(!await ConfirmChange("Применить показанные записи всех трёх блоков hosts? Другие записи сохранятся; будет создан бэкап. Для подтверждённых комбинаций сохраним выбранный профиль Zapret.","Применить hosts"))return;setBusy(true);
     var staged=new List<RouteList>();var newProfiles=new List<ZapretProfile>();
     for(int n=0;n<2;n++)if(plans[n]!=null&&confirmedText[n]==editors[n].Text){var service=ZapretChecks.Services.First(x=>x.Id==ids[n]);var p=new ZapretProfile{Name=service.Name+" · hosts",Enabled=true,Settings=ManualServiceChecks.AppliedSettings(reports[n],ids[n],plans[n].Strategy.StrategyId)};p.Settings.Strategy=plans[n].Strategy.StrategyId;p.Settings.Family=plans[n].Strategy.Family;p.Settings.Hosts=plans[n].Hosts;var route=ServicePresetRoutes.Existing(state,ids[n]);if(route==null)route=await ServicePresetRoutes.Create(service,"zapret",p.Id,core.DownloadTextAsync);else route=json.Deserialize<RouteList>(json.Serialize(route));route.Target="zapret";route.ZapretProfileId=p.Id;route.Enabled=true;route.BuiltinPreset="service-constructor:"+ids[n];staged.Add(route);newProfiles.Add(p);}
     if(box.IsDisposed)throw new OperationCanceledException();touched=true;if(running)zapret.Stop();await HostsRepair.ApplyAsync(store.Root,HostsEditor.Managed(after),before);written=!before.SequenceEqual(after);
     foreach(var route in staged){var id=route.BuiltinPreset.Substring("service-constructor:".Length);var old=ServicePresetRoutes.Existing(state,id);if(old!=null){route.Id=old.Id;state.Lists.Remove(old);}state.Lists.Insert(0,route);}state.ZapretProfiles.AddRange(newProfiles);
     for(int n=0;n<2;n++)HostsEditor.UpdateProfileEntries(state.ZapretProfiles.Except(newProfiles),ids[n],editors[n].Text,plans[n]!=null);
     if(running||newProfiles.Count>0)await StartSavedZapretProfiles(CancellationToken.None);store.Save(state);Toast("hosts и подтверждённые комбинации сохранены");blueDashboard.Invalidate();
}catch(Exception ex){if(touched){zapret.Stop();state=json.Deserialize<ClientState>(backup);}if(written)rollback=System.Threading.Tasks.Task.Run(()=>HostsRepair.Apply(store.Root,HostsEditor.Managed(before),after,false));applyFailure=ex;}
    finally{if(rollback==null)setBusy(false);}
    if(rollback!=null)try{await rollback;}catch(Exception restore){WriteLog("Откат hosts: "+restore.ToString());}finally{setBusy(false);}
    if(applyFailure!=null){if(running&&touched)WriteLog("Профили восстановлены; включите Zapret снова.");GlassNotice.Show(this,applyFailure.Message,"Не применено");}
   },true);apply.Name="hostsApplyBoth";apply.SetBounds(22,box.Height-52,220,38);apply.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(apply);
   var remove=B("Убрать записи",async(s,e)=>{if(busy||setupCancellation!=null||zapretCancellation!=null||discordVoiceChecking||connecting||warpCancellation!=null)return;byte[] before=null,after=null;bool written=false;var json=new System.Web.Script.Serialization.JavaScriptSerializer{MaxJsonLength=Int32.MaxValue};string backup=json.Serialize(state);System.Threading.Tasks.Task rollbackTask=null;Exception removeFailure=null;try{if(!IsAdministrator())throw new InvalidOperationException("Для изменения hosts запустите программу от администратора.");if(!await ConfirmChange("Убрать записи Instagram и ChatGPT и дополнительные сервисы из блока MCRF и из профилей? Другие записи hosts сохранятся.","Убрать записи"))return;setBusy(true);before=await System.Threading.Tasks.Task.Run(()=>HostsRepair.ReadHostsFile(HostsEditor.PathName));after=before;foreach(var id in ids)after=HostsEditor.Compose(after,"",id);after=MalwHosts.Compose(after,"");await HostsRepair.ApplyAsync(store.Root,HostsEditor.Managed(after),before);written=!before.SequenceEqual(after);foreach(var p in state.ZapretProfiles)p.Settings.Hosts=(p.Settings.Hosts??new List<HostsCandidate>()).Where(h=>!ids.Contains(h.Service)).ToList();store.Save(state);for(int n=0;n<2;n++){plans[n]=null;confirmedText[n]=null;editors[n].Clear();statuses[n].Text="Записи удалены";statuses[n].ForeColor=Color.FromArgb(255,220,110);}loadingMalw=true;foreach(int selected in malwPicker.SelectedIndices.ToArray())malwPicker.SetChecked(selected,false);loadingMalw=false;editors[2].Clear();statuses[2].Text="Записи удалены";}catch(Exception ex){state=json.Deserialize<ClientState>(backup);if(written)rollbackTask=System.Threading.Tasks.Task.Run(()=>HostsRepair.Apply(store.Root,HostsEditor.Managed(before),after,false));WriteLog("Удаление hosts: "+ex.ToString());removeFailure=ex;}finally{if(rollbackTask==null)setBusy(false);}if(rollbackTask!=null)try{await rollbackTask;}catch(Exception restore){WriteLog("Откат удаления hosts: "+restore.ToString());}finally{setBusy(false);}if(removeFailure!=null)GlassNotice.Show(this,removeFailure.Message,"hosts");});remove.Name="hostsRemoveBoth";remove.SetBounds(258,box.Height-52,220,38);remove.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(remove);
   box.Disposed+=(s,e)=>{if(cancellation!=null)cancellation.Cancel();};
  }
  void HostsBlueOld(){
   var box=Box();box.Dock=DockStyle.Fill;content.Controls.Add(box);
   var description=L("hosts связывает домен с указанным IP. Это не VPN. Меняем только записи выбранного сервиса в блоке MCRF; остальные записи сохраняются. Перед изменением создаётся резервная копия.",11,false,Muted);description.AutoSize=false;description.SetBounds(22,16,box.Width-44,62);box.Controls.Add(description);
   var services=new GlassPicker{Name="hostsService",Location=new Point(22,88),Width=260};services.SetItems(new[]{"Instagram / Facebook","ChatGPT","Rutor"});box.Controls.Add(services);string[] ids={"instagram","chatgpt","rutor"};
   var source=new GlassPicker{Name="hostsSourcePicker",Location=new Point(300,88),Width=Math.Max(240,box.Width-322)};source.SetItems(new[]{"Zapret-Manager","dns.malw.link","GeoHideDNS"});source.SelectedIndex=0;box.Controls.Add(source);
   var warning=L("",10,false,Color.FromArgb(255,220,110));warning.AutoSize=false;warning.SetBounds(22,142,box.Width-44,55);box.Controls.Add(warning);
   var editor=new TextBox{Name="hostsEditableEntries",Multiline=true,ScrollBars=ScrollBars.Both,WordWrap=false,BorderStyle=BorderStyle.FixedSingle,BackColor=GlassFieldPanel.InputColor,ForeColor=Ink,Font=Font};editor.SetBounds(22,203,box.Width-44,Math.Max(90,box.Height-365));editor.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(editor);
   var status=L("Формат: IP домен, одна запись на строке.",10,false,Muted);status.AutoSize=false;status.SetBounds(22,box.Height-155,box.Width-44,60);status.Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(status);
   bool busy=false;CancellationTokenSource cancellation=null;string id="instagram";
   Action load=()=>{if(busy)return;id=ids[Math.Max(0,services.SelectedIndex)];try{editor.Text=HostsEditor.ServiceEntries(File.ReadAllBytes(HostsEditor.PathName),id);}catch(Exception ex){status.Text=ex.Message;}
    warning.Text=id=="chatgpt"?"ChatGPT: в источниках встречаются сторонние SNI-реле. Это не IP OpenAI. Не отключаем TLS и не устанавливаем чужие сертификаты. Проверка HTTP не подтверждает вход и отправку сообщения.":"Альтернативный IP может помочь вместе с Zapret, но не гарантирует загрузку медиа. Проверьте изображения, видео и вход самостоятельно.";};
   services.SelectedIndexChanged+=(s,e)=>load();services.SelectedIndex=0;
   Action<bool> enabled=value=>{busy=!value;services.Enabled=source.Enabled=editor.Enabled=value;};
   var fetch=B("Подобрать IP",async(s,e)=>{if(busy)return;enabled(false);cancellation=new CancellationTokenSource();try{
    string url=source.SelectedIndex==0?HostsRepair.Source:source.SelectedIndex==1?HostsCandidates.MalwSource:"https://raw.githubusercontent.com/Internet-Helper/GeoHideDNS/main/hosts/hosts";status.Text="Загружаем источник…";var raw=await core.DownloadTextAsync(url);cancellation.Token.ThrowIfCancellationRequested();var candidates=source.SelectedIndex==0?HostsCandidates.ParseScript(raw,id):HostsCandidates.ParseLines(raw,id,url);
    status.Text="Проверяем TLS и HTTP всех адресов без изменения hosts…";var results=await HostsCandidates.ProbeAll(core,candidates,cancellation.Token,r=>{if(!status.IsDisposed)status.Text=r.Candidate.Domain+" → "+r.Candidate.Address+" · "+r.Detail;});
    var best=results.Where(r=>r.Usable).GroupBy(r=>r.Candidate.Domain).Select(g=>g.OrderBy(r=>r.Milliseconds).First().Candidate).ToArray();if(best.Length==0)throw new InvalidOperationException("Ни один адрес не подтвердил TLS/HTTP. Текущие записи не изменены.");
    if(!editor.IsDisposed)editor.Text=HostsCandidates.Entries(best);if(!status.IsDisposed)status.Text="Подобрано доменов: "+best.Length+". TLS/HTTP проверен дважды. Это ещё не подтверждение работы сервиса. Записи НЕ сохранены; их можно отредактировать.";
   }catch(OperationCanceledException){if(!status.IsDisposed)status.Text="Подбор отменён; hosts не изменён.";}catch(Exception ex){if(!status.IsDisposed)status.Text=ex.Message;}finally{cancellation.Dispose();cancellation=null;if(!box.IsDisposed)enabled(true);}});fetch.Name="hostsPick";fetch.SetBounds(22,box.Height-88,190,36);fetch.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(fetch);
   var check=B("Проверить записи",async(s,e)=>{if(busy)return;enabled(false);cancellation=new CancellationTokenSource();try{var entries=HostsEditor.Parse(editor.Text,id);HostsCandidates.Entries(entries);if(entries.Count==0)throw new InvalidOperationException("Введите записи.");var results=await HostsCandidates.ProbeAll(core,entries,cancellation.Token,null);status.Text=String.Join(" · ",results.Select(r=>r.Candidate.Domain+": "+(r.Usable?"TLS/HTTP доступен":"не подтверждён")));}catch(Exception ex){if(!status.IsDisposed)status.Text=ex.Message;}finally{cancellation.Dispose();cancellation=null;if(!box.IsDisposed)enabled(true);}});check.Name="hostsCheck";check.SetBounds(228,box.Height-88,210,36);check.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(check);
   var apply=B("Сохранить записи",async(s,e)=>{if(busy)return;try{var original=File.ReadAllBytes(HostsEditor.PathName);var next=HostsEditor.Compose(original,editor.Text,id);if(!IsAdministrator())throw new InvalidOperationException("Перезапустите MCRF с правами администратора. Ничего не изменено.");if(!await ConfirmChange("Сохранить показанные записи выбранного сервиса? Работу сайта необходимо проверить в браузере. Остальные записи сохранятся; резервная копия будет в hosts-backups.","Сохранить hosts","Изменение hosts"))return;enabled(false);await System.Threading.Tasks.Task.Run(()=>HostsRepair.Apply(store.Root,HostsEditor.Managed(next),original));status.Text="Сохранено. Перезапустите браузер и проверьте сервис.";}catch(Exception ex){if(!status.IsDisposed)status.Text=ex.Message;}finally{if(!box.IsDisposed)enabled(true);}},true);apply.Name="hostsSave";apply.SetBounds(22,box.Height-44,220,36);apply.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(apply);
   var remove=B("Убрать записи сервиса",async(s,e)=>{if(busy)return;try{if(!await ConfirmChange("Удалить только записи "+services.SelectedItem+" из блока MCRF? Другие записи сохранятся.","Убрать записи"))return;var original=File.ReadAllBytes(HostsEditor.PathName);var next=HostsEditor.Compose(original,"",id);enabled(false);await System.Threading.Tasks.Task.Run(()=>HostsRepair.Apply(store.Root,HostsEditor.Managed(next),original));status.Text="Записи сервиса удалены. Другие записи сохранены.";enabled(true);load();}catch(Exception ex){if(!status.IsDisposed)status.Text=ex.Message;}finally{if(!box.IsDisposed)enabled(true);}});remove.Name="hostsRemoveService";remove.SetBounds(260,box.Height-44,260,36);remove.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(remove);
   var stop=B("Отмена подбора",(s,e)=>{if(cancellation!=null)cancellation.Cancel();});stop.SetBounds(454,box.Height-88,210,36);stop.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(stop);box.Disposed+=(s,e)=>{if(cancellation!=null)cancellation.Cancel();};
  }
 }
}
