using System;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace SplifyWin {
  public sealed class UpdateListView : Control {
    public static UpdateItem[] SectionRows(UpdateItem[] rows){var names=new[]{"Программа","Движки","Дополнительный софт","Стратегии","Текущие выходы — их списки"};var result=new System.Collections.Generic.List<UpdateItem>();for(int n=0;n<names.Length;n++){var group=rows.Where(r=>Section(r)==n&&(r.Kind!="catalog"||!rows.Any(x=>x.Kind=="optional"))).ToArray();if(group.Length==0)continue;result.Add(new UpdateItem{Id="section:"+n,Kind="section",Name=names[n]});result.AddRange(group);}return result.ToArray();}
    static int Section(UpdateItem row){return row.Id=="app"?0:row.Kind=="list"?4:row.Id.EndsWith("-config")?3:row.Id=="telegram"||row.Id=="warp"||row.Id=="zapret"?2:1;}
    const int HeaderHeight=42,RowHeight=62;
    public UpdateItem[] Items=new UpdateItem[0];public int SelectedIndex=-1;int first,dragOffset=-1;public event Action SelectionChanged;readonly ToolTip tips=new ToolTip();readonly Font groupFont=new Font("Segoe UI",14,GraphicsUnit.Pixel);
    public UpdateListView(){Name="updateList";SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.ResizeRedraw,true);BackColor=Color.FromArgb(28,44,79);Font=new Font("Segoe UI",16,GraphicsUnit.Pixel);TabStop=true;Disposed+=(s,e)=>{tips.Dispose();groupFont.Dispose();Font.Dispose();};}
    public UpdateItem Selected{get{return SelectedIndex>=0&&SelectedIndex<Items.Length&&Items[SelectedIndex].Kind!="section"?Items[SelectedIndex]:null;}}
    public int VisibleRows{get{return Math.Max(1,(Height-HeaderHeight)/RowHeight);}}
    public int FirstVisibleRow{get{return first;}}
    public Rectangle[] Columns{get{int width=Math.Max(1,Width-16),name=(int)(width*.24),version=(int)(width*.145);return new[]{new Rectangle(14,0,name-14,HeaderHeight),new Rectangle(name,0,version,HeaderHeight),new Rectangle(name+version,0,version,HeaderHeight),new Rectangle(name+2*version+16,0,Math.Max(1,width-name-2*version-26),HeaderHeight)};}}
    Rectangle Track{get{return new Rectangle(Width-9,HeaderHeight+5,4,Math.Max(1,Height-HeaderHeight-10));}}
    Rectangle Thumb{get{var r=Track;int h=Math.Min(r.Height,Math.Max(25,r.Height*VisibleRows/Math.Max(1,Items.Length)));return new Rectangle(r.X,r.Y+(r.Height-h)*first/Math.Max(1,Items.Length-VisibleRows),r.Width,h);}}
    void ScrollTo(int row){first=Math.Max(0,Math.Min(Math.Max(0,Items.Length-VisibleRows),row));Invalidate();}
    protected override void OnResize(EventArgs e){base.OnResize(e);ScrollTo(first);var old=Region;if(Width>1&&Height>1)using(var p=UiShape.Round(ClientRectangle,13))Region=new Region(p);if(old!=null)old.Dispose();}
    public void Reload(UpdateItem[] items){string id=Selected==null?null:Selected.Id;items=SectionRows(items);Items=items;SelectedIndex=Array.FindIndex(items,x=>x.Id==id);if(SelectedIndex<0&&items.Length>0)SelectedIndex=Array.FindIndex(items,x=>x.Kind!="section");first=Math.Min(first,Math.Max(0,Items.Length-VisibleRows));Invalidate();if(SelectionChanged!=null)SelectionChanged();}
    static string Version(string value){if(String.IsNullOrEmpty(value))return "—";return value.Length==64?value.Substring(0,8):value.StartsWith("engines-")?value.Substring(7):value;}
    protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.Clear(BackColor);g.SmoothingMode=SmoothingMode.AntiAlias;var c=Columns;using(var b=new SolidBrush(Color.FromArgb(25,40,73)))g.FillRectangle(b,0,0,Width,HeaderHeight);string[] headers={"Компонент","Установлено","На GitHub","Состояние"};for(int k=0;k<4;k++)Draw(g,headers[k],c[k],GlassInk.Muted,false,k==1||k==2);
      for(int i=first;i<Math.Min(Items.Length,first+VisibleRows);i++){var row=Items[i];int y=HeaderHeight+(i-first)*RowHeight;if(row.Kind=="section"){Draw(g,row.Name,new Rectangle(16,y+8,Width-40,RowHeight-16),Color.FromArgb(194,83,113),false,false,groupFont);using(var line=new Pen(Color.FromArgb(55,78,109,152)))g.DrawLine(line,16,y+RowHeight-8,Width-24,y+RowHeight-8);continue;}using(var b=new SolidBrush(i==SelectedIndex?Color.FromArgb(45,65,108):i%2==0?Color.FromArgb(29,45,80):BackColor))g.FillRectangle(b,0,y,Width-14,RowHeight);if(i==SelectedIndex)using(var b=new SolidBrush(GlassInk.Cyan))g.FillRectangle(b,0,y+10,3,RowHeight-20);
        Draw(g,row.Name,new Rectangle(c[0].X,y+9,c[0].Width-8,25),GlassInk.White);Draw(g,row.Group,new Rectangle(c[0].X,y+33,c[0].Width-8,21),GlassInk.Muted,false,false,groupFont);
        for(int k=1;k<=2;k++)Draw(g,Version(k==1?row.Current:row.Version),new Rectangle(c[k].X,y+8,c[k].Width,RowHeight-16),k==2&&row.Available&&!row.Ignored?GlassInk.Cyan:GlassInk.Muted,false,true);
        string status=(row.Ignored?"Пропущено · ":"")+row.DisplayStatus;Color ink=row.Ignored?GlassInk.Muted:row.Available?GlassInk.Cyan:row.Status!=null&&row.Status.StartsWith("Не удалось")?Color.FromArgb(255,167,183):row.IsCurrent||row.Status!=null&&row.Status.StartsWith("Обновлено")?GlassInk.Mint:GlassInk.Muted;
        Draw(g,status,new Rectangle(c[3].X,y+7,c[3].Width,RowHeight-14),ink,true);
        using(var p=new Pen(Color.FromArgb(38,56,93)))g.DrawLine(p,14,y+RowHeight-1,Width-20,y+RowHeight-1);
      }
      if(Items.Length>VisibleRows){using(var b=new SolidBrush(Color.FromArgb(51,68,108)))g.FillRectangle(b,Track);using(var b=new SolidBrush(Color.FromArgb(135,157,207)))g.FillRectangle(b,Thumb);}}
    void Draw(Graphics g,string text,Rectangle r,Color color,bool wrap=false,bool center=false,Font font=null){var flags=TextFormatFlags.NoPrefix|TextFormatFlags.PreserveGraphicsClipping|TextFormatFlags.EndEllipsis|TextFormatFlags.VerticalCenter|(wrap?TextFormatFlags.WordBreak:TextFormatFlags.SingleLine)|(center?TextFormatFlags.HorizontalCenter:TextFormatFlags.Left);TextRenderer.DrawText(g,text??"",font??Font,r,color,flags);}
    protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(e.Button!=MouseButtons.Left)return;Focus();if(Items.Length>VisibleRows&&e.X>=Width-15&&e.Y>=HeaderHeight){var thumb=Thumb;if(thumb.Contains(e.Location)){dragOffset=e.Y-thumb.Y;Capture=true;}else ScrollTo(first+(e.Y<thumb.Y?-VisibleRows:VisibleRows));return;}int index=first+(e.Y-HeaderHeight)/RowHeight;if(e.Y>=HeaderHeight&&index<Items.Length&&index<first+VisibleRows&&Items[index].Kind!="section"){SelectedIndex=index;Invalidate();if(SelectionChanged!=null)SelectionChanged();}}
    protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);if(dragOffset>=0){var track=Track;ScrollTo((int)Math.Round((double)(e.Y-dragOffset-track.Y)*Math.Max(0,Items.Length-VisibleRows)/Math.Max(1,track.Height-Thumb.Height)));return;}int index=first+(e.Y-HeaderHeight)/RowHeight;string value=e.Y>=HeaderHeight&&index<Items.Length&&index<first+VisibleRows?Items[index].Name+"\n"+Items[index].Status+"\n"+Items[index].Url:"";if(tips.GetToolTip(this)!=value)tips.SetToolTip(this,value);}
    protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);dragOffset=-1;Capture=false;}
    protected override void OnMouseCaptureChanged(EventArgs e){base.OnMouseCaptureChanged(e);if(!Capture)dragOffset=-1;}
    protected override void OnMouseWheel(MouseEventArgs e){base.OnMouseWheel(e);if(e.Delta!=0)ScrollTo(first-Math.Sign(e.Delta)*3);}
    protected override bool IsInputKey(Keys key){return key==Keys.Up||key==Keys.Down||key==Keys.PageUp||key==Keys.PageDown||base.IsInputKey(key);}
    protected override void OnKeyDown(KeyEventArgs e){base.OnKeyDown(e);int delta=e.KeyCode==Keys.Down?1:e.KeyCode==Keys.Up?-1:e.KeyCode==Keys.PageDown?VisibleRows:e.KeyCode==Keys.PageUp?-VisibleRows:0;if(delta==0||Items.Length==0)return;SelectedIndex=Math.Max(0,Math.Min(Items.Length-1,SelectedIndex+delta));while(SelectedIndex>=0&&SelectedIndex<Items.Length&&Items[SelectedIndex].Kind=="section"){int next=SelectedIndex+Math.Sign(delta);if(next<0||next>=Items.Length)break;SelectedIndex=next;}if(SelectedIndex<first)first=SelectedIndex;if(SelectedIndex>=first+VisibleRows)first=SelectedIndex-VisibleRows+1;Invalidate();if(SelectionChanged!=null)SelectionChanged();e.Handled=true;}
  }
  public sealed partial class MainForm {
    internal static bool ShouldNotifyUpdate(UpdateItem row,ClientState client){return client.Servers!=null&&client.Servers.Count>0||!(row.Id=="singbox"||row.Kind=="optional"||row.Kind=="catalog");}
    AppUpdates updates;Control updatePrompt;bool startupUpdatesScheduled;
    AppUpdates Updates{get{return updates??(updates=new AppUpdates(core));}}
    void ScheduleStartupUpdates(){if(startupUpdatesScheduled)return;startupUpdatesScheduled=true;FormClosing+=(s,e)=>{if(!e.Cancel&&updates!=null)updates.Dispose();};if(Environment.GetEnvironmentVariable("MCRF_TEST_NO_STARTUP_UPDATES")=="1"||!Updates.Preferences.CheckOnStart)return;BeginInvoke(new Action(async()=>{await Task.Delay(1500);if(!IsDisposed)await CheckUpdates(true);}));}
    async Task CheckUpdates(bool notify){try{await Updates.Check(state);if(IsDisposed)return;WriteLog("Обновления: "+Updates.Activity);if(notify)ShowUpdatePrompt();}catch(OperationCanceledException){}catch(Exception ex){if(!IsDisposed)WriteLog("Проверка обновлений: "+ex.Message);}}
    void ShowUpdatePrompt(){var fresh=Updates.Items.Where(r=>r.Available&&!r.Ignored&&ShouldNotifyUpdate(r,state)).ToArray();if(fresh.Length==0||IsDisposed)return;if(updatePrompt!=null)updatePrompt.Dispose();var card=Box();card.Name="startupUpdatePrompt";card.SetBounds(ClientSize.Width-495,74,465,194);card.Anchor=AnchorStyles.Top|AnchorStyles.Right;Controls.Add(card);card.BringToFront();updatePrompt=card;
      var title=L("Есть обновления · "+fresh.Length,15,true);title.SetBounds(20,16,425,29);card.Controls.Add(title);var text=L(String.Join(", ",fresh.Select(x=>x.Name))+". Ничего не установлено автоматически.",10,false,Muted);text.AutoSize=false;text.SetBounds(20,54,425,70);card.Controls.Add(text);
      Action dismiss=()=>{if(updatePrompt==card)updatePrompt=null;card.Dispose();};var later=B("Позже",(s,e)=>dismiss());later.Name="updateLater";later.SetBounds(20,141,110,36);card.Controls.Add(later);var skip=B("Пропустить",(s,e)=>{try{Updates.Skip(fresh);dismiss();}catch(Exception ex){Toast(ex.Message);}});skip.Name="updateSkip";skip.SetBounds(141,141,132,36);card.Controls.Add(skip);var apply=B("Обновить",(s,e)=>{dismiss();RestoreWindow();ShowPage("updates");},true);apply.Name="updateOpen";apply.SetBounds(284,141,160,36);card.Controls.Add(apply);
    }
    void UpdatesBlue(){var box=Box();box.Dock=DockStyle.Fill;content.Controls.Add(box);var info=L("Проверка только ищет обновления. Установка — по вашей кнопке; списки и настройки сохраняются.",10,false,Muted);info.AutoSize=false;info.SetBounds(22,13,box.Width-44,47);info.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(info);
      var startup=new GlassToggle{Name="updatesOnStart",Text="Проверять при запуске",Checked=Updates.Preferences.CheckOnStart,BackColor=Color.Transparent,ForeColor=Ink,Location=new Point(22,61),Size=new Size(420,30)};startup.CheckedChanged+=(s,e)=>{Updates.Preferences.CheckOnStart=startup.Checked;try{Updates.Save();}catch(Exception ex){Toast(ex.Message);}};box.Controls.Add(startup);
      var check=B("Проверить сейчас",async(s,e)=>await CheckUpdates(false),true);check.Name="updateCheck";check.SetBounds(box.Width-224,61,202,37);check.Anchor=AnchorStyles.Top|AnchorStyles.Right;box.Controls.Add(check);
      var list=new UpdateListView();list.SetBounds(22,110,box.Width-44,Math.Max(108,box.Height-257));list.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(list);
      var detail=L("",10,false,Muted);detail.Name="updateDetail";detail.AutoSize=false;detail.SetBounds(22,box.Height-130,box.Width-44,57);detail.Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(detail);
      var progress=new EngineProgress{Name="updateProgress",Location=new Point(22,box.Height-72),Size=new Size(box.Width-44,14),Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right};box.Controls.Add(progress);
      var apply=B("Обновить выбранное",async(s,e)=>{var row=list.Selected;if(row==null)return;try{if(Updates.Installing||Updates.Checking)return;if(row.Kind=="app"&&!String.IsNullOrEmpty(row.AppliedVersion)){InstallAppUpdate(row);return;}if(core.Running||zapret.Running||telegramBridge.Running||connecting||zapretCancellation!=null||warpCancellation!=null||core.Engines.Packages.Any(p=>core.Engines.State(p.Id).Busy)){Toast("Сначала выключите VPN, Zapret и Telegram WS и дождитесь загрузок / проверок");return;}await Updates.Apply(row,state,store);if(IsDisposed)return;if(row.Kind=="zapret")zapret.ReloadUpdates();RefreshServers();RefreshRoutes();WriteLog("Обновлено: "+row.Name);Toast(row.Kind=="app"?"Обновление скачано. Нажмите «Установить и перезапустить»":"Обновлено: "+row.Name);list.Invalidate();}catch(Exception ex){if(!IsDisposed){WriteLog("Обновление не применено: "+ex.Message);Toast(ex.Message);}}},true);apply.Name="updateApply";apply.SetBounds(22,box.Height-62,284,40);apply.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(apply);
      var skip=B("Пропустить версию",(s,e)=>{if(list.Selected!=null){try{Updates.Skip(new[]{list.Selected});list.Invalidate();}catch(Exception ex){Toast(ex.Message);}}});skip.Name="updateSkipSelected";skip.SetBounds(318,box.Height-62,201,40);skip.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;box.Controls.Add(skip);
      var release=B("Источник / релиз",(s,e)=>{var row=list.Selected;Uri uri;if(row==null||!Uri.TryCreate(row.Url,UriKind.Absolute,out uri)||uri.Scheme!="https")return;try{Process.Start(new ProcessStartInfo(uri.AbsoluteUri){UseShellExecute=true});}catch(Exception ex){Toast(ex.Message);}});release.SetBounds(box.Width-219,box.Height-62,197,40);release.Anchor=AnchorStyles.Bottom|AnchorStyles.Right;box.Controls.Add(release);
      var timer=new Timer{Interval=180};UpdateItem[] shown=null;Action refresh=()=>{if(box.IsDisposed)return;var current=Updates.Items.ToArray();if(shown==null||shown.Length!=current.Length||!shown.SequenceEqual(current)){shown=current;list.Reload(shown);}var row=list.Selected;check.Enabled=!Updates.Checking&&!Updates.Installing;check.Text=Updates.Checking?"Проверяем…":"Проверить сейчас";progress.Visible=Updates.Checking||Updates.Installing;progress.Percent=Updates.Checking?15:row!=null&&row.Kind=="optional"&&Updates.Installing?core.Engines.State(row.Package.Id).Percent:Updates.Progress;progress.Invalidate();detail.Text=Updates.Checking||Updates.Installing?Updates.Activity:row==null?Updates.CheckedAt==DateTime.MinValue?"Нажмите «Проверить сейчас» или дождитесь фоновой проверки.":"Проверено: "+Updates.CheckedAt.ToString("dd.MM.yyyy HH:mm:ss"):row.Name+" · "+row.Status+(row.Kind=="list"?"\nЛокальная копия сохраняется. Изменения применяются при повторном включении модулей.":row.Kind=="text"||row.Kind=="flowseal"||row.Kind=="zapret"?"\nСохранённые стратегии не выбираются заново автоматически; после обновления повторите тесты.":"");apply.Enabled=row!=null&&(row.Available||(row.Kind=="optional"&&!core.Engines.Installed(row.Package.Id)))&&row.Kind!="link"&&row.Kind!="catalog"&&!Updates.Checking&&!Updates.Installing;apply.Text=row!=null&&row.Kind=="app"?(String.IsNullOrEmpty(row.AppliedVersion)?"Скачать обновление":"Установить и перезапустить"):(row!=null&&row.Kind=="optional"&&!core.Engines.Installed(row.Package.Id)?"Скачать движок":"Обновить выбранное");release.Enabled=row!=null&&!String.IsNullOrEmpty(row.Url);skip.Enabled=row!=null&&row.Available&&!Updates.Installing&&!Updates.Checking;list.Invalidate();};list.SelectionChanged+=refresh;timer.Tick+=(s,e)=>refresh();refresh();timer.Start();box.Disposed+=(s,e)=>timer.Dispose();
    }
    void InstallAppUpdate(UpdateItem row){if(core.Running||zapret.Running||telegramBridge.Running||connecting||zapretCancellation!=null||warpCancellation!=null){Toast("Сначала выключите все подключения и проверки");return;}if(!File.Exists(row.AppliedVersion)||AppUpdates.HashFile(row.AppliedVersion)!=row.Asset.digest.Substring(7))throw new InvalidDataException("Скачанное обновление изменилось. Проверьте и скачайте заново");string target=Application.ExecutablePath;if(Path.GetFileName(target).ToLowerInvariant()!="mcrf.exe")throw new InvalidOperationException("Обновление доступно для файла mcrf.exe");string script=AppUpdateInstaller.Script(Process.GetCurrentProcess().Id,row.AppliedVersion,target,row.Asset.digest.Substring(7),store.FilePath);string encoded=Convert.ToBase64String(Encoding.Unicode.GetBytes(script));var psi=new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"WindowsPowerShell","v1.0","powershell.exe"),"-NoProfile -NonInteractive -WindowStyle Hidden -EncodedCommand "+encoded){UseShellExecute=false,CreateNoWindow=true};Process.Start(psi);Close();}
  }
  public static class AppUpdateInstaller {
    static string Quote(string value){return "'"+value.Replace("'","''")+"'";}
    public static string ReadyEvent;
    public static void ConfirmStartup(){if(!System.Text.RegularExpressions.Regex.IsMatch(ReadyEvent??"", @"^Local\\MCRF-update-[a-f0-9]{32}$"))return;try{using(var signal=System.Threading.EventWaitHandle.OpenExisting(ReadyEvent))signal.Set();}catch(System.Threading.WaitHandleCannotBeOpenedException){}catch(UnauthorizedAccessException){}}
    public static string Script(int pid,string source,string target,string sha,string settingsFile=null){
      if(!System.Text.RegularExpressions.Regex.IsMatch(sha??"", @"^[a-fA-F0-9]{64}$"))throw new InvalidDataException("Некорректный SHA-256");
      return "$ErrorActionPreference='Stop'; $taskSource="+Quote(Path.GetFullPath(source))+"; $taskTarget="+Quote(Path.GetFullPath(target))+"; $taskSettings="+(settingsFile==null?"$null":Quote(Path.GetFullPath(settingsFile)))+"; "+
        "$taskTag=[Guid]::NewGuid().ToString('N'); $taskBackup=$taskTarget+'.previous-'+$taskTag; $taskStage=$taskTarget+'.new-'+$taskTag; $taskSettingsBackup=if($taskSettings){$taskSettings+'.before-update-'+$taskTag}else{$null}; $taskReplaced=$false; $taskNew=$null; $taskEvent=$null; "+
        "try { Wait-Process -Id "+pid+" -Timeout 90 -ErrorAction SilentlyContinue; if(Get-Process -Id "+pid+" -ErrorAction SilentlyContinue){throw 'MCRF is still running'}; "+
        "if((Get-FileHash -LiteralPath $taskSource -Algorithm SHA256).Hash -ne "+Quote(sha)+"){throw 'SHA256 mismatch'}; "+
        "if($taskSettings -and (Test-Path -LiteralPath $taskSettings)){Copy-Item -LiteralPath $taskSettings -Destination $taskSettingsBackup}; "+
        "$taskEventName='Local\\MCRF-update-'+$taskTag; $taskSecurity=[Security.AccessControl.EventWaitHandleSecurity]::new(); $taskSid=[Security.Principal.WindowsIdentity]::GetCurrent().User; $taskRule=[Security.AccessControl.EventWaitHandleAccessRule]::new($taskSid,[Security.AccessControl.EventWaitHandleRights]::FullControl,[Security.AccessControl.AccessControlType]::Allow); $taskSecurity.SetAccessRuleProtection($true,$false); $taskSecurity.AddAccessRule($taskRule); $taskCreated=$false; $taskEvent=[Threading.EventWaitHandle]::new($false,[Threading.EventResetMode]::ManualReset,$taskEventName,[ref]$taskCreated,$taskSecurity); if(-not $taskCreated){throw 'Readiness event collision'}; "+
        "Copy-Item -LiteralPath $taskSource -Destination $taskStage; [IO.File]::Replace($taskStage,$taskTarget,$taskBackup); $taskReplaced=$true; "+
        "$taskNew=Start-Process -FilePath $taskTarget -ArgumentList ('--update-ready-event='+$taskEventName) -WindowStyle Hidden -PassThru; $taskReady=$false; $taskWatch=[Diagnostics.Stopwatch]::StartNew(); "+
        "while($taskWatch.Elapsed.TotalSeconds -lt 90){if($taskEvent.WaitOne(500)){$taskReady=$true;break}; if($taskNew.HasExited){break}}; if(-not $taskReady){throw 'New MCRF failed its startup health check'} "+
        "} catch { $_.Exception.Message | Out-File -LiteralPath ($taskSource+'.install-error.txt'); "+
        "if($taskReplaced){if($taskNew -and -not $taskNew.HasExited){$taskNew.Kill(); $taskNew.WaitForExit()}; [IO.File]::Replace($taskBackup,$taskTarget,$taskTarget+'.failed-'+$taskTag); if($taskSettingsBackup -and (Test-Path -LiteralPath $taskSettingsBackup)){if(Test-Path -LiteralPath $taskSettings){[IO.File]::Replace($taskSettingsBackup,$taskSettings,$taskSettings+'.failed-'+$taskTag)}else{[IO.File]::Move($taskSettingsBackup,$taskSettings)}}}; "+
        "if(-not(Get-Process -Id "+pid+" -ErrorAction SilentlyContinue)){Start-Process -FilePath $taskTarget -WindowStyle Hidden} "+
        "} finally {if($taskEvent){$taskEvent.Dispose()}}";
    }
  }
}
