using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows.Forms;

namespace SplifyWin {
  public static class SetupPlan {
    public static string Destination(ServiceAccess direct,ServiceAccess zapret,ServiceAccess vpn){return direct==ServiceAccess.Available?"direct":zapret==ServiceAccess.Available?"zapret":vpn==ServiceAccess.Available?"proxy":null;}
  }
  public static class SetupServiceProbe {
    public static async Task<ZapretCheckRow> Measure(NetworkCore core,IEnumerable<ZapretService> services,bool proxy,CancellationToken token,Action<string> progress,Action<ZapretCheckRow> live=null){
      var row=new ZapretCheckRow{Name=proxy?"Через VPN":"Без обхода",CheckedAt=DateTime.Now,Checking=true};if(live!=null)live(row);
      using(var video=new VideoProbe(core.CurlExecutable,(proxy?"--noproxy \"\" --proxy socks5h://127.0.0.1:10808 ":"--noproxy \"*\" ")+"--cacert "+ZapretRuntime.Quote(Path.Combine(core.DataRoot,"core","curl-ca-bundle.crt"))))
      using(var gate=new SemaphoreSlim(4)){
        var tasks=services.Select(async service=>{
          var rounds=new List<ZapretEndpointResult[]>();
for(int round=0;round<(service.Urls.Length==1&&(service.Urls[0]==VideoProbe.Target||service.Urls[0]==VideoProbe.PornhubTarget||ServiceBrowserProbe.Supports(service.Urls[0]))?1:2);round++){
            var results=await Task.WhenAll(service.Urls.Select(async url=>{
              await gate.WaitAsync(token);try{return url==VideoProbe.Target||url==VideoProbe.PornhubTarget?await video.RunMediaFor(url,token):await Probe(core,url,proxy,token);}finally{gate.Release();}
            }));rounds.Add(results);
          }
          var result=ZapretChecks.Combine(service,rounds[0],rounds.Count==1?new ZapretEndpointResult[0]:rounds[1]);lock(row.Services)row.Services.Add(result);
          if(progress!=null)progress(service.Name+": "+ZapretChecks.Label(result.Access));
        }).ToArray();await Task.WhenAll(tasks);
      }row.Checking=false;return row;
    }
    static async Task<ZapretEndpointResult> Probe(NetworkCore core,string url,bool proxy,CancellationToken token){
      if(url==DiscordInterfaceProbe.Target)return await DiscordInterfaceProbe.Run(proxy,token);
if(ServiceBrowserProbe.Supports(url))return await ServiceBrowserProbe.Run(Path.Combine(core.DataRoot,"core"),url,proxy?"socks5://127.0.0.1:10808":null,token,null,HostsCandidates.StrategyBudgetMs);
      string args="--silent --show-error --location --max-redirs 3 --proto =https --proto-redir =https --http1.1 --compressed --dump-header - --header \"Connection: close\" --user-agent \"Mozilla/5.0\" "+(proxy?"--noproxy \"\" --proxy socks5h://127.0.0.1:10808 ":"--noproxy \"*\" ")+"--connect-timeout 3 --max-time 5 --cacert "+ZapretRuntime.Quote(Path.Combine(core.DataRoot,"core","curl-ca-bundle.crt"))+" --write-out \"\nMCRF_HTTP:%{http_code}\" "+ZapretRuntime.Quote(url);
      return await BoundedProbe.Run(core.CurlExecutable,args,url,token);
    }
  }
  public sealed partial class MainForm {
    CancellationTokenSource setupCancellation;NetworkCore setupProbeCore;
    bool setupScheduled,telegramStarting;
    public void OpenSetup(){ShowPage("setup");}
    async Task StartTelegramWithConsent(){
      if(telegramStarting)throw new InvalidOperationException("Telegram WS уже запускается. Дождитесь завершения.");telegramStarting=true;SyncTray();
      try{await StartTelegramCoreWithConsent();}finally{telegramStarting=false;if(!IsDisposed)SyncTray();}
    }
    async Task StartTelegramCoreWithConsent(){
      TelegramPortException problem=null;
      try{await Task.Run(()=>telegramBridge.Start(core.TelegramExecutable));}
      catch(TelegramPortException ex){problem=ex;}
      if(problem!=null){RestoreWindow();int? replacement=await AskTelegramPort(problem.Message);if(!replacement.HasValue)return;int old=telegramBridge.Port;
        try{telegramBridge.SetPort(replacement.Value);await Task.Run(()=>telegramBridge.Start(core.TelegramExecutable));state.TelegramPort=telegramBridge.Port;store.Save(state);WriteLog("Telegram WS: выбран порт "+telegramBridge.Port);}
        catch{telegramBridge.Stop();telegramBridge.SetPort(old);state.TelegramPort=old;throw;}
      }
      if(!IsDisposed){blueDashboard.Invalidate();SyncTray();}
    }
    Task<int?> AskTelegramPort(string reason){
      var done=new TaskCompletionSource<int?>();var veil=new GlassBackdrop(blueDashboard){Dock=DockStyle.Fill};var popup=new GlassPopupPanel{Size=new Size(570,300)};veil.Controls.Add(popup);
      Action layout=()=>popup.Location=new Point((veil.Width-popup.Width)/2,(veil.Height-popup.Height)/2);veil.Resize+=(s,e)=>layout();
      var text=L(reason+"\nМожно выбрать другой порт. Без подтверждения ничего не меняется.",11,false,Muted);text.AutoSize=false;text.SetBounds(24,22,520,105);popup.Controls.Add(text);
      var input=T();input.Text=(telegramBridge.Port==65535?19071:telegramBridge.Port+1).ToString();input.SetBounds(24,138,220,40);popup.Controls.Add(input);
      Action<int?> finish=value=>{done.TrySetResult(value);veil.Dispose();};veil.Disposed+=(s,e)=>done.TrySetResult(null);
      var change=B("Сменить порт",(s,e)=>{int port;if(!Int32.TryParse(input.Text,out port)||port<1024||port>65535){text.Text="Введите порт от 1024 до 65535.";return;}finish(port);},true);change.SetBounds(24,228,240,40);popup.Controls.Add(change);
      var cancel=B("Оставить выключенным",(s,e)=>finish(null));cancel.SetBounds(282,228,260,40);popup.Controls.Add(cancel);Controls.Add(veil);veil.BringToFront();layout();input.Focus();return done.Task;
    }
    void ScheduleStartupSetup(){
      if(setupScheduled)return;setupScheduled=true;FormClosing+=(s,e)=>{if(!e.Cancel){if(setupCancellation!=null)setupCancellation.Cancel();var probe=setupProbeCore;if(probe!=null)Task.Run(()=>probe.Stop());}};
      if(state.SetupSeen||Environment.GetEnvironmentVariable("MCRF_TEST_NO_STARTUP_SETUP")=="1")return;
      BeginInvoke(new Action(()=>{if(!IsDisposed)ShowPage("setup");}));
    }
    void SetupBlue(){
      var box=Box();box.Dock=DockStyle.Fill;content.Controls.Add(box);
      Action refreshSteps=null;
      var wizardServices=ZapretChecks.Services.Where(x=>x.Id!="spotify"&&x.Id!="rutracker"&&x.Id!="pornhub").ToArray();
      var intro=L("Выберите нужные сервисы. Сначала проверим доступ без обхода, затем Zapret и VPN. Настройки применяются только по вашей кнопке.",10,false,Muted);intro.AutoSize=false;intro.SetBounds(22,14,box.Width-44,48);intro.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(intro);
      var mode=new GlassPicker{Name="setupVpnChoice",Location=new Point(22,70),Width=230};mode.SetItems(new[]{"Есть VPN","Без VPN"});mode.SelectedIndex=state.Servers.Any(n=>!WarpPicker.IsWarp(n))?0:1;box.Controls.Add(mode);
      var services=new GlassPicker{Name="setupServices",MultiSelect=true,EmptySelectionText="Выберите сервисы",Location=new Point(267,70),Width=box.Width-289,Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};services.SelectionCaption="Сервисов";services.SetItems(wizardServices.Select(x=>x.CheckName));for(int i=0;i<wizardServices.Length;i++)services.SetChecked(i,true);box.Controls.Add(services);
      var servers=state.Servers.Where(n=>!WarpPicker.IsWarp(n)).ToArray();var server=new GlassPicker{Name="setupServer",Location=new Point(22,123),Width=box.Width-44,Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};server.SetItems(servers.Length==0?new[]{"Добавьте VPN в разделе «Серверы»"}:servers.Select(x=>ServerIdentity.ListName(x.Name)));server.SelectedIndex=Math.Max(0,Array.FindIndex(servers,x=>x.Id==state.SelectedServerId));box.Controls.Add(server);
      var warpTargets=new GlassPicker{Name="setupWarpTargets",MultiSelect=true,SelectionCaption="Через WARP",EmptySelectionText="Выберите сервисы, направляемые в WARP",Location=new Point(22,123),Width=box.Width-44,Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};warpTargets.SetItems(wizardServices.Select(x=>x.Name));box.Controls.Add(warpTargets);
      var warpType=new GlassPicker{Name="setupWarpType",Location=new Point(22,222),Width=300};warpType.SetItems(new[]{"Авто · WireGuard / AmneziaWG","WireGuard","AmneziaWG"});warpType.SelectedIndex=0;warpType.Height=30;box.Controls.Add(warpType);
      var importServers=B("Добавить / выбрать VPN…",(s,e)=>OpenSetupServers());importServers.SetBounds(22,123,box.Width-44,40);importServers.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(importServers);server.Visible=false;
      bool warpAssignmentReady=false;Action modeLayout=()=>{if(refreshSteps!=null){refreshSteps();return;}warpTargets.Visible=mode.SelectedIndex==1&&warpAssignmentReady;warpType.Visible=mode.SelectedIndex==1&&warpAssignmentReady;importServers.Visible=mode.SelectedIndex==0;};
      var families=new GlassPicker{Name="setupFamilies",MultiSelect=true,SelectionCaption="Наборы стратегий",Location=new Point(22,177),Width=300};families.SetItems(new[]{"Flowseal","V","YouTube"});for(int i=0;i<3;i++)families.SetChecked(i,i<2);box.Controls.Add(families);
      var warpConsent=new GlassToggle{Checked=true,Text="Принимаю условия Cloudflare для создания WARP",Location=new Point(336,177),Size=new Size(box.Width-358,42),BackColor=Color.Transparent};box.Controls.Add(warpConsent);mode.SelectedIndexChanged+=(s,e)=>{modeLayout();warpConsent.Visible=mode.SelectedIndex==1&&warpAssignmentReady;};modeLayout();warpConsent.Visible=mode.SelectedIndex==1;
      setupServerRefresh=()=>{servers=state.Servers.Where(n=>!WarpPicker.IsWarp(n)).ToArray();server.SetItems(servers.Select(x=>ServerIdentity.ListName(x.Name)));server.SelectedIndex=Array.FindIndex(servers,x=>x.Id==state.SelectedServerId);importServers.Text=server.SelectedIndex>=0?"VPN: "+server.SelectedItem+" · изменить":"Добавить / выбрать VPN…";};setupServerRefresh();
      var warpTerms=RepositoryLink(box,"setupWarpTerms","Условия Cloudflare","https://www.cloudflare.com/application/terms/",336,222,box.Width-358);warpTerms.Visible=mode.SelectedIndex==1&&warpAssignmentReady;mode.SelectedIndexChanged+=(s,e)=>warpTerms.Visible=mode.SelectedIndex==1&&warpAssignmentReady;
      var strategies=new GlassPicker{Name="setupStrategy",Location=new Point(22,252),Width=box.Width-264,Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right};strategies.EmptySelectionText="Выберите конфиг Zapret";strategies.SetItems(new[]{"После проверки выберите конфиг Zapret"});strategies.SelectedIndex=0;box.Controls.Add(strategies);
      var status=new GlassLogBox{Name="setupJournal",ReadOnly=true,BorderStyle=BorderStyle.None,BackColor=UiTheme.Simple?Color.FromArgb(24,29,47):Color.FromArgb(30,47,80),ForeColor=GlassInk.Muted,Font=new Font("Segoe UI",14,FontStyle.Regular,GraphicsUnit.Pixel),WordWrap=true};status.SetBounds(22,305,box.Width-44,Math.Max(90,box.Height-377));status.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;status.Text="Выключите другие VPN. Проверим сайты и видео; голос — отдельно. Настройки пока не меняются.";box.Controls.Add(status);
      var buttons=new FlowLayoutPanel{Location=new Point(22,box.Height-58),Size=new Size(box.Width-44,44),Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right,BackColor=Color.Transparent,WrapContents=false};box.Controls.Add(buttons);
int step=0;Button check=null,apply=null;ZapretCheckReport report=null;ZapretCheckRow direct=null,vpn=null;ZapretCheckRow[] ranked=new ZapretCheckRow[0];ServerNode candidate=null;ZapretService[] chosen=new ZapretService[0];bool telegram=false,busy=false,stagedTelegramOwned=false,planApplied=false; Dictionary<string,SetupAssignment> assignments=null; HashSet<string> failedWithoutVpn=new HashSet<string>(),unverifiedWarp=new HashSet<string>();
      ZapretCheckReport cachedReport=null;bool reuseResults=false;Button useSaved=null;try{cachedReport=ZapretChecks.Load(Path.Combine(store.Root,"setup-results"));}catch(Exception ex){WriteLog("Сохранённая проверка мастера недоступна: "+ex.Message);}
      var results=B("Результаты Zapret",(s,e)=>{try{var last=report??ZapretChecks.Load(Path.Combine(store.Root,"setup-results"));if(last==null){Toast("Сначала запустите проверку мастера");return;}ShowSetupResults(last,null,assignments==null?null:(Action<ZapretCheckRow,ZapretService>)((row,service)=>{if(busy||!assignments.ContainsKey(service.Id))return;var assignment=assignments[service.Id];assignment.Output="zapret";assignment.Strategy=row;if(service.Id=="rutor")foreach(string alias in new[]{"rutracker","pornhub"})assignments[alias]=new SetupAssignment{ServiceId=alias,Output="zapret",Strategy=row};Toast(service.CheckName+": выбрана "+row.Name+". Применение — кнопкой «Применить план».");}));}catch(Exception ex){GlassNotice.Show(this,ex.Message,"Результаты мастера");}});results.Name="setupResults";results.SetBounds(box.Width-222,252,200,40);results.Anchor=AnchorStyles.Top|AnchorStyles.Right;box.Controls.Add(results);
      Action<string> say=value=>{if(!status.IsDisposed){status.AppendText(Environment.NewLine+DateTime.Now.ToString("HH:mm:ss")+" · "+value);status.SelectionStart=status.TextLength;status.ScrollToCaret();}};
      var clear=B("Очистить журнал",(s,e)=>status.Clear());clear.SetBounds(box.Width-222,box.Height-102,200,30);clear.Anchor=AnchorStyles.Bottom|AnchorStyles.Right;box.Controls.Add(clear);status.Height=Math.Max(60,status.Height-36);var journalHost=new GlassFieldPanel{Name="setupJournalSurface",Location=status.Location,Size=status.Size,Anchor=status.Anchor};box.Controls.Remove(status);box.Controls.Add(journalHost);journalHost.Controls.Add(status);status.InstallRails(journalHost);
      Action preview=()=>{var selected=strategies.SelectedIndex>=0&&strategies.SelectedIndex<ranked.Length?ranked[strategies.SelectedIndex]:null;if(assignments!=null){say(String.Join(Environment.NewLine,chosen.Select(x=>x.Name+": "+(assignments[x.Id].Output=="skip"?"не назначено":assignments[x.Id].Output=="warp"?"WARP":assignments[x.Id].Output=="byetube"?"ByeTube · "+assignments[x.Id].Strategy.Name:assignments[x.Id].Output=="zapret"?"Zapret · "+assignments[x.Id].Strategy.Name:"напрямую")))+(assignments.Values.Any(a=>a.Hosts!=null&&a.Hosts.Count>0)?"\nHosts: "+String.Join(", ",assignments.Values.Where(a=>a.Hosts!=null&&a.Hosts.Count>0).Select(a=>a.ServiceId+" · "+a.Hosts.Count+" доменов")):"")+(telegram?"\nTelegram-прокси: включение по ссылке.":"")+"\nНичего ещё не применено. Нажмите «Применить план».");return;}say(String.Join(Environment.NewLine,chosen.Select(x=>x.Name+": "+SetupDestinationLabel(mode.SelectedIndex==1&&warpTargets.SelectedIndices.Any(i=>wizardServices[i].Id==x.Id)?(vpn!=null&&vpn.Access(x.Id)==ServiceAccess.Available?"proxy":null):SetupPlan.Destination(direct==null?ServiceAccess.Unknown:direct.Access(x.Id),selected==null?ServiceAccess.Unknown:selected.Access(x.Id),vpn==null?ServiceAccess.Unknown:vpn.Access(x.Id)))))+(telegram?"\nTelegram: локальный WS-прокси; включение в Telegram по ссылке.":"")+"\nНичего ещё не применено. Выберите конфиг и нажмите «Применить план».");};strategies.SelectedIndexChanged+=(s,e)=>{if(!busy&&direct!=null)preview();};
      RouteList customVpnRoute=null;
      var moduleChoices=new GlassPicker{Name="setupModules",MultiSelect=true,SelectionCaption="Модули",Location=new Point(336,177),Width=box.Width-358};moduleChoices.SetItems(new[]{"Zapret (необязательно)","Telegram WS (необязательно)"});moduleChoices.SetChecked(0,mode.SelectedIndex==1);box.Controls.Add(moduleChoices);
      var chooseRoutes=B("Что направлять в VPN…",async(s,e)=>{if(busy)return;var value=await ChooseVpnConstructor(customVpnRoute);if(value!=null){direct=vpn=null;report=null;ranked=new ZapretCheckRow[0];apply.Enabled=false;value.Target="proxy";customVpnRoute=value;say("В VPN добавлен список: "+value.Name+". Пока не применён.");}});chooseRoutes.Name="setupVpnRoutes";chooseRoutes.SetBounds(336,222,box.Width-358,30);chooseRoutes.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;box.Controls.Add(chooseRoutes);chooseRoutes.Visible=moduleChoices.Visible=mode.SelectedIndex==0;
      var dnsRoutes=B("DNS для VPN…",(s,e)=>OpenSetupSection("exits"));dnsRoutes.Name="setupExitDns";dnsRoutes.SetBounds(22,222,300,30);dnsRoutes.Visible=mode.SelectedIndex==0;box.Controls.Add(dnsRoutes);mode.SelectedIndexChanged+=(s,e)=>dnsRoutes.Visible=mode.SelectedIndex==0;
      var vpnLinkHost=new GlassFieldPanel{Name="setupVpnImportSurface",Size=new Size(box.Width-180,40)};var vpnLink=T();vpnLink.Name="setupVpnLink";vpnLink.BorderStyle=BorderStyle.None;vpnLink.BackColor=GlassFieldPanel.InputColor;vpnLink.SetBounds(12,10,vpnLinkHost.Width-24,24);vpnLink.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;vpnLinkHost.Controls.Add(vpnLink);box.Controls.Add(vpnLinkHost);
      var addVpn=B("Добавить",async(s,e)=>{if(busy)return;if(String.IsNullOrWhiteSpace(vpnLink.Text)){Toast("Вставьте ссылку VPN или подписку");return;}var button=(Button)s;busy=true;button.Enabled=false;try{if(await ImportBatch(vpnLink.Text.Trim(),false)){var newest=state.Servers.LastOrDefault();if(newest!=null){state.SelectedServerId=newest.Id;state.AutoSelect=false;store.Save(state);}setupServerRefresh();vpnLink.Clear();Toast("VPN добавлен");OfferMissingEngines();}}finally{busy=false;if(!button.IsDisposed)button.Enabled=true;if(refreshSteps!=null)refreshSteps();}},true);addVpn.Name="setupAddVpn";box.Controls.Add(addVpn);
      var vpnDnsLabel=L("DNS для VPN",11,true);box.Controls.Add(vpnDnsLabel);
      var vpnDns=new GlassPicker{Name="setupVpnDnsProvider",FlatSurface=true};vpnDns.SetItems(new[]{"Автоматически","Общий"}.Concat(DnsOptions.Providers.Where(p=>p!="Системный")));box.Controls.Add(vpnDns);
      var vpnDnsType=new GlassPicker{Name="setupVpnDnsProtocol",FlatSurface=true};box.Controls.Add(vpnDnsType);
      var vpnDnsHost=new GlassFieldPanel{Name="setupVpnDnsCustomSurface"};var vpnDnsCustom=T();vpnDnsCustom.Name="setupVpnDnsCustom";vpnDnsCustom.BorderStyle=BorderStyle.None;vpnDnsCustom.BackColor=GlassFieldPanel.InputColor;vpnDnsCustom.SetBounds(12,8,300,24);vpnDnsCustom.Anchor=AnchorStyles.Top|AnchorStyles.Left|AnchorStyles.Right;vpnDnsHost.Controls.Add(vpnDnsCustom);box.Controls.Add(vpnDnsHost);
      var oldVpnDns=(state.ExitDns??new List<ExitDnsSettings>()).FirstOrDefault(x=>x.Target=="proxy");
      vpnDns.SelectedIndexChanged+=(s,e)=>{vpnDnsType.SetItems(DnsOptions.Protocols(vpnDns.SelectedItem));vpnDnsType.SelectedIndex=0;if(refreshSteps!=null)refreshSteps();};vpnDns.SelectedItem=oldVpnDns==null?"Общий":oldVpnDns.Provider=="Системный"?"Автоматически":oldVpnDns.Provider;vpnDnsType.SelectedItem=oldVpnDns==null?"UDP":oldVpnDns.Protocol;vpnDnsCustom.Text=oldVpnDns==null?"":oldVpnDns.Custom??"";
      mode.SelectedIndexChanged+=(s,e)=>chooseRoutes.Visible=moduleChoices.Visible=mode.SelectedIndex==0;
Action reset=()=>{if(busy)return;if(stagedTelegramOwned){telegramBridge.Stop();stagedTelegramOwned=false;telegram=false;}failedWithoutVpn.Clear();unverifiedWarp.Clear();direct=vpn=null;assignments=null;report=null;ranked=new ZapretCheckRow[0];warpAssignmentReady=false;modeLayout();apply.Enabled=false;};mode.SelectedIndexChanged+=(s,e)=>reset();services.CheckedItemsChanged+=(s,e)=>reset();server.SelectedIndexChanged+=(s,e)=>reset();families.CheckedItemsChanged+=(s,e)=>reset();moduleChoices.CheckedItemsChanged+=(s,e)=>reset();
      check=B("Начать проверку",async(s,e)=>{
if(busy)return;failedWithoutVpn.Clear();unverifiedWarp.Clear();if(connecting||zapretCancellation!=null||warpCancellation!=null||setupCancellation!=null){Toast("Дождитесь окончания текущей операции");return;}if(mode.SelectedIndex==0&&server.SelectedIndex>=0&&server.SelectedIndex<servers.Length&&await OfferEngineDownload(new[]{servers[server.SelectedIndex]}))return;if(!await OfferStopTun()||!await OfferStopZapret())return;
        chosen=services.SelectedIndices.Select(i=>wizardServices[i]).ToArray();if(chosen.Any(x=>x.Id=="rutor"))chosen=chosen.Concat(ZapretChecks.Services.Where(x=>x.Id=="rutracker"||x.Id=="pornhub")).ToArray();telegram=moduleChoices.SelectedIndices.Contains(1);if(chosen.Length==0&&!telegram){say("Выберите хотя бы один сервис.");return;}
        if(chosen.Length>0&&(mode.SelectedIndex==1||moduleChoices.SelectedIndices.Contains(0))&&!IsAdministrator()){if(await ConfirmChange("Для проверки Zapret нужны права администратора. Сохранённые настройки останутся; Windows запросит повышение прав.","Получить права и перезапустить","Нужны права Windows"))RequestElevation("--setup");return;}
        if(chosen.Any(ZapretChecks.CanCheckZapret)&&(mode.SelectedIndex==1||moduleChoices.SelectedIndices.Contains(0))&&families.SelectedIndices.Length==0){say("Выберите наборы стратегий Zapret.");return;}
        if(mode.SelectedIndex==0&&chosen.Length>0&&(servers.Length==0||server.SelectedIndex<0)){say("Сначала добавьте VPN-профиль в разделе «Серверы».");return;}
        
        busy=true;step=2;check.Enabled=false;apply.Enabled=false;foreach(var c in new Control[]{mode,services,server,families,warpConsent,warpTargets,warpType,importServers,strategies,moduleChoices,chooseRoutes,dnsRoutes})c.Enabled=false;
        var cancellation=new CancellationTokenSource();setupCancellation=cancellation;var token=cancellation.Token;bool reuse=reuseResults&&cachedReport!=null&&cachedReport.Complete;reuseResults=false;report=reuse?cachedReport:null;direct=reuse?report.Rows.FirstOrDefault(r=>String.IsNullOrEmpty(r.StrategyId)):null;vpn=null;ranked=new ZapretCheckRow[0];candidate=null;
        try{
          // Hosts trials use an isolated browser. Proposed records are applied only with the final plan.
          if(!reuse){say("Проверяем исходную доступность…");direct=await MeasureSetupLive(core,chosen.Where(ZapretChecks.CanCheckZapret).ToArray(),false,cancellation,say);}
          if(chosen.Length>0){
            if(!reuse){
            zapret.Prepare();var scanChosen=chosen.Where(ZapretChecks.CanCheckZapret).ToArray();var settings=new ZapretSettings{ScopeText=String.Join("\n",scanChosen.Select(x=>x.Domains)),MatchMode="addresses",TestUrls=String.Join("\n",scanChosen.SelectMany(x=>x.Urls)),CheckServices=scanChosen.Select(x=>x.Id).ToList(),CheckFamilies=families.SelectedIndices.Select(i=>new[]{"Flowseal","V","YouTube"}[i]).ToList()};
            report=new ZapretCheckReport{Settings=settings,ApplySettings=ZapretChecks.CopySettings(settings),WizardServiceIds=chosen.Select(x=>x.Id).ToList(),ServiceIds=scanChosen.Select(x=>x.Id).ToList()};report.Rows.Add(direct);if(scanChosen.Length==0){report.Complete=true;report.MediaProbeRevision=2;}var live=scanChosen.Length==0?null:OpenLiveResults(report,"Мастер · Zapret",cancellation);zapretCancellation=cancellation;
            try{if(scanChosen.Length>0&&(mode.SelectedIndex==1||moduleChoices.SelectedIndices.Contains(0)))await zapret.Scan(report,ZapretChecks.SelectFamilies(ZapretCatalog.Load(zapret.DirectoryPath),settings.CheckFamilies),token,say,value=>{string directory=Path.Combine(store.Root,"setup-results");Directory.CreateDirectory(directory);ZapretChecks.Save(directory,value);});}finally{if(live!=null)live.Finish();if(zapretCancellation==cancellation)zapretCancellation=null;}
            }else{say("Используем сохранённые результаты от "+report.FinishedAt.ToString("dd.MM HH:mm")+". Новая проверка не запускается.");zapret.Prepare();}
            cachedReport=report;
            ranked=ZapretChecks.Rank(report.Rows);strategies.SetItems(ranked.Select(x=>x.Name+" · "+x.AdditionalPassed+"/"+chosen.Count(v=>!v.Primary)+" · "+(x.SuccessfulMilliseconds.HasValue?x.SuccessfulMilliseconds+" мс":"—")));strategies.SelectedIndex=-1;
            if(mode.SelectedIndex==1){
              assignments=reuse&&report.WizardAssignments!=null&&report.WizardAssignments.Count>0?report.WizardAssignments.ToDictionary(a=>a.ServiceId):await ChooseSetupDistribution(report,chosen,direct,token);token.ThrowIfCancellationRequested();if(assignments==null)throw new OperationCanceledException();report.WizardAssignments=assignments.Values.ToList();ZapretChecks.Save(Path.Combine(store.Root,"setup-results"),report);
              if(chosen.Any(item=>item.Id=="youtube")&&!report.Rows.Any(r=>!String.IsNullOrEmpty(r.StrategyId)&&r.Access("youtube")==ServiceAccess.Available)&&await ConfirmChange("Zapret не подтвердил воспроизведение YouTube. Проверить резервный способ ByeTube? После него продолжим проверку голоса Discord.","Проверить ByeTube","YouTube · резервный обход")){var youtube=ZapretChecks.Services.First(item=>item.Id=="youtube");var fallback=new ZapretCheckReport{Settings=new ZapretSettings{ScopeText=youtube.Domains,MatchMode="addresses",CheckServices=new List<string>{"youtube"}},ServiceIds=new List<string>{"youtube"}};var view=OpenLiveResults(fallback,"Мастер · ByeTube",cancellation);byetubeCancellation=cancellation;try{await ByeTubeScan.Run(core,fallback,token,say,value=>ZapretChecks.Save(Path.Combine(store.Root,"byetube-results"),value));byetubeReport=fallback;}finally{view.Finish();byetubeCancellation=null;}var best=fallback.Rows.Where(r=>!String.IsNullOrEmpty(r.StrategyId)&&r.Access("youtube")==ServiceAccess.Available).OrderBy(r=>r.Services.First(item=>item.Id=="youtube").Milliseconds).FirstOrDefault();if(best!=null&&await ConfirmChange("Воспроизведение подтверждено через "+best.Name+". Назначить YouTube этому выходу?","Использовать ByeTube","YouTube")){assignments["youtube"].Output="byetube";assignments["youtube"].Strategy=best;}else say("Подтверждённый ByeTube не выбран; сохраняем выбор выходов.");}

if(!report.WizardVoiceCompleted&&assignments.ContainsKey("discord")&&assignments["discord"].Output!="skip"&&VoiceCandidates(report).Length>0){say("Голос Discord: последовательная проверка без таймера");var interfaceChoice=assignments["discord"].Strategy;if(interfaceChoice!=null)report.Settings.DiscordInterfaceStrategy=interfaceChoice.StrategyId;ZapretCheckRow voiceChoice=null;await RunDiscordVoiceCheck(report,row=>voiceChoice=row,token);token.ThrowIfCancellationRequested();if(voiceChoice!=null){assignments["discord"].Strategy=voiceChoice;assignments["discord"].Output="zapret";}else if(interfaceChoice!=null&&interfaceChoice.Access("discord")==ServiceAccess.Available){assignments["discord"].Strategy=interfaceChoice;assignments["discord"].Output="zapret";say("Голос не подтверждён. Для интерфейса Discord сохраняем рабочий Zapret; WARP ему не назначаем.");}}
              report.WizardVoiceCompleted=true;report.WizardAssignments=assignments.Values.ToList();ZapretChecks.Save(Path.Combine(store.Root,"setup-results"),report);await CheckSetupServicesManually(report,chosen,assignments,token);
              if(assignments.ContainsKey("rutor"))foreach(string alias in new[]{"rutracker","pornhub"})assignments[alias]=new SetupAssignment{ServiceId=alias,Output=assignments["rutor"].Output,Strategy=assignments["rutor"].Strategy};
var unresolved=chosen.Where(service=>assignments[service.Id].Output=="warp"&&service.Id!="rutracker"&&service.Id!="pornhub").ToArray();
if(unresolved.Length>0){var options=await ChooseSetupWarp(unresolved,token);token.ThrowIfCancellationRequested();if(options==null){foreach(var service in unresolved)assignments[service.Id].Output="skip";say("WARP пропущен. Эти сервисы не получат новых маршрутов.");}else{foreach(var excluded in unresolved.Where(targetService=>!options.ServiceIds.Contains(targetService.Id)))assignments[excluded.Id].Output="skip";unresolved=unresolved.Where(targetService=>options.ServiceIds.Contains(targetService.Id)).ToArray();candidate=await PrepareSetupWarp(options,token,say);if(candidate==null){foreach(var service in unresolved){assignments[service.Id].Output="skip";unverifiedWarp.Add(service.Id);}say("WARP не подготовлен. Сервисы через него не проверены; вывод о необходимости VPN пока сделать нельзя. Остальные назначения доступны для применения.");}}}
if(assignments.ContainsKey("rutor"))foreach(string alias in new[]{"rutracker","pornhub"})assignments[alias].Output=assignments["rutor"].Output;
            }else candidate=servers[server.SelectedIndex];
            if(candidate!=null){token.ThrowIfCancellationRequested();if(!core.HasEngine(candidate))throw new InvalidOperationException("Движок выбранного выхода не установлен");setupProbeCore=new NetworkCore(store);var temporary=new ClientState{Mode="proxy",AutoSelect=false,SelectedServerId=candidate.Id,Servers=new List<ServerNode>{candidate},Lists=new List<RouteList>(),DnsProvider=mode.SelectedIndex==1?"Системный":state.DnsProvider,DnsProtocol=mode.SelectedIndex==1?"Системный":state.DnsProtocol,DnsCustom=mode.SelectedIndex==1?"":state.DnsCustom};
say("Проверяем сервисы через WARP…");try{await Task.Run(()=>setupProbeCore.Start(temporary));token.ThrowIfCancellationRequested();vpn=await MeasureSetupLive(setupProbeCore,chosen.Where(x=>assignments==null||assignments[x.Id].Output=="warp").ToArray(),true,cancellation,say);if(assignments!=null){foreach(var service in chosen.Where(x=>assignments[x.Id].Output=="warp"&&x.Id!="discord"&&x.Id!="rutracker"&&x.Id!="pornhub")){bool? answer=await CheckMappedServiceManually(service,service.Urls[0],new List<HostsCandidate>(),token,"socks5://127.0.0.1:10808");token.ThrowIfCancellationRequested();var result=vpn.Services.FirstOrDefault(r=>r.Id==service.Id);if(result!=null&&answer.HasValue){result.Access=answer.Value?ServiceAccess.Available:ServiceAccess.Unavailable;result.Detail="Ручная проверка через выбранный WARP: "+(answer.Value?"работает":"не работает");}if(answer==false||!answer.HasValue&&vpn.Access(service.Id)==ServiceAccess.Unavailable){assignments[service.Id].Output="skip";failedWithoutVpn.Add(service.Id);}}if(assignments.ContainsKey("rutor"))foreach(string alias in new[]{"rutracker","pornhub"})assignments[alias].Output=assignments["rutor"].Output;}}finally{setupProbeCore.Stop();setupProbeCore=null;}}
          }
          if(mode.SelectedIndex==1&&assignments!=null&&vpn!=null)foreach(var service in chosen.Where(service=>assignments[service.Id].Output=="warp"&&vpn.Access(service.Id)==ServiceAccess.Unavailable)){assignments[service.Id].Output="skip";failedWithoutVpn.Add(service.Id);}
if(mode.SelectedIndex==1&&(failedWithoutVpn.Count>0||unverifiedWarp.Count>0)){say(unverifiedWarp.Count>0?"WARP не подготовлен: жёлтые сервисы ещё не проверены через него.":"Для сервисов с красной отметкой мастер не нашёл рабочего способа без VPN.");await ShowSetupServiceStatus(chosen,assignments,direct,vpn,failedWithoutVpn,unverifiedWarp,token);}
if(mode.SelectedIndex==1){say("Создаём Telegram-прокси…");bool alreadyRunning=telegramBridge.Running;if(!alreadyRunning)await StartTelegramWithConsent();stagedTelegramOwned|=!alreadyRunning&&telegramBridge.Running;telegram=telegramBridge.Running;if(token.IsCancellationRequested||box.IsDisposed){if(stagedTelegramOwned){telegramBridge.Stop();stagedTelegramOwned=false;telegram=false;}token.ThrowIfCancellationRequested();throw new OperationCanceledException();}if(telegram)await ShowSetupTelegram(token);else say("Telegram-прокси не запущен. Остальные назначения можно применить.");}
          token.ThrowIfCancellationRequested();preview();apply.Enabled=true;
}catch(OperationCanceledException){if(stagedTelegramOwned){telegramBridge.Stop();stagedTelegramOwned=false;telegram=false;}say("Проверка отменена. Настройки не применены.");}catch(Exception ex){if(stagedTelegramOwned){telegramBridge.Stop();stagedTelegramOwned=false;telegram=false;}step=1;say("Проверка остановлена: "+ex.Message+" Пройденные результаты сохранены. Нажмите «Использовать прошлую проверку», чтобы продолжить.");WriteLog("Мастер: "+ex.ToString());}
        finally{if(setupCancellation==cancellation)setupCancellation=null;if(zapretCancellation==cancellation)zapretCancellation=null;cancellation.Dispose();busy=false;if(!box.IsDisposed){refreshSteps();check.Enabled=true;foreach(var c in new Control[]{mode,services,server,families,warpConsent,warpTargets,warpType,importServers,strategies,moduleChoices,chooseRoutes})c.Enabled=true;}}
      },true);
      useSaved=B("Использовать прошлую проверку",(s,e)=>{if(busy||cachedReport==null||!cachedReport.Complete)return;var ids=cachedReport.WizardServiceIds??cachedReport.ServiceIds??cachedReport.Settings.CheckServices;for(int i=0;i<wizardServices.Length;i++)services.SetChecked(i,ids.Contains(wizardServices[i].Id));reuseResults=true;check.PerformClick();});useSaved.Name="setupReuseResults";box.Controls.Add(useSaved);
      apply=B("Применить план",async(s,e)=>{
        if(busy||direct==null)return;if(core.Running||zapret.Running||connecting||zapretCancellation!=null||warpCancellation!=null){say("Выключите подключения перед применением.");return;}
        var selected=strategies.SelectedIndex>=0&&strategies.SelectedIndex<ranked.Length?ranked[strategies.SelectedIndex]:null;
        var destinations=chosen.ToDictionary(x=>x.Id,x=>assignments!=null?(assignments[x.Id].Output=="skip"?"skip":assignments[x.Id].Output=="warp"?(candidate==null?null:"proxy"):assignments[x.Id].Output):SetupPlan.Destination(direct.Access(x.Id),selected==null?ServiceAccess.Unknown:selected.Access(x.Id),vpn==null?ServiceAccess.Unknown:vpn.Access(x.Id)));

        if(mode.SelectedIndex==1&&assignments==null)foreach(string id in chosen.Where(x=>ZapretChecks.WarpPreferred(x.Id)).Select(x=>x.Id))if(destinations.ContainsKey(id))destinations[id]=candidate!=null&&vpn!=null&&vpn.Access(id)==ServiceAccess.Available?"proxy":null;
        if(mode.SelectedIndex==1&&assignments==null)foreach(var serviceId in warpTargets.SelectedIndices.Select(i=>wizardServices[i].Id).Where(id=>destinations.ContainsKey(id)))destinations[serviceId]=vpn!=null&&vpn.Access(serviceId)==ServiceAccess.Available?"proxy":null;
        if(destinations.Values.Any(x=>x==null)){var unresolved=chosen.Where(x=>destinations[x.Id]==null).ToArray();string manualTarget=candidate!=null&&vpn!=null&&!unresolved.Any(x=>vpn.Access(x.Id)==ServiceAccess.Unavailable)?"proxy":selected!=null&&!unresolved.Any(x=>x.Id=="instagram"||x.Id=="chatgpt"||x.Id=="spotify")?"zapret":null;if(manualTarget==null){say("Для части сервисов нет подтверждённого пути. Выберите другой конфиг, рекомендации hosts для Instagram или WARP.");return;}string manualName=manualTarget=="zapret"?"выбранный конфиг Zapret":mode.SelectedIndex==1?"WARP":"выбранный VPN";if(!await ConfirmChange("Для "+String.Join(", ",unresolved.Select(x=>x.Name))+" проверка не дала подтверждённого результата. Направить их через "+manualName+" по вашему выбору? Проверка не считается пройденной; её цвет не изменится.","Применить с ручным маршрутом"))return;foreach(var service in unresolved)destinations[service.Id]=manualTarget;say("Неподтверждённые сервисы направляются вручную; проверьте их работу после применения.");}
        if(assignments!=null&&candidate!=null){var unconfirmed=chosen.Where(x=>assignments[x.Id].Output=="warp"&&(vpn==null||vpn.Access(x.Id)!=ServiceAccess.Available)).ToArray();if(unconfirmed.Length>0)say("Назначения WARP сохраняются по вашему выбору. Эти сервисы ещё требуют ручной проверки: "+String.Join(", ",unconfirmed.Select(x=>x.Name)));}
        if(mode.SelectedIndex==1&&candidate!=null)foreach(string id in destinations.Keys.ToArray())if(destinations[id]=="proxy")destinations[id]=WarpOutputs.Tag(candidate);
        if(!IsAdministrator()&&((assignments!=null&&assignments.Values.Any(a=>a.Hosts!=null&&a.Hosts.Count>0))||destinations.Values.Contains("zapret")||destinations.Values.Any(WarpOutputs.IsTarget)||destinations.Values.Contains("proxy")||customVpnRoute!=null)){if(await ConfirmChange("Для применения этого плана нужны права Windows. Настройки ещё не изменены.","Получить права и перезапустить","Доступ Windows"))RequestElevation("--setup");return;}
        byte[] hostsBefore=null,hostsAfter=null;bool hostsWritten=false;
        if(assignments!=null&&assignments.Values.Any(a=>a.Hosts!=null&&a.Hosts.Count>0&&a.Output!="skip")){hostsBefore=File.ReadAllBytes(HostsEditor.PathName);hostsAfter=hostsBefore;foreach(var assignment in assignments.Values.Where(a=>a.Hosts!=null&&a.Hosts.Count>0&&a.Output!="skip"))hostsAfter=HostsEditor.Compose(hostsAfter,HostsCandidates.Entries(assignment.Hosts),assignment.ServiceId);if(!await ConfirmChange("План добавит проверенные записи hosts:\n"+String.Join("\n",assignments.Values.Where(a=>a.Hosts!=null&&a.Hosts.Count>0&&a.Output!="skip").Select(a=>a.ServiceId+" · "+a.Hosts.Count+" доменов\n"+HostsCandidates.Entries(a.Hosts)))+"\nОстальные записи сохранятся. Создадим резервную копию. Стороннее реле ChatGPT не является сервером OpenAI.","Применить план и hosts","Изменения hosts"))return;}
        busy=true;apply.Enabled=check.Enabled=false;var applyCancellation=new CancellationTokenSource();setupCancellation=applyCancellation;var applyToken=applyCancellation.Token;string backup=new JavaScriptSerializer{MaxJsonLength=Int32.MaxValue}.Serialize(state);bool startedTelegram=false;
        try{
          if(mode.SelectedIndex==1){state.IndependentWarpOutputs=true;state.VpnEnabled=false;state.DnsProvider="Системный";state.DnsProtocol="Системный";state.DnsCustom="";if(state.ExitDns!=null)state.ExitDns.RemoveAll(d=>d.Target=="direct");}
          if(destinations.Values.Contains("byetube")){var choice=assignments.Values.First(a=>a.Output=="byetube").Strategy;int index;if(choice==null||!Int32.TryParse(choice.StrategyId.Substring(8),out index)||index<0||index>=ByeTube.Strategies.Length)throw new InvalidOperationException("Не выбрана проверенная стратегия ByeTube");state.ByeTubeStrategy=ByeTube.Strategies[index];state.ByeTubeEnabled=true;state.Mode="tun";}
          EnsureZapretProfiles();var stagedPlan=await SetupAssignments.Stage(chosen,destinations,assignments,selected,report,constructorPresetDownload??core.DownloadTextAsync);var createdProfiles=stagedPlan.Profiles;var routes=stagedPlan.Routes;
          var replaced=state.Lists.Where(r=>routes.Any(n=>n.BuiltinPreset==r.BuiltinPreset)).ToArray();state.Lists.RemoveAll(r=>replaced.Contains(r));var oldIds=replaced.Where(r=>r.Target=="zapret").Select(r=>r.ZapretProfileId).ToArray();state.ZapretProfiles.RemoveAll(p=>oldIds.Contains(p.Id)&&!state.Lists.Any(r=>r.ZapretProfileId==p.Id));state.ZapretProfiles.AddRange(createdProfiles);state.Lists.InsertRange(0,routes);ZapretProfile profile=createdProfiles.FirstOrDefault();
          if(candidate!=null&&(mode.SelectedIndex==1||destinations.Values.Contains("proxy")||customVpnRoute!=null)){var old=state.Servers.FirstOrDefault(x=>x.Id==candidate.Id);if(old!=null)state.Servers.Remove(old);state.Servers.Add(candidate);if(mode.SelectedIndex==1){state.WarpEnabled=destinations.Values.Any(WarpOutputs.IsTarget);state.VpnEnabled=false;}else{state.SelectedServerId=candidate.Id;state.AutoSelect=false;state.VpnEnabled=true;}state.Mode="tun";}
          if(hostsAfter!=null){applyToken.ThrowIfCancellationRequested();await Task.Run(()=>HostsRepair.Apply(store.Root,HostsEditor.Managed(hostsAfter),hostsBefore));hostsWritten=true;}
          if(profile!=null)await StartSavedZapretProfiles(applyToken);
          if(destinations.Values.Contains("proxy")||destinations.Values.Any(WarpOutputs.IsTarget)||destinations.Values.Contains("byetube")||customVpnRoute!=null){if(!IsAdministrator())throw new InvalidOperationException("Для TUN нужны права Windows.");await Task.Run(()=>core.Start(state));applyToken.ThrowIfCancellationRequested();if(IsDisposed)throw new OperationCanceledException();expectedRunning=true;connectedAtUtc=DateTime.UtcNow;connectionGeneration++;if(state.VpnEnabled)CheckSession(connectionGeneration);else{WriteLog("WARP: отдельные выходы подключены; VPN выключен");SyncTray();blueDashboard.Invalidate();}}
          if(telegram&&!telegramBridge.Running){await StartTelegramWithConsent();startedTelegram=telegramBridge.Running;if(!startedTelegram)throw new InvalidOperationException("Telegram оставлен выключенным; план не применён.");}
applyToken.ThrowIfCancellationRequested();if(IsDisposed)throw new OperationCanceledException();state.SetupSeen=true;state.SetupServices=chosen.Select(x=>x.Id).Concat(telegram?new[]{"telegram"}:new string[0]).ToList();store.Save(state);planApplied=true;stagedTelegramOwned=false;
          if(profile!=null){report.ProfileId=profile.Id;report.LastAppliedId=profile.Settings.Strategy;report.LastAppliedAt=DateTime.Now;PersistZapretReport(report);zapretReport=report;reportLoaded=true;}
          say("План применён. Предыдущие списки сохранены; новые правила добавлены перед ними.\n"+(telegram?"Откройте раздел Telegram WS и нажмите «Подключить в Telegram».\n":"")+"Видео и звонки проверьте в самих приложениях.");WriteLog("Мастер: план применён");blueDashboard.Invalidate();
}catch(Exception ex){core.Stop();zapret.Stop();if(startedTelegram||stagedTelegramOwned){telegramBridge.Stop();stagedTelegramOwned=false;telegram=false;}expectedRunning=false;if(hostsWritten){try{HostsRepair.Apply(store.Root,HostsEditor.Managed(hostsBefore),hostsAfter);}catch(Exception restoreError){WriteLog("Не удалось восстановить hosts: "+restoreError.Message);say("Проверьте hosts: восстановление не выполнено. Резервная копия находится в hosts-backups.");}}state=new JavaScriptSerializer{MaxJsonLength=Int32.MaxValue}.Deserialize<ClientState>(backup);store.Save(state);say("План не применён, настройки восстановлены: "+ex.Message);}
        finally{if(setupCancellation==applyCancellation)setupCancellation=null;applyCancellation.Dispose();busy=false;if(!box.IsDisposed)check.Enabled=true;}
      },true);apply.Enabled=false;
      var cancel=B("Отменить",(s,e)=>{if(setupCancellation!=null){setupCancellation.Cancel();var probe=setupProbeCore;if(probe!=null)Task.Run(()=>probe.Stop());}else{state.SetupSeen=true;store.Save(state);ShowPage("");}});
      var rights=B("Права Windows",(s,e)=>{if(!busy)RequestElevation("--setup");});rights.Enabled=!IsAdministrator();
      foreach(var b in new[]{check,apply,cancel}){b.Size=new Size(190,38);b.Margin=new Padding(0,0,10,0);buttons.Controls.Add(b);}
      var stepTitle=L("",16,true);stepTitle.Name="setupStepTitle";stepTitle.SetBounds(22,16,box.Width-44,36);box.Controls.Add(stepTitle);intro.SetBounds(22,56,box.Width-44,40);
      var duration=L("Проверка стратегий займёт около 10 минут.",10,true,Color.FromArgb(255,220,110));duration.Name="setupDuration";duration.SetBounds(22,218,box.Width-44,22);box.Controls.Add(duration);
      var previous=B("Назад",(s,e)=>{if(busy||step==0)return;step--;refreshSteps();});previous.Name="setupPrevious";
      var forward=B("Далее",async(s,e)=>{if(busy)return;if(step==1&&mode.SelectedIndex==0&&(servers.Length==0||server.SelectedIndex<0)){Toast("Сначала добавьте и выберите VPN");return;}if(step==1&&mode.SelectedIndex==0&&await OfferEngineDownload(new[]{servers[server.SelectedIndex]}))return;if(step==1&&mode.SelectedIndex==0&&customVpnRoute==null){Toast("Выберите, что направлять в VPN");return;}if(step==1&&mode.SelectedIndex==0){var draftDns=vpnDns.SelectedIndex==1?null:new ExitDnsSettings{Target="proxy",Provider=vpnDns.SelectedIndex==0?"Системный":vpnDns.SelectedItem,Protocol=vpnDns.SelectedIndex==0?"Системный":vpnDnsType.SelectedItem,Custom=vpnDnsCustom.Text.Trim()};try{if(draftDns!=null)DnsOptions.Build(new ClientState{DnsProvider=draftDns.Provider,DnsProtocol=draftDns.Protocol,DnsCustom=draftDns.Custom});RouteCompiler.Compile(customVpnRoute,"direct");if(!await OfferStopTun())return;string backup=new JavaScriptSerializer().Serialize(state);try{customVpnRoute.Target="proxy";customVpnRoute.Enabled=true;customVpnRoute.BuiltinPreset="setup-vpn";state.Lists.RemoveAll(r=>r.BuiltinPreset=="setup-vpn");state.Lists.Insert(0,customVpnRoute);if(state.ExitDns==null)state.ExitDns=new List<ExitDnsSettings>();state.ExitDns.RemoveAll(d=>d.Target=="proxy");if(draftDns!=null)state.ExitDns.Add(draftDns);state.SelectedServerId=servers[server.SelectedIndex].Id;state.AutoSelect=false;state.VpnEnabled=true;state.SetupSeen=true;store.Save(state);}catch{state=new JavaScriptSerializer().Deserialize<ClientState>(backup);throw;}ShowPage("");Toast("VPN, маршруты и DNS сохранены. Подключите VPN на главной.");}catch(Exception ex){GlassNotice.Show(this,ex.Message,"Не удалось сохранить VPN");}return;}if(step<3)step++;refreshSteps();},true);forward.Name="setupNext";
      previous.Size=forward.Size=new Size(140,38);previous.Margin=forward.Margin=new Padding(0,0,10,0);buttons.Controls.Add(previous);buttons.Controls.Add(forward);
      Action paintSteps=()=>{
        if(box.IsDisposed)return;
        foreach(Control c in new Control[]{mode,services,server,importServers,vpnLinkHost,addVpn,vpnDnsLabel,vpnDns,vpnDnsType,vpnDnsHost,families,warpConsent,warpTargets,warpType,warpTerms,strategies,results,moduleChoices,chooseRoutes,dnsRoutes,journalHost,clear,check,apply,useSaved})c.Visible=false;
        stepTitle.Text=(step==0?"Подключение":step==1?(mode.SelectedIndex==0?"VPN и маршруты":"Сервисы и проверка"):step==2?"Проверяем доступ и стратегии":"План и применение");
        duration.Visible=(step==1&&mode.SelectedIndex==1)||step==2;duration.Top=step==2?108:230;
        intro.Text=step==0?"Есть свой VPN? Выберите подходящий вариант.":step==1?(mode.SelectedIndex==0?"Добавьте или выберите VPN, затем настройте его маршруты и DNS.":"Выберите сервисы и наборы стратегий. После проверки предложим отдельные выходы."):step==2?"Видео проверяется воспроизведением; голос Discord — отдельным шагом. Настройки ещё не применяются.":"Проверьте распределение сервисов. Настройки изменятся только по кнопке «Применить план».";
        previous.Visible=step>0;previous.Enabled=forward.Enabled=!busy;forward.Visible=step<2&&(mode.SelectedIndex==0||step==0);forward.Text=step==1&&mode.SelectedIndex==0?"Сохранить":"Далее";cancel.Text=busy?"Отменить проверку":"Закрыть";
        if(step==0){mode.Visible=true;mode.SetBounds(22,110,Math.Min(380,box.Width-44),42);}
        if(step==1&&mode.SelectedIndex==0){vpnLinkHost.Visible=addVpn.Visible=importServers.Visible=chooseRoutes.Visible=vpnDnsLabel.Visible=vpnDns.Visible=true;vpnLinkHost.SetBounds(22,112,box.Width-192,42);addVpn.SetBounds(box.Width-156,112,134,42);importServers.SetBounds(22,170,box.Width-44,42);chooseRoutes.SetBounds(22,228,box.Width-44,42);vpnDnsLabel.SetBounds(22,296,box.Width-44,26);bool specific=vpnDns.SelectedIndex>=2;vpnDns.SetBounds(22,332,box.Width-(specific?220:44),42);vpnDnsType.Visible=specific;vpnDnsType.SetBounds(box.Width-188,332,166,42);vpnDnsHost.Visible=specific&&vpnDns.SelectedItem=="Свой";vpnDnsHost.SetBounds(22,382,box.Width-44,42);vpnDnsCustom.Width=vpnDnsHost.Width-24;}
        if(step==1&&mode.SelectedIndex==1){check.Visible=true;useSaved.Visible=cachedReport!=null&&cachedReport.Complete;useSaved.SetBounds(22,272,Math.Min(380,box.Width-44),40);services.Visible=true;services.SetBounds(22,112,box.Width-44,42);families.Visible=true;families.SetBounds(22,174,box.Width-44,42);}
        if(step==2){check.Visible=!busy;}
        if(step>=2){journalHost.Visible=true;journalHost.SetBounds(22,step==2&&mode.SelectedIndex==0?290:180,box.Width-44,Math.Max(60,box.Height-(step==2&&mode.SelectedIndex==0?400:290)));clear.Visible=true;}
        if(step==3){apply.Visible=results.Visible=true;results.SetBounds(box.Width-222,112,200,40);strategies.Visible=assignments==null&&ranked.Length>0;strategies.SetBounds(22,112,box.Width-264,42);}
        buttons.Controls.SetChildIndex(previous,0);buttons.Controls.SetChildIndex(forward,1);
      };refreshSteps=paintSteps;
      mode.SelectedIndexChanged+=(s,e)=>{moduleChoices.SetChecked(0,mode.SelectedIndex==1);step=0;paintSteps();};moduleChoices.CheckedItemsChanged+=(s,e)=>paintSteps();
      check.EnabledChanged+=(s,e)=>{if(!busy&&apply.Enabled)step=3;paintSteps();};
paintSteps();box.Disposed+=(s,e)=>{if(setupCancellation!=null)setupCancellation.Cancel();if(stagedTelegramOwned&&!planApplied){telegramBridge.Stop();stagedTelegramOwned=false;}};
    }
    static string SetupDestinationLabel(string value){return value=="direct"?"напрямую":value=="zapret"?"Zapret":value=="proxy"?"VPN":"нет подтверждённого пути";}
    async Task<ZapretCheckRow> MeasureSetupLive(NetworkCore network,ZapretService[] services,bool proxy,CancellationTokenSource cancellation,Action<string> progress){if(services.Length==0)return new ZapretCheckRow{Name="Без обхода",Services=new List<ZapretServiceResult>()};var report=new ZapretCheckReport{Settings=new ZapretSettings{CheckServices=services.Select(x=>x.Id).ToList()},ServiceIds=services.Select(x=>x.Id).ToList()};var live=OpenLiveResults(report,proxy?"Мастер · VPN / WARP":"Мастер · без обхода",cancellation);try{var row=await SetupServiceProbe.Measure(network,services,proxy,cancellation.Token,progress,value=>report.Rows.Add(value));report.Complete=true;return row;}finally{live.Finish();}}
    Control ShowSetupResults(ZapretCheckReport report,Action<ZapretCheckRow> choose,Action<ZapretCheckRow,ZapretService> chooseService=null){
      Panel veil=UiTheme.Simple?(Panel)new Panel{Name="mainResultSection",Location=new Point(234,72),Size=new Size(ClientSize.Width-250,ClientSize.Height-88),Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right,BackColor=Color.FromArgb(12,17,31)}:new GlassBackdrop(blueDashboard){Dock=DockStyle.Fill};var popup=new GlassPopupPanel{Inline=UiTheme.Simple,Size=new Size(Math.Min(1300,ClientSize.Width-40),Math.Min(620,ClientSize.Height-40))};veil.Controls.Add(popup);Action layout=()=>{if(UiTheme.Simple)popup.SetBounds(0,0,veil.Width,veil.Height);else popup.Location=new Point((veil.Width-popup.Width)/2,(veil.Height-popup.Height)/2);};veil.Resize+=(s,e)=>layout();layout();
      var caption=L("Результаты · мастер · "+(report.FinishedAt==DateTime.MinValue?DateTime.Now-report.StartedAt:report.FinishedAt-report.StartedAt).ToString(@"hh\:mm\:ss"),18,true);caption.SetBounds(24,20,popup.Width-110,40);popup.Controls.Add(caption);
      var close=new GlassClose{Location=new Point(popup.Width-64,20)};close.Click+=(s,e)=>veil.Dispose();if(!UiTheme.Simple)popup.Controls.Add(close);else{var back=B("Назад",(s,e)=>veil.Dispose());back.SetBounds(popup.Width-148,popup.Height-47,124,36);back.Anchor=AnchorStyles.Bottom|AnchorStyles.Right;popup.Controls.Add(back);}
      var table=new ZapretResultTable{VisibleServices=ZapretChecks.Selected(report.ServiceIds??report.Settings.CheckServices).Concat(report.Rows.Any(r=>r.Services.Any(v=>v.Id=="discord-voice"))?new[]{DiscordVoiceScores.Service}:new ZapretService[0]).ToArray(),CanApply=choose!=null,ActionCaption="Выбрать",Rows=report.Rows.Where(x=>x.StrategyId==null).Concat(ZapretChecks.Rank(report.Rows)).ToArray()};table.SetBounds(24,80,popup.Width-48,popup.Height-140);table.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;popup.Controls.Add(table);table.CanApply=chooseService!=null;if(chooseService!=null)table.ApplyService+=(row,service)=>{chooseService(row,service);veil.Dispose();};
      var hint=L(report.MediaProbeRevision<2?"Сохранён прежний видеотест — для актуальных результатов повторите проверку.":choose==null?"Результаты проверки. Выбор выходов и стратегий выполняется отдельным шагом мастера.":"Выбор конфига не включает Zapret. Применение — кнопкой «Применить план» в мастере.",10,false,Muted);hint.AutoSize=false;hint.SetBounds(24,popup.Height-50,popup.Width-(UiTheme.Simple?190:48),40);hint.Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;popup.Controls.Add(hint);Controls.Add(veil);veil.BringToFront();layout();return veil;
    }
  }
}
