using System;using System.Collections.Generic;using System.IO;using System.Linq;using System.Security.Cryptography;using System.Text;using System.Threading.Tasks;using System.Web.Script.Serialization;
namespace SplifyWin {
 public sealed class PresetBundleRow {public string Url{get;set;}public string Name{get;set;}public string OriginalName{get;set;}}
 public sealed class PresetBundle {public int Version{get;set;}public List<PresetBundleRow> Catalog{get;set;}public Dictionary<string,string> Texts{get;set;}}
 public static class PresetStorage {
  static readonly object gate=new object();static PresetBundle bundle;
  static PresetBundle Bundle{get{lock(gate){if(bundle==null)using(var input=BundledResources.Open("SplifyWin.Presets.bundle")){if(input==null)throw new InvalidOperationException("Встроенные списки пресетов отсутствуют.");using(var reader=new StreamReader(input,Encoding.UTF8))bundle=new JavaScriptSerializer{MaxJsonLength=Int32.MaxValue}.Deserialize<PresetBundle>(reader.ReadToEnd());}return bundle;}}}
  public static RoutePreset[] Review(RoutePreset[] original){var rows=Bundle.Catalog.ToDictionary(r=>r.Url,StringComparer.Ordinal);return original.Where(p=>rows.ContainsKey(p.Url)).Select(p=>{p.OriginalName=p.Name;p.Name=ReviewedName(p,rows[p.Url].Name);return p;}).ToArray();}
  static string ReviewedName(RoutePreset preset,string reviewed){if(preset.AdBlock){if(preset.SourceOwner=="neomikanagi"&&preset.File=="megamori.list")return "Megamori (блок рекламы)";if(preset.SourceOwner=="neomikanagi"&&preset.File=="ads-all-lite.list")return "Megamori lite (блок рекламы)";if(preset.SourceOwner=="burjuyz"&&preset.Repository=="RuRulesets")return "AdAway (блок рекламы)";if(preset.SourceOwner=="StevenBlack"&&preset.Repository=="hosts")return "StevenBlack (блок рекламы)";}return reviewed;}
  public static bool Contains(string url){return Bundle.Texts.ContainsKey(url);}
  static string Cache(string root){return Path.Combine(root,"preset-lists","current.json");}
  static readonly Dictionary<string,Dictionary<string,string>> cached=new Dictionary<string,Dictionary<string,string>>(StringComparer.OrdinalIgnoreCase);
  static readonly Dictionary<string,string> stamps=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);
  static string Stamp(string path){var file=new FileInfo(path);return file.Exists?file.Length+":"+file.LastWriteTimeUtc.Ticks:"missing";}
  public static string[] AllSources{get{return Bundle.Texts.Keys.OrderBy(x=>x,StringComparer.Ordinal).ToArray();}}
  static Dictionary<string,string> CacheData(string root){string path=Cache(root);Dictionary<string,string> data;string stamp=Stamp(path),oldStamp;if(cached.TryGetValue(path,out data)&&stamps.TryGetValue(path,out oldStamp)&&oldStamp==stamp)return data;try{data=File.Exists(path)?new JavaScriptSerializer{MaxJsonLength=Int32.MaxValue}.Deserialize<Dictionary<string,string>>(File.ReadAllText(path,Encoding.UTF8)):new Dictionary<string,string>();data=(data??new Dictionary<string,string>()).Where(p=>Contains(p.Key)&&Valid(p.Key,p.Value)).ToDictionary(p=>p.Key,p=>p.Value);}catch(IOException){data=new Dictionary<string,string>();}catch(ArgumentException){data=new Dictionary<string,string>();}cached[path]=data;stamps[path]=stamp;return data;}
  public static string Read(string root,string url){lock(gate){var cache=CacheData(root);string text;if(cache.TryGetValue(url,out text))return text;if(Bundle.Texts.TryGetValue(url,out text))return text;throw new InvalidOperationException("Нет локального списка: "+url);}}
  static bool Valid(string url,string text){if(String.IsNullOrWhiteSpace(text)||text.Length>10*1024*1024||text.TrimStart().StartsWith("<"))return false;try{if(Bundle.Catalog.Any(r=>r.Url==url))return RouteCompiler.Parse(text).Values.Sum(v=>v.Count)>0;if(url==HostsCandidates.MalwSource)return HostsCandidates.ParseLines(text,"chatgpt",url).Count>0;if(url==HostsRepair.Source)return HostsCandidates.ParseScript(text,"instagram").Count>0;if(OutsideRussiaPreset.Sources.Contains(url))return RouteCompiler.Parse(text)["ip_cidr"].Count>0;return false;}catch{return false;}}
  public static async Task Update(string root,IEnumerable<string> urls,Func<string,Task<string>> fetch,Action<int,int> progress=null){var selected=urls.Distinct().ToArray();var staged=new Dictionary<string,string>();foreach(var url in selected){if(!Contains(url))throw new InvalidOperationException("Неизвестный источник пресета.");string text=await fetch(url);if(!await Task.Run(()=>Valid(url,text)))throw new FormatException("Источник вернул некорректный список: "+url);staged[url]=text;if(progress!=null)progress(staged.Count,selected.Length);}await Task.Run(()=>{lock(gate){var data=new Dictionary<string,string>(CacheData(root));foreach(var item in staged)data[item.Key]=item.Value;string path=Cache(root);Directory.CreateDirectory(Path.GetDirectoryName(path));string temp=path+"."+Guid.NewGuid().ToString("N")+".tmp";try{File.WriteAllText(temp,new JavaScriptSerializer{MaxJsonLength=Int32.MaxValue}.Serialize(data),new UTF8Encoding(false));if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);cached[path]=data;stamps[path]=Stamp(path);}finally{if(File.Exists(temp))File.Delete(temp);}}});}
  public static string[] Sources(RoutePreset preset){return (preset.Parts??new[]{preset}).Select(p=>p.Url).Distinct().ToArray();}
  public static Dictionary<RouteList,string> UpdatedRoutes(string root,IEnumerable<RouteList> routes){var result=new Dictionary<RouteList,string>();foreach(var route in routes){var urls=RouteSources.Urls(route);if(urls.Length==0||urls.Any(url=>!Contains(url)))continue;string text=RouteSources.UpdatedText(route,String.Join("\n",urls.Select(url=>Read(root,url))));RouteCompiler.Parse(text);result[route]=text;}return result;}
  public static void NormalizeNames(IEnumerable<RouteList> routes){foreach(var route in routes){var urls=RouteSources.Urls(route);var presets=RoutePresets.Items.Where(p=>urls.Contains(p.Url)).ToArray();if(presets.Length==0)continue;Func<string,string> canonical=value=>{var found=presets.FirstOrDefault(p=>value==p.OriginalName||value==p.Name||value==p.OriginalName+" · "+p.Kind||value==p.Name+" · "+p.Kind);return found==null?value:found.Name;};route.Name=canonical(route.Name);if(route.PresetNames!=null)route.PresetNames=route.PresetNames.Select(canonical).Distinct().ToList();}}
  public static Task<string> Load(NetworkCore core,RoutePreset preset){return Task.FromResult(String.Join("\n",Sources(preset).Select(url=>Read(core.DataRoot,url))));}
 }
}
