using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace SplifyWin {
  public static class VpnPresetRules {
    public static readonly string[] RussiaTags={"mcrf-geoip-ru","mcrf-geosite-ru","mcrf-tld-ru"};
    public static readonly string[] TorrentApps={"qbittorrent.exe","utorrent.exe","bittorrent.exe","transmission-qt.exe","deluge.exe","tixati.exe","biglybt.exe","vuze.exe","aria2c.exe","webtorrent.exe","picotorrent.exe"};
    static Dictionary<string,object> D(params object[] values){var d=new Dictionary<string,object>();for(int i=0;i<values.Length;i+=2)d[(string)values[i]]=values[i+1];return d;}
    public static object[] RussiaSets(){return new[]{D("type","remote","tag",RussiaTags[0],"format","binary","url","https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-ru.srs","http_client",D("domain_resolver","bootstrap"),"update_interval","1d"),D("type","remote","tag",RussiaTags[1],"format","binary","url","https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ru.srs","http_client",D("domain_resolver","bootstrap"),"update_interval","1d"),D("type","remote","tag",RussiaTags[2],"format","binary","url","https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tld-ru.srs","http_client",D("domain_resolver","bootstrap"),"update_interval","1d")};}
    public static List<object> DirectRules(IEnumerable<RouteList> routes){var lists=routes.Where(l=>l.Enabled&&l.Target=="proxy").ToArray();var rules=new List<object>();if(lists.Any(l=>l.ExcludeRussia))rules.Add(D("rule_set",RussiaTags,"action","route","outbound","direct"));if(lists.Any(l=>l.ExcludeTorrents)){rules.Add(D("protocol",new[]{"bittorrent"},"action","route","outbound","direct"));rules.Add(D("process_name",TorrentApps,"action","route","outbound","direct"));}foreach(var list in lists.Where(l=>!String.IsNullOrWhiteSpace(l.ExcludedText)))foreach(var rule in RouteCompiler.Compile(new RouteList{Text=list.ExcludedText,Target="direct",MatchMode="addresses"},"direct"))rules.Add(rule);if(lists.Any(l=>l.ExcludeRussia||l.ExcludeTorrents))rules.Add(D("ip_is_private",true,"action","route","outbound","direct"));return rules;}
  }
  public sealed partial class MainForm {
    Task<RouteList> ChooseVpnConstructor(RouteList current){
      var done=new TaskCompletionSource<RouteList>();var veil=new GlassBackdrop(blueDashboard){Dock=DockStyle.Fill};var popup=new GlassPopupPanel{Size=new Size(Math.Min(960,ClientSize.Width-40),Math.Min(690,ClientSize.Height-40))};veil.Controls.Add(popup);Action layout=()=>popup.Location=new Point((veil.Width-popup.Width)/2,(veil.Height-popup.Height)/2);veil.Resize+=(s,e)=>layout();
      Add(popup,L("Конструктор маршрута VPN",18,true),24,18);var hint=L("«Да» — через VPN; «Нет» — напрямую, с приоритетом над VPN-правилами.\nРФ: GeoIP / Geosite. Торренты: протокол и известные клиенты; распознавание не гарантировано.",10,false,Muted);hint.AutoSize=false;hint.SetBounds(24,62,popup.Width-48,60);popup.Controls.Add(hint);
      var grid=Grid();grid.Name="vpnPresetConstructor";grid.SetBounds(24,130,popup.Width-48,Math.Max(100,popup.Height-335));grid.Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;grid.ReadOnly=false;grid.MultiSelect=false;grid.Columns.Add("service","Сервис / категория");grid.Columns.Add(new DataGridViewCheckBoxColumn{Name="yes",HeaderText="Да · VPN",Width=115,AutoSizeMode=DataGridViewAutoSizeColumnMode.None});grid.Columns.Add(new DataGridViewCheckBoxColumn{Name="no",HeaderText="Нет · напрямую",Width=165,AutoSizeMode=DataGridViewAutoSizeColumnMode.None});grid.Columns[0].ReadOnly=true;grid.Columns.Add("source","Источник");grid.Columns[3].ReadOnly=true;popup.Controls.Add(grid);
      grid.Rows.Add("Весь интернет",current!=null&&(current.InvertAddresses||current.Text=="0.0.0.0/0\n::/0"),false);grid.Rows.Add("РФ · GeoIP + Geosite",false,current==null||current.ExcludeRussia);grid.Rows.Add("Торрент-соединения и клиенты",false,current==null||current.ExcludeTorrents);grid.Rows[0].Cells[2].ReadOnly=true;grid.Rows[1].Cells[1].ReadOnly=true;grid.Rows[2].Cells[1].ReadOnly=true;
      foreach(var group in RoutePresets.Items.Where(p=>!p.OutsideRussia&&!p.AdBlock).GroupBy(p=>p.Name)){int row=grid.Rows.Add(group.Key,current!=null&&(current.PresetNames??new List<string>()).Any(p=>p==group.Key||p.StartsWith(group.Key+" · ")),false,String.Join(", ",group.Select(p=>p.SourceLabel).Distinct()));grid.Rows[row].Tag=group.ToArray();}
      bool changing=false;grid.CurrentCellDirtyStateChanged+=(s,e)=>{if(grid.IsCurrentCellDirty)grid.CommitEdit(DataGridViewDataErrorContexts.Commit);};grid.CellValueChanged+=(s,e)=>{if(changing||e.RowIndex<0||e.ColumnIndex<1||e.ColumnIndex>2)return;changing=true;try{var row=grid.Rows[e.RowIndex];if(Convert.ToBoolean(row.Cells[e.ColumnIndex].Value)){row.Cells[e.ColumnIndex==1?2:1].Value=false;if(e.RowIndex>=3&&e.ColumnIndex==1)grid.Rows[0].Cells[1].Value=false;}}finally{changing=false;}};
      var extraHost=new GlassFieldPanel{Location=new Point(24,popup.Height-160),Size=new Size(popup.Width-48,50),Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right};popup.Controls.Add(extraHost);var extra=new TextBox{Name="vpnConstructorCustom",BorderStyle=BorderStyle.None,BackColor=GlassFieldPanel.InputColor,ForeColor=Ink,Location=new Point(12,12),Width=extraHost.Width-24,Text=current==null||current.InvertAddresses||ExitDnsRouting.AllInternet(current)?"":current.CustomText??current.Text};extraHost.Controls.Add(extra);var custom=L("Дополнительно: домены / IP через VPN (для URL и приложений — ручной редактор).",9,false,Muted);custom.SetBounds(24,popup.Height-190,popup.Width-48,24);custom.Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;popup.Controls.Add(custom);
      bool busy=false;var save=B("Сохранить выбор",async(s,e)=>{if(busy)return;busy=true;((Control)s).Enabled=false;grid.Enabled=false;try{grid.EndEdit();bool all=Convert.ToBoolean(grid.Rows[0].Cells[1].Value);var yes=new List<string>();var no=new List<string>();var sources=new List<string>();var names=new List<string>();foreach(DataGridViewRow row in grid.Rows){var presets=row.Tag as RoutePreset[];if(presets==null)continue;bool include=Convert.ToBoolean(row.Cells[1].Value),exclude=Convert.ToBoolean(row.Cells[2].Value);if(!include&&!exclude)continue;foreach(var preset in presets){hint.Text="Читаем локальный пресет «"+preset.Name+" · "+preset.Kind+"»…";var text=await core.DownloadTextAsync(preset.Url);RouteCompiler.Parse(text);if(include){yes.Add(text);sources.Add(preset.Url);}else no.Add(text);}if(include)names.Add(Convert.ToString(row.Cells[0].Value));}
        if(!String.IsNullOrWhiteSpace(extra.Text))yes.Add(extra.Text);if(!all&&yes.Count==0)throw new InvalidOperationException("Отметьте сервисы в «Да» или выберите весь интернет.");var route=new RouteList{Id=current==null?Guid.NewGuid().ToString("N"):current.Id,Name=all?OutsideRussiaPreset.Name:"VPN · выбранные сервисы",Target="proxy",MatchMode="addresses",Text=all?"0.0.0.0/0\n::/0":String.Join("\n",yes),ExcludeRussia=Convert.ToBoolean(grid.Rows[1].Cells[2].Value),ExcludeTorrents=Convert.ToBoolean(grid.Rows[2].Cells[2].Value),ExcludedText=String.Join("\n",no),CustomText=extra.Text.Trim(),SourceUrls=all?null:sources,PresetNames=names};if(all&&!route.ExcludeRussia)route.Name="VPN · весь интернет";RouteCompiler.Compile(route,"proxy");done.TrySetResult(route);veil.Dispose();
      }catch(Exception ex){if(!hint.IsDisposed)hint.Text="Не сохранено: "+ex.Message;}finally{busy=false;if(!((Control)s).IsDisposed)((Control)s).Enabled=true;if(!grid.IsDisposed)grid.Enabled=true;}},true);save.SetBounds(24,popup.Height-65,220,40);save.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;popup.Controls.Add(save);
      var manual=B("Ручной редактор",async(s,e)=>{if(busy)return;var result=await ChooseWizardRoute(current);if(result!=null){if(result.Target=="proxy"){grid.EndEdit();result.ExcludeRussia=Convert.ToBoolean(grid.Rows[1].Cells[2].Value);result.ExcludeTorrents=Convert.ToBoolean(grid.Rows[2].Cells[2].Value);}done.TrySetResult(result);veil.Dispose();}});manual.SetBounds(260,popup.Height-65,220,40);manual.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;popup.Controls.Add(manual);var cancel=B("Отмена",(s,e)=>{if(!busy)veil.Dispose();});cancel.SetBounds(popup.Width-180,popup.Height-65,156,40);cancel.Anchor=AnchorStyles.Bottom|AnchorStyles.Right;popup.Controls.Add(cancel);veil.Disposed+=(s,e)=>done.TrySetResult(null);Controls.Add(veil);veil.BringToFront();layout();return done.Task;
    }
  }
}
