using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace SplifyWin {
 public sealed partial class MainForm {
  async Task<bool> EditZapretProfile(ZapretProfile original){
   if(zapretCancellation!=null||setupCancellation!=null||discordVoiceChecking){Toast("Дождитесь завершения проверки");return false;}
   EnsureZapretProfiles();zapret.Prepare();var catalog=ZapretCatalog.Load(zapret.DirectoryPath).Where(s=>s.Available).ToArray();var lists=state.Lists.ToArray();var presets=RoutePresets.Groups.Where(p=>!p.OutsideRussia).ToArray();var source=original??new ZapretProfile{Enabled=false};var customLists=lists.Where(l=>l.Target=="zapret"&&l.ZapretProfileId==source.Id&&(l.BuiltinPreset=="zapret-profile-custom:"+source.Id||l.Name==source.Name+" · свои записи")&&RouteSources.Urls(l).Length==0).ToArray();
   var done=new TaskCompletionSource<bool>();var veil=new GlassBackdrop(blueDashboard){Dock=DockStyle.Fill};var popup=new GlassPopupPanel{Size=new Size(Math.Min(840,ClientSize.Width-40),Math.Min(580,ClientSize.Height-32))};veil.Controls.Add(popup);Action layout=()=>popup.Location=new Point((veil.Width-popup.Width)/2,(veil.Height-popup.Height)/2);veil.Resize+=(s,e)=>layout();
   Add(popup,L(original==null?"Новый профиль Zapret":"Изменить профиль Zapret",18,true),24,20);
   var nameLabel=L("Название профиля",11,true);nameLabel.SetBounds(24,60,popup.Width-48,22);popup.Controls.Add(nameLabel);
   var nameHost=new GlassFieldPanel{Location=new Point(24,82),Size=new Size(popup.Width-48,38)};var name=T();name.Name="zapretEditName";name.Text=source.Name;name.BorderStyle=BorderStyle.None;name.BackColor=GlassFieldPanel.InputColor;name.SetBounds(12,9,nameHost.Width-24,24);nameHost.Controls.Add(name);popup.Controls.Add(nameHost);
   var strategy=new GlassPicker{Name="zapretEditStrategy",FlatSurface=true,Location=new Point(24,132),Width=popup.Width-48};strategy.SetItems(new[]{"Выберу позже"}.Concat(catalog.Select(c=>c.ShortName)));strategy.SelectedIndex=Math.Max(0,Array.FindIndex(catalog,c=>c.Id==source.Settings.Strategy)+1);popup.Controls.Add(strategy);
   var scope=new GlassPicker{Name="zapretEditPresets",MultiSelect=true,EmptySelectionText="Пресеты",Location=new Point(24,184),Width=popup.Width-48};scope.SetItems(lists.Select(l=>ZapretStrategy.CleanLabel(l.Name)).Concat(presets.Select(p=>"Пресет: "+p.DisplayName)));scope.ItemSource=i=>i<lists.Length?RouteSources.SourceLabel(lists[i]):presets[i-lists.Length].SourceLabel;scope.ItemHint=i=>i<lists.Length?"Ваш сохранённый список: "+lists[i].Name:presets[i-lists.Length].Description;for(int i=0;i<lists.Length;i++)if(!customLists.Contains(lists[i])&&lists[i].Target=="zapret"&&lists[i].ZapretProfileId==source.Id)scope.SetChecked(i,true);popup.Controls.Add(scope);
   var ownLabel=L("Свои домены, IP/CIDR или app:имя.exe (необязательно)",10,false,Muted);ownLabel.SetBounds(24,238,popup.Width-48,28);popup.Controls.Add(ownLabel);var ownHost=new GlassFieldPanel{Location=new Point(24,272),Size=new Size(popup.Width-48,Math.Max(70,popup.Height-414))};var own=new GlassLogBox{Name="zapretEditScope",BorderStyle=BorderStyle.None,BackColor=GlassFieldPanel.InputColor,ForeColor=Ink,Font=Font,WordWrap=false};own.Text=String.Join("\n",customLists.Select(l=>l.Text));ownHost.Controls.Add(own);own.InstallRails(ownHost);popup.Controls.Add(ownHost);
   var mode=new GlassPicker{Name="zapretEditMatchMode",FlatSurface=true,Location=new Point(24,popup.Height-126),Width=popup.Width-320};mode.SetItems(new[]{"Приложения ИЛИ адреса","Только адреса","Только приложения","Приложения И адреса","Кроме приложений"});var modes=new[]{"any","addresses","apps","in-apps","except-apps"};mode.SelectedIndex=Math.Max(0,Array.IndexOf(modes,source.Settings.MatchMode));popup.Controls.Add(mode);
   var enabled=new GlassToggle{Text="Запускать",Checked=source.Enabled,Location=new Point(popup.Width-278,popup.Height-126),Width=250};popup.Controls.Add(enabled);
   Action selectedStrategy=()=>{enabled.Enabled=strategy.SelectedIndex>0;if(!enabled.Enabled)enabled.Checked=false;};strategy.SelectedIndexChanged+=(s,e)=>selectedStrategy();selectedStrategy();
   bool busy=false;var save=B("Сохранить",async(s,e)=>{if(busy)return;if(String.IsNullOrWhiteSpace(name.Text)){Toast("Введите название профиля");return;}busy=true;((Control)s).Enabled=false;
    try{var selected=scope.SelectedIndices;source=original==null?source:state.ZapretProfiles.Single(p=>p.Id==source.Id);lists=state.Lists.ToArray();var staged=new List<RouteList>();foreach(int i in selected.Where(i=>i>=lists.Length)){var preset=presets[i-lists.Length];string text=await PresetStorage.Load(core,preset);var route=new RouteList{Name=preset.Name,Text=text,SourceUrls=PresetStorage.Sources(preset).ToList(),PresetNames=new List<string>{preset.Name},MatchMode="addresses",Target="zapret",ZapretProfileId=source.Id};RouteCompiler.Compile(route,"direct");staged.Add(route);}if(staged.Count>1)staged=new List<RouteList>{RouteSources.Merge(staged)};
     if(!String.IsNullOrWhiteSpace(own.Text)){var custom=new RouteList{Name=name.Text.Trim()+" · свои записи",Text=own.Text,Target="zapret",ZapretProfileId=source.Id,BuiltinPreset="zapret-profile-custom:"+source.Id,MatchMode=modes[mode.SelectedIndex]};ZapretScope.Validate(custom);staged.Add(custom);}
     if(enabled.Checked&&selected.Length==0&&staged.Count==0)throw new InvalidOperationException("Для включённого профиля выберите списки или укажите записи");
     if(!await OfferStopTun())return;bool saved=await ChangeActiveProfiles(()=>{if(original==null)state.ZapretProfiles.Add(source);source.Name=name.Text.Trim();source.Enabled=enabled.Checked;source.Settings.Strategy=strategy.SelectedIndex>0?catalog[strategy.SelectedIndex-1].Id:"";source.Settings.Family=strategy.SelectedIndex>0?catalog[strategy.SelectedIndex-1].Family:"";source.Settings.MatchMode=modes[mode.SelectedIndex];state.Lists.RemoveAll(l=>customLists.Contains(l));foreach(int i in Enumerable.Range(0,lists.Length)){if(customLists.Contains(lists[i]))continue;if(selected.Contains(i)){lists[i].Target="zapret";lists[i].ZapretProfileId=source.Id;lists[i].Enabled=true;}else if(lists[i].Target=="zapret"&&lists[i].ZapretProfileId==source.Id){lists[i].Target="direct";lists[i].ZapretProfileId=null;}}state.Lists.AddRange(staged);state.SelectedZapretProfileId=source.Id;state.Zapret=source.Settings;},()=>{});if(saved){done.TrySetResult(true);veil.Dispose();}
    }catch(Exception ex){GlassNotice.Show(this,ex.Message,"Профиль не сохранён");}finally{busy=false;if(!((Control)s).IsDisposed)((Control)s).Enabled=true;}
   },true);save.Name="zapretEditSave";save.SetBounds(24,popup.Height-66,180,40);popup.Controls.Add(save);var cancel=B("Отмена",(s,e)=>{if(!busy)veil.Dispose();});cancel.SetBounds(popup.Width-180,popup.Height-66,156,40);popup.Controls.Add(cancel);veil.Disposed+=(s,e)=>done.TrySetResult(false);Controls.Add(veil);veil.BringToFront();layout();return await done.Task;
  }
 }
}
