using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace SplifyWin {
 public sealed partial class MainForm {
  void ZapretBlue(Panel body){
   ZapretLegacyBlue(body);var family=body.Controls.Find("zapretCheckFamilies",true).First();var services=body.Controls.Find("zapretCheckServices",true).First();var start=body.Controls.Find("zapretAutoPick",true).First();var results=body.Controls.Find("zapretResults",true).First();var cancel=body.Controls.Find("zapretCancel",true).First();var status=body.Controls.Find("zapretStatus",true).First();foreach(Control control in body.Controls)control.Visible=false;
   foreach(var control in new[]{family,services,start,results,cancel,status}){body.Controls.Add(control);control.Anchor=AnchorStyles.Top|AnchorStyles.Left;control.Visible=control!=cancel;}
   var profiles=state.ZapretProfiles.ToArray();var lists=state.Lists.ToArray();var presets=RoutePresets.Groups.Where(p=>!p.OutsideRussia).ToArray();
   var grid=(GlassGrid)Grid();grid.Name="zapretOutputTable";grid.SetBounds(0,0,body.Width,42+Math.Max(1,(body.Height-326)/54)*54+2);grid.RowTemplate.Height=54;foreach(string c in new[]{"Профиль / выход","Стратегия","Включён","Пресеты"})grid.Columns.Add(c,c);grid.Columns[0].FillWeight=100;grid.Columns[1].FillWeight=140;grid.Columns[2].FillWeight=65;grid.Columns[3].FillWeight=180;body.Controls.Add(grid);
   var fields=new List<Tuple<int,int,Control>>();var picks=new Dictionary<string,GlassPicker>();var dirty=new HashSet<string>();bool busy=false;Button savePresets=null;
   for(int i=0;i<profiles.Length;i++){var p=profiles[i];int row=grid.Rows.Add(ZapretStrategy.CleanLabel(p.Name),"","","");grid.Rows[row].Tag=p;
    var catalog=ZapretCatalog.Load(zapret.DirectoryPath).Where(x=>x.Available).ToArray();var strategyPick=new GlassPicker{Name="zapretOutputStrategy_"+p.Id,FlatSurface=true};strategyPick.SetItems(new[]{"Выберу позже"}.Concat(catalog.Select(x=>x.ShortName)));strategyPick.ItemHint=n=>n>0?catalog[n-1].Name:"";strategyPick.SelectedIndex=String.IsNullOrEmpty(p.Settings.Strategy)?0:1+Array.FindIndex(catalog,x=>x.Id==p.Settings.Strategy);var colorReport=StrategyReport();strategyPick.ItemColor=colorIndex=>colorIndex<=0?VerdictColor(ServiceAccess.Unknown):ProfileStrategyColor(colorReport,p,catalog[colorIndex-1].Id);strategyPick.SurfaceColor=()=>VerdictFill(strategyPick.ItemColor(strategyPick.SelectedIndex));grid.Controls.Add(strategyPick);fields.Add(Tuple.Create(row,1,(Control)strategyPick));strategyPick.MouseWheel+=(s,e)=>grid.ShiftRows(e.Delta>0?-3:3);strategyPick.SelectedIndexChanged+=async(s,e)=>{if(busy)return;if(zapretCancellation!=null||setupCancellation!=null||discordVoiceChecking){Toast("Дождитесь завершения проверки");return;}busy=true;try{var selected=strategyPick.SelectedIndex<=0?null:catalog[strategyPick.SelectedIndex-1];await ChangeActiveProfiles(()=>{p.Settings.Strategy=selected==null?"":selected.Id;p.Settings.Family=selected==null?"":selected.Family;if(selected==null)p.Enabled=false;},()=>{});}catch(Exception ex){GlassNotice.Show(this,ex.Message,"Стратегия не изменена");}finally{busy=false;if(!IsDisposed&&page=="zapret")ShowPage("zapret");}};
    var toggle=new GlassToggle{Name="zapretOutputToggle_"+p.Id,Text="",Checked=p.Enabled};grid.Controls.Add(toggle);fields.Add(Tuple.Create(row,2,(Control)toggle));toggle.CheckedChanged+=async(s,e)=>{if(busy)return;bool previousEnabled=p.Enabled;bool desired=toggle.Checked;if(zapretCancellation!=null||setupCancellation!=null||byetubeCancellation!=null||discordVoiceChecking){busy=true;toggle.Checked=p.Enabled;busy=false;Toast("Дождитесь завершения проверки");return;}if(desired&&(!IsAdministrator()||ZapretRoutes.Lists(state,p.Id).Length==0||String.IsNullOrEmpty(p.Settings.Strategy))){busy=true;toggle.Checked=p.Enabled;busy=false;if(!IsAdministrator()){if(await ConfirmChange("Для включения Zapret нужны права Windows. Приложение перезапустится с запросом разрешения.","Получить права и перезапустить","Доступ Windows"))RequestElevation("--zapret");}else GlassNotice.Show(this,"Сначала выберите стратегию и сохраните пресеты.","Zapret");return;}busy=true;try{if(!await OfferStopTun())return;bool running=zapret.Running;if(await ChangeActiveProfiles(()=>p.Enabled=desired,()=>{})){if(desired&&!running)await StartSavedZapretProfiles(CancellationToken.None);}}catch(Exception ex){var restored=state.ZapretProfiles.FirstOrDefault(x=>x.Id==p.Id);if(restored!=null)restored.Enabled=previousEnabled;store.Save(state);GlassNotice.Show(this,ex.Message,"Профиль не включён");}finally{busy=false;if(!IsDisposed&&page=="zapret")ShowPage("zapret");}};
    var pick=new GlassPicker{Name="zapretOutputPresets_"+p.Id,MultiSelect=true,FlatSurface=true,EmptySelectionText="Выберите пресеты",SelectionCaption="Выбрано"};pick.SetItems(lists.Select(l=>ZapretStrategy.CleanLabel(l.Name)).Concat(presets.Select(x=>"Пресет: "+x.DisplayName)));pick.ItemSource=sourceIndex=>sourceIndex<lists.Length?RouteSources.SourceLabel(lists[sourceIndex]):presets[sourceIndex-lists.Length].SourceLabel;pick.ItemHint=n=>n<lists.Length?"Ваш сохранённый список: "+lists[n].Name:presets[n-lists.Length].Description;for(int n=0;n<lists.Length;n++)if(lists[n].Target=="zapret"&&lists[n].ZapretProfileId==p.Id)pick.SetChecked(n,true);pick.CheckedItemsChanged+=(s,e)=>{dirty.Add(p.Id);if(savePresets!=null){savePresets.Enabled=true;savePresets.Text="Сохранить изменения";}};pick.MouseWheel+=(s,e)=>grid.ShiftRows(e.Delta>0?-3:3);grid.Controls.Add(pick);fields.Add(Tuple.Create(row,3,(Control)pick));picks[p.Id]=pick;
   }
   Action arrange=()=>{foreach(var item in fields){var r=grid.GetCellDisplayRectangle(item.Item2,item.Item1,false);item.Item3.Visible=r.Top>=grid.ColumnHeadersHeight&&r.Bottom<=grid.Height;if(item.Item3.Visible){item.Item3.SetBounds(r.Left+6,r.Top+7,Math.Max(30,r.Width-24),r.Height-14);item.Item3.BringToFront();}}};grid.Scroll+=(s,e)=>{arrange();if(grid.IsHandleCreated&&!grid.IsDisposed)grid.BeginInvoke(arrange);};grid.Resize+=(s,e)=>arrange();grid.ColumnWidthChanged+=(s,e)=>arrange();
   int y=grid.Bottom+12;var add=B("Новый профиль",async(s,e)=>{if(!busy&&await EditZapretProfile(null))ShowPage("zapret");},true);add.SetBounds(0,y,180,38);body.Controls.Add(add);var edit=B("Изменить",async(s,e)=>{if(!busy&&grid.CurrentRow!=null&&await EditZapretProfile(grid.CurrentRow.Tag as ZapretProfile))ShowPage("zapret");});edit.SetBounds(192,y,140,38);body.Controls.Add(edit);
   var save=B("Пресеты сохранены",async(s,e)=>{if(busy||dirty.Count==0)return;busy=true;grid.Enabled=false;try{var owners=new Dictionary<int,string>();foreach(var id in picks.Keys)foreach(int n in picks[id].SelectedIndices.Where(n=>n<lists.Length)){if(owners.ContainsKey(n)&&owners[n]!=id)throw new InvalidOperationException("Один список выбран в разных профилях. Оставьте ему один выход");owners[n]=id;}var staged=new Dictionary<string,List<RouteList>>();foreach(var id in dirty){var selected=picks[id].SelectedIndices;var routes=new List<RouteList>();foreach(int n in selected.Where(n=>n>=lists.Length)){var preset=presets[n-lists.Length];var route=new RouteList{Name=preset.Name,Text=await PresetStorage.Load(core,preset),SourceUrls=PresetStorage.Sources(preset).ToList(),PresetNames=new List<string>{preset.Name},Target="zapret",ZapretProfileId=id,MatchMode="addresses"};ZapretScope.Validate(route);routes.Add(route);}if(routes.Count>1)routes=new List<RouteList>{RouteSources.Merge(routes)};staged[id]=routes;}if(!await OfferStopTun())return;bool saved=await ChangeActiveProfiles(()=>{foreach(var id in dirty){var selected=picks[id].SelectedIndices;for(int n=0;n<lists.Length;n++){if(selected.Contains(n)){lists[n].Target="zapret";lists[n].ZapretProfileId=id;lists[n].Enabled=true;}else if(lists[n].Target=="zapret"&&lists[n].ZapretProfileId==id){lists[n].Target="direct";lists[n].ZapretProfileId=null;}}state.Lists.AddRange(staged[id]);}},()=>{});if(saved){ShowPage("zapret");Toast("Списки и пресеты сохранены для "+dirty.Count+" профилей");}}catch(Exception ex){GlassNotice.Show(this,ex.Message,"Пресеты не сохранены");}finally{busy=false;if(!grid.IsDisposed)grid.Enabled=true;}});savePresets=save;save.Enabled=false;save.SetBounds(344,y,220,38);body.Controls.Add(save);
   var remove=B("Удалить",async(s,e)=>{if(busy||grid.CurrentRow==null)return;var p=grid.CurrentRow.Tag as ZapretProfile;if(state.ZapretProfiles.Count<2||state.Lists.Any(l=>l.Target=="zapret"&&l.ZapretProfileId==p.Id)){Toast("Сначала переназначьте его списки; один профиль должен остаться");return;}if(await ChangeActiveProfiles(()=>state.ZapretProfiles.Remove(p),()=>{})){EnsureZapretProfiles();ShowPage("zapret");}});remove.SetBounds(body.Width-124,y,124,38);body.Controls.Add(remove);
   var title=L("Начать проверку",14,true);title.SetBounds(0,y+52,body.Width,30);body.Controls.Add(title);var duration=L("Проверка займёт около 10 минут.",10,true,Color.FromArgb(255,220,110));duration.SetBounds(220,y+52,body.Width-220,30);body.Controls.Add(duration);family.SetBounds(0,y+90,(body.Width-16)/2,40);services.SetBounds((body.Width+16)/2,y+90,(body.Width-16)/2,40);start.SetBounds(0,body.Height-44,220,40);cancel.SetBounds(232,body.Height-44,140,40);results.SetBounds(body.Width-240,body.Height-44,240,40);status.SetBounds(0,y+138,body.Width,Math.Max(28,body.Height-y-188));arrange();
  }
 }
}
